// AUTO-GENERATED by scripts/genWordGameData.ts — do not edit by hand.
// Connections (Word Game) puzzles, mirrored for the admin web.
export type ConnectionsColor = 'yellow' | 'green' | 'blue' | 'purple';
export interface ConnectionsGroup {
  label: string;
  words: string[];
  color: ConnectionsColor;
}
export interface ConnectionsPuzzle {
  id: number;
  groups: ConnectionsGroup[];
}

export const CONNECTIONS_PUZZLES: ConnectionsPuzzle[] = [
  {
    "id": 1,
    "groups": [
      {
        "label": "Fruits",
        "color": "yellow",
        "words": [
          "APPLE",
          "MANGO",
          "GRAPE",
          "BANANA"
        ]
      },
      {
        "label": "Colors",
        "color": "green",
        "words": [
          "RED",
          "BLUE",
          "GREEN",
          "ORANGE"
        ]
      },
      {
        "label": "Countries",
        "color": "blue",
        "words": [
          "TURKEY",
          "CHILE",
          "JORDAN",
          "CHINA"
        ]
      },
      {
        "label": "Also a Brand",
        "color": "purple",
        "words": [
          "PUMA",
          "JAGUAR",
          "DOVE",
          "SHELL"
        ]
      }
    ]
  },
  {
    "id": 2,
    "groups": [
      {
        "label": "Kitchen Items",
        "color": "yellow",
        "words": [
          "SPOON",
          "FORK",
          "KNIFE",
          "PLATE"
        ]
      },
      {
        "label": "Weather",
        "color": "green",
        "words": [
          "THUNDER",
          "RAIN",
          "SNOW",
          "WIND"
        ]
      },
      {
        "label": "Musical Instruments",
        "color": "blue",
        "words": [
          "DRUM",
          "GUITAR",
          "PIANO",
          "VIOLIN"
        ]
      },
      {
        "label": "_____ Board",
        "color": "purple",
        "words": [
          "SKATE",
          "DART",
          "KEY",
          "CARD"
        ]
      }
    ]
  },
  {
    "id": 3,
    "groups": [
      {
        "label": "Malaysian Food",
        "color": "yellow",
        "words": [
          "RENDANG",
          "SATAY",
          "LAKSA",
          "ROTI"
        ]
      },
      {
        "label": "Furniture",
        "color": "green",
        "words": [
          "CHAIR",
          "TABLE",
          "SHELF",
          "DESK"
        ]
      },
      {
        "label": "Things That Are Round",
        "color": "blue",
        "words": [
          "COIN",
          "WHEEL",
          "CLOCK",
          "PIZZA"
        ]
      },
      {
        "label": "_____ Light",
        "color": "purple",
        "words": [
          "FLASH",
          "SPOT",
          "MOON",
          "HIGH"
        ]
      }
    ]
  },
  {
    "id": 4,
    "groups": [
      {
        "label": "Animals",
        "color": "yellow",
        "words": [
          "TIGER",
          "EAGLE",
          "DOLPHIN",
          "COBRA"
        ]
      },
      {
        "label": "Emotions",
        "color": "green",
        "words": [
          "HAPPY",
          "ANGRY",
          "SAD",
          "EXCITED"
        ]
      },
      {
        "label": "Types of Dance",
        "color": "blue",
        "words": [
          "SALSA",
          "WALTZ",
          "TANGO",
          "SWING"
        ]
      },
      {
        "label": "Can Follow \"SUN\"",
        "color": "purple",
        "words": [
          "FLOWER",
          "BURN",
          "RISE",
          "SET"
        ]
      }
    ]
  },
  {
    "id": 5,
    "groups": [
      {
        "label": "Breakfast Items",
        "color": "yellow",
        "words": [
          "TOAST",
          "CEREAL",
          "PANCAKE",
          "WAFFLE"
        ]
      },
      {
        "label": "Sports",
        "color": "green",
        "words": [
          "BADMINTON",
          "FOOTBALL",
          "CRICKET",
          "TENNIS"
        ]
      },
      {
        "label": "Parts of a House",
        "color": "blue",
        "words": [
          "ROOF",
          "WINDOW",
          "DOOR",
          "WALL"
        ]
      },
      {
        "label": "Things That Can Be \"BROKEN\"",
        "color": "purple",
        "words": [
          "HEART",
          "RECORD",
          "ICE",
          "NEWS"
        ]
      }
    ]
  },
  {
    "id": 6,
    "groups": [
      {
        "label": "Drinks",
        "color": "yellow",
        "words": [
          "WATER",
          "JUICE",
          "MILK",
          "SODA"
        ]
      },
      {
        "label": "Vehicles",
        "color": "green",
        "words": [
          "TRUCK",
          "PLANE",
          "BOAT",
          "TRAIN"
        ]
      },
      {
        "label": "Planets",
        "color": "blue",
        "words": [
          "MARS",
          "VENUS",
          "SATURN",
          "JUPITER"
        ]
      },
      {
        "label": "Also a Chocolate Bar",
        "color": "purple",
        "words": [
          "BOUNTY",
          "TWIRL",
          "BOOST",
          "KIT"
        ]
      }
    ]
  },
  {
    "id": 7,
    "groups": [
      {
        "label": "Clothes",
        "color": "yellow",
        "words": [
          "SHIRT",
          "JACKET",
          "PANTS",
          "HOODIE"
        ]
      },
      {
        "label": "Shapes",
        "color": "green",
        "words": [
          "CIRCLE",
          "SQUARE",
          "TRIANGLE",
          "DIAMOND"
        ]
      },
      {
        "label": "Things in a Classroom",
        "color": "blue",
        "words": [
          "MARKER",
          "ERASER",
          "PROJECTOR",
          "WHITEBOARD"
        ]
      },
      {
        "label": "Also a Card Suit",
        "color": "purple",
        "words": [
          "CLUB",
          "SPADE",
          "HEART",
          "JACK"
        ]
      }
    ]
  },
  {
    "id": 8,
    "groups": [
      {
        "label": "Vegetables",
        "color": "yellow",
        "words": [
          "CARROT",
          "POTATO",
          "ONION",
          "GARLIC"
        ]
      },
      {
        "label": "Jobs",
        "color": "green",
        "words": [
          "DOCTOR",
          "PILOT",
          "TEACHER",
          "LAWYER"
        ]
      },
      {
        "label": "Things With Strings",
        "color": "blue",
        "words": [
          "KITE",
          "PUPPET",
          "GUITAR",
          "BOW"
        ]
      },
      {
        "label": "_____ Stone",
        "color": "purple",
        "words": [
          "MILE",
          "KEY",
          "LIME",
          "SAND"
        ]
      }
    ]
  },
  {
    "id": 9,
    "groups": [
      {
        "label": "Body Parts",
        "color": "yellow",
        "words": [
          "ELBOW",
          "KNEE",
          "SHOULDER",
          "WRIST"
        ]
      },
      {
        "label": "Social Media",
        "color": "green",
        "words": [
          "TWITTER",
          "SNAPCHAT",
          "TIKTOK",
          "REDDIT"
        ]
      },
      {
        "label": "Things That Melt",
        "color": "blue",
        "words": [
          "ICE",
          "CHEESE",
          "BUTTER",
          "SNOW"
        ]
      },
      {
        "label": "Things That Are Also \"FIRE\"",
        "color": "purple",
        "words": [
          "ALARM",
          "TRUCK",
          "WORK",
          "PLACE"
        ]
      }
    ]
  },
  {
    "id": 10,
    "groups": [
      {
        "label": "Desserts",
        "color": "yellow",
        "words": [
          "CAKE",
          "BROWNIE",
          "COOKIE",
          "PUDDING"
        ]
      },
      {
        "label": "Flowers",
        "color": "green",
        "words": [
          "ROSE",
          "LILY",
          "DAISY",
          "TULIP"
        ]
      },
      {
        "label": "Superheroes",
        "color": "blue",
        "words": [
          "BATMAN",
          "FLASH",
          "THOR",
          "HULK"
        ]
      },
      {
        "label": "Also a Name",
        "color": "purple",
        "words": [
          "GRACE",
          "FAITH",
          "HOPE",
          "IRIS"
        ]
      }
    ]
  },
  {
    "id": 11,
    "groups": [
      {
        "label": "Stationery",
        "color": "yellow",
        "words": [
          "PENCIL",
          "ERASER",
          "RULER",
          "STAPLER"
        ]
      },
      {
        "label": "Ocean Creatures",
        "color": "green",
        "words": [
          "SHARK",
          "WHALE",
          "SQUID",
          "CORAL"
        ]
      },
      {
        "label": "Things You Charge",
        "color": "blue",
        "words": [
          "PHONE",
          "LAPTOP",
          "WATCH",
          "TABLET"
        ]
      },
      {
        "label": "Can Follow \"BOOK\"",
        "color": "purple",
        "words": [
          "WORM",
          "MARK",
          "SHELF",
          "STORE"
        ]
      }
    ]
  },
  {
    "id": 12,
    "groups": [
      {
        "label": "Footwear",
        "color": "yellow",
        "words": [
          "BOOTS",
          "SANDALS",
          "HEELS",
          "SNEAKERS"
        ]
      },
      {
        "label": "Trees",
        "color": "green",
        "words": [
          "OAK",
          "PINE",
          "MAPLE",
          "PALM"
        ]
      },
      {
        "label": "Things in a Bag",
        "color": "blue",
        "words": [
          "WALLET",
          "KEYS",
          "TISSUE",
          "CHARGER"
        ]
      },
      {
        "label": "Words Before \"HOUSE\"",
        "color": "purple",
        "words": [
          "WARE",
          "GREEN",
          "FIRE",
          "POWER"
        ]
      }
    ]
  },
  {
    "id": 13,
    "groups": [
      {
        "label": "Spices",
        "color": "yellow",
        "words": [
          "PEPPER",
          "GINGER",
          "CINNAMON",
          "TURMERIC"
        ]
      },
      {
        "label": "Types of Music",
        "color": "green",
        "words": [
          "POP",
          "JAZZ",
          "ROCK",
          "BLUES"
        ]
      },
      {
        "label": "Things at a Beach",
        "color": "blue",
        "words": [
          "SAND",
          "WAVE",
          "SHELL",
          "SURF"
        ]
      },
      {
        "label": "Also a Gemstone",
        "color": "purple",
        "words": [
          "RUBY",
          "JADE",
          "AMBER",
          "PEARL"
        ]
      }
    ]
  },
  {
    "id": 14,
    "groups": [
      {
        "label": "Rooms in a House",
        "color": "yellow",
        "words": [
          "KITCHEN",
          "BEDROOM",
          "BATHROOM",
          "GARAGE"
        ]
      },
      {
        "label": "Types of Bread",
        "color": "green",
        "words": [
          "BAGUETTE",
          "NAAN",
          "PITA",
          "CROISSANT"
        ]
      },
      {
        "label": "Movie Genres",
        "color": "blue",
        "words": [
          "COMEDY",
          "HORROR",
          "ACTION",
          "DRAMA"
        ]
      },
      {
        "label": "Things That Can Be \"DOUBLE\"",
        "color": "purple",
        "words": [
          "DUTCH",
          "AGENT",
          "TAKE",
          "CHECK"
        ]
      }
    ]
  },
  {
    "id": 15,
    "groups": [
      {
        "label": "Dairy Products",
        "color": "yellow",
        "words": [
          "CHEESE",
          "YOGURT",
          "CREAM",
          "BUTTER"
        ]
      },
      {
        "label": "Board Games",
        "color": "green",
        "words": [
          "CHESS",
          "MONOPOLY",
          "SCRABBLE",
          "RISK"
        ]
      },
      {
        "label": "Things in the Sky",
        "color": "blue",
        "words": [
          "CLOUD",
          "STAR",
          "RAINBOW",
          "MOON"
        ]
      },
      {
        "label": "Words After \"PAPER\"",
        "color": "purple",
        "words": [
          "BACK",
          "CLIP",
          "WEIGHT",
          "WORK"
        ]
      }
    ]
  },
  {
    "id": 16,
    "groups": [
      {
        "label": "Metals",
        "color": "yellow",
        "words": [
          "IRON",
          "GOLD",
          "SILVER",
          "COPPER"
        ]
      },
      {
        "label": "Hobbies",
        "color": "green",
        "words": [
          "PAINTING",
          "COOKING",
          "FISHING",
          "HIKING"
        ]
      },
      {
        "label": "Things That Spin",
        "color": "blue",
        "words": [
          "TOP",
          "WHEEL",
          "FAN",
          "GLOBE"
        ]
      },
      {
        "label": "_____ Ring",
        "color": "purple",
        "words": [
          "EAR",
          "BOXING",
          "SPRING",
          "KEY"
        ]
      }
    ]
  },
  {
    "id": 17,
    "groups": [
      {
        "label": "Fruits With Seeds",
        "color": "yellow",
        "words": [
          "WATERMELON",
          "PAPAYA",
          "GUAVA",
          "POMEGRANATE"
        ]
      },
      {
        "label": "Seasons",
        "color": "green",
        "words": [
          "SPRING",
          "SUMMER",
          "AUTUMN",
          "WINTER"
        ]
      },
      {
        "label": "Things That Buzz",
        "color": "blue",
        "words": [
          "BEE",
          "PHONE",
          "ALARM",
          "RAZOR"
        ]
      },
      {
        "label": "Words Before \"BALL\"",
        "color": "purple",
        "words": [
          "FOOT",
          "BASE",
          "BASKET",
          "SNOW"
        ]
      }
    ]
  },
  {
    "id": 18,
    "groups": [
      {
        "label": "Pets",
        "color": "yellow",
        "words": [
          "DOG",
          "CAT",
          "HAMSTER",
          "RABBIT"
        ]
      },
      {
        "label": "School Supplies",
        "color": "green",
        "words": [
          "NOTEBOOK",
          "PEN",
          "FOLDER",
          "CALCULATOR"
        ]
      },
      {
        "label": "Things That Drip",
        "color": "blue",
        "words": [
          "TAP",
          "CANDLE",
          "PAINT",
          "SWEAT"
        ]
      },
      {
        "label": "Also a Type of \"SHOT\"",
        "color": "purple",
        "words": [
          "MOON",
          "LONG",
          "BIG",
          "HEAD"
        ]
      }
    ]
  },
  {
    "id": 19,
    "groups": [
      {
        "label": "Insects",
        "color": "yellow",
        "words": [
          "ANT",
          "BEETLE",
          "FIREFLY",
          "CRICKET"
        ]
      },
      {
        "label": "Currencies",
        "color": "green",
        "words": [
          "RINGGIT",
          "DOLLAR",
          "POUND",
          "EURO"
        ]
      },
      {
        "label": "Things That Are Sticky",
        "color": "blue",
        "words": [
          "TAPE",
          "GLUE",
          "HONEY",
          "GUM"
        ]
      },
      {
        "label": "Can Follow \"WATER\"",
        "color": "purple",
        "words": [
          "FALL",
          "PROOF",
          "MARK",
          "MELON"
        ]
      }
    ]
  },
  {
    "id": 20,
    "groups": [
      {
        "label": "Berries",
        "color": "yellow",
        "words": [
          "BLUEBERRY",
          "RASPBERRY",
          "CRANBERRY",
          "BLACKBERRY"
        ]
      },
      {
        "label": "Things With Wheels",
        "color": "green",
        "words": [
          "BICYCLE",
          "TROLLEY",
          "SKATEBOARD",
          "SCOOTER"
        ]
      },
      {
        "label": "Things That Pop",
        "color": "blue",
        "words": [
          "BALLOON",
          "BUBBLE",
          "CORN",
          "CHAMPAGNE"
        ]
      },
      {
        "label": "Words After \"BREAK\"",
        "color": "purple",
        "words": [
          "FAST",
          "DOWN",
          "THROUGH",
          "AWAY"
        ]
      }
    ]
  },
  {
    "id": 21,
    "groups": [
      {
        "label": "Dog Breeds",
        "color": "yellow",
        "words": [
          "HUSKY",
          "POODLE",
          "BEAGLE",
          "LABRADOR"
        ]
      },
      {
        "label": "Ice Cream Flavors",
        "color": "green",
        "words": [
          "VANILLA",
          "STRAWBERRY",
          "MINT",
          "CARAMEL"
        ]
      },
      {
        "label": "Things at a Birthday Party",
        "color": "blue",
        "words": [
          "CAKE",
          "BALLOON",
          "CANDLE",
          "CONFETTI"
        ]
      },
      {
        "label": "Can Follow \"HAIR\"",
        "color": "purple",
        "words": [
          "BAND",
          "CUT",
          "LINE",
          "BRUSH"
        ]
      }
    ]
  },
  {
    "id": 22,
    "groups": [
      {
        "label": "Kitchen Appliances",
        "color": "yellow",
        "words": [
          "BLENDER",
          "TOASTER",
          "MICROWAVE",
          "KETTLE"
        ]
      },
      {
        "label": "Types of Pasta",
        "color": "green",
        "words": [
          "PENNE",
          "FUSILLI",
          "LASAGNA",
          "RIGATONI"
        ]
      },
      {
        "label": "Things You Wear on Your Head",
        "color": "blue",
        "words": [
          "CAP",
          "TURBAN",
          "HELMET",
          "CROWN"
        ]
      },
      {
        "label": "Can Precede \"SIDE\"",
        "color": "purple",
        "words": [
          "OUT",
          "IN",
          "FLIP",
          "BLIND"
        ]
      }
    ]
  },
  {
    "id": 23,
    "groups": [
      {
        "label": "Types of Map",
        "color": "yellow",
        "words": [
          "ROAD",
          "HEAT",
          "MIND",
          "TREASURE"
        ]
      },
      {
        "label": "Things in a Library",
        "color": "green",
        "words": [
          "SHELF",
          "CATALOG",
          "REFERENCE",
          "ARCHIVE"
        ]
      },
      {
        "label": "Dances",
        "color": "blue",
        "words": [
          "WALTZ",
          "SAMBA",
          "FOXTROT",
          "RUMBA"
        ]
      },
      {
        "label": "Words After \"BOOK\"",
        "color": "purple",
        "words": [
          "CASE",
          "KEEPER",
          "MARK",
          "LET"
        ]
      }
    ]
  },
  {
    "id": 24,
    "groups": [
      {
        "label": "Things That Are Red",
        "color": "yellow",
        "words": [
          "TOMATO",
          "FIRE",
          "BLOOD",
          "CHERRY"
        ]
      },
      {
        "label": "Card Games",
        "color": "green",
        "words": [
          "SNAP",
          "RUMMY",
          "POKER",
          "BRIDGE"
        ]
      },
      {
        "label": "Parts of a Camera",
        "color": "blue",
        "words": [
          "LENS",
          "SHUTTER",
          "FLASH",
          "SENSOR"
        ]
      },
      {
        "label": "Can Follow \"DARK\"",
        "color": "purple",
        "words": [
          "ROOM",
          "SIDE",
          "NESS",
          "HORSE"
        ]
      }
    ]
  },
  {
    "id": 25,
    "groups": [
      {
        "label": "Things in a Toolbox",
        "color": "yellow",
        "words": [
          "HAMMER",
          "WRENCH",
          "DRILL",
          "PLIERS"
        ]
      },
      {
        "label": "Types of Tea",
        "color": "green",
        "words": [
          "GREEN",
          "OOLONG",
          "CHAMOMILE",
          "JASMINE"
        ]
      },
      {
        "label": "Things That Glow",
        "color": "blue",
        "words": [
          "FIREFLY",
          "MOON",
          "EMBER",
          "SCREEN"
        ]
      },
      {
        "label": "Words Before \"STORM\"",
        "color": "purple",
        "words": [
          "BRAIN",
          "THUNDER",
          "SNOW",
          "FIRE"
        ]
      }
    ]
  },
  {
    "id": 26,
    "groups": [
      {
        "label": "Fruits That Are Orange",
        "color": "yellow",
        "words": [
          "MANGO",
          "PAPAYA",
          "PEACH",
          "APRICOT"
        ]
      },
      {
        "label": "Things in a Hospital",
        "color": "green",
        "words": [
          "STRETCHER",
          "SYRINGE",
          "WARD",
          "SCALPEL"
        ]
      },
      {
        "label": "Types of Clock",
        "color": "blue",
        "words": [
          "ALARM",
          "CUCKOO",
          "SUNDIAL",
          "DIGITAL"
        ]
      },
      {
        "label": "Can Follow \"HAND\"",
        "color": "purple",
        "words": [
          "SHAKE",
          "MADE",
          "RAIL",
          "STAND"
        ]
      }
    ]
  },
  {
    "id": 27,
    "groups": [
      {
        "label": "Baby Animals",
        "color": "yellow",
        "words": [
          "CUB",
          "FOAL",
          "KITTEN",
          "CALF"
        ]
      },
      {
        "label": "Things You Fold",
        "color": "green",
        "words": [
          "MAP",
          "TOWEL",
          "LETTER",
          "NAPKIN"
        ]
      },
      {
        "label": "Types of Bridge",
        "color": "blue",
        "words": [
          "ROPE",
          "ARCH",
          "CABLE",
          "DRAW"
        ]
      },
      {
        "label": "Can Precede \"FISH\"",
        "color": "purple",
        "words": [
          "SWORD",
          "STAR",
          "CAT",
          "BLOW"
        ]
      }
    ]
  },
  {
    "id": 28,
    "groups": [
      {
        "label": "Things in Space",
        "color": "yellow",
        "words": [
          "COMET",
          "NEBULA",
          "ASTEROID",
          "ORBIT"
        ]
      },
      {
        "label": "Types of Shoe",
        "color": "green",
        "words": [
          "LOAFER",
          "STILETTO",
          "OXFORD",
          "MOCCASIN"
        ]
      },
      {
        "label": "Things That Are Flat",
        "color": "blue",
        "words": [
          "PANCAKE",
          "PLATEAU",
          "SHEET",
          "ROAD"
        ]
      },
      {
        "label": "Words After \"BACK\"",
        "color": "purple",
        "words": [
          "PACK",
          "FIRE",
          "YARD",
          "BONE"
        ]
      }
    ]
  },
  {
    "id": 29,
    "groups": [
      {
        "label": "Things at a Campsite",
        "color": "yellow",
        "words": [
          "TENT",
          "LANTERN",
          "SLEEPING BAG",
          "BONFIRE"
        ]
      },
      {
        "label": "Types of Soil",
        "color": "green",
        "words": [
          "CLAY",
          "LOAM",
          "SAND",
          "SILT"
        ]
      },
      {
        "label": "Things That Have Stripes",
        "color": "blue",
        "words": [
          "ZEBRA",
          "TIGER",
          "BEE",
          "BARRICADE"
        ]
      },
      {
        "label": "Can Follow \"UNDER\"",
        "color": "purple",
        "words": [
          "COVER",
          "LINE",
          "MINE",
          "PASS"
        ]
      }
    ]
  },
  {
    "id": 30,
    "groups": [
      {
        "label": "Things in a Playground",
        "color": "yellow",
        "words": [
          "SWING",
          "SLIDE",
          "SEESAW",
          "SANDBOX"
        ]
      },
      {
        "label": "Types of Noodle",
        "color": "green",
        "words": [
          "UDON",
          "VERMICELLI",
          "RAMEN",
          "SOBA"
        ]
      },
      {
        "label": "Things That Overflow",
        "color": "blue",
        "words": [
          "RIVER",
          "GLASS",
          "INBOX",
          "TRASH"
        ]
      },
      {
        "label": "Words Before \"LINE\"",
        "color": "purple",
        "words": [
          "HAIR",
          "BASE",
          "DEAD",
          "GUIDE"
        ]
      }
    ]
  },
  {
    "id": 31,
    "groups": [
      {
        "label": "Parts of a Ship",
        "color": "yellow",
        "words": [
          "HULL",
          "MAST",
          "STERN",
          "ANCHOR"
        ]
      },
      {
        "label": "Things Made of Glass",
        "color": "green",
        "words": [
          "WINDOW",
          "MIRROR",
          "BOTTLE",
          "LENS"
        ]
      },
      {
        "label": "Types of Bread",
        "color": "blue",
        "words": [
          "SOURDOUGH",
          "FOCACCIA",
          "BRIOCHE",
          "ROTI"
        ]
      },
      {
        "label": "Can Follow \"FIRE\"",
        "color": "purple",
        "words": [
          "PLACE",
          "WORK",
          "SIDE",
          "FLY"
        ]
      }
    ]
  },
  {
    "id": 32,
    "groups": [
      {
        "label": "Things in a Garden",
        "color": "yellow",
        "words": [
          "HOSE",
          "TROWEL",
          "COMPOST",
          "FENCE"
        ]
      },
      {
        "label": "Nocturnal Animals",
        "color": "green",
        "words": [
          "OWL",
          "BAT",
          "RACCOON",
          "MOTH"
        ]
      },
      {
        "label": "Things With Buttons",
        "color": "blue",
        "words": [
          "SHIRT",
          "REMOTE",
          "ELEVATOR",
          "CONTROLLER"
        ]
      },
      {
        "label": "Words After \"OVER\"",
        "color": "purple",
        "words": [
          "TIME",
          "LOOK",
          "NIGHT",
          "FLOW"
        ]
      }
    ]
  },
  {
    "id": 33,
    "groups": [
      {
        "label": "Things You Blow",
        "color": "yellow",
        "words": [
          "WHISTLE",
          "BUBBLE",
          "CANDLE",
          "HORN"
        ]
      },
      {
        "label": "Parts of an Eye",
        "color": "green",
        "words": [
          "PUPIL",
          "IRIS",
          "RETINA",
          "CORNEA"
        ]
      },
      {
        "label": "Types of Laugh",
        "color": "blue",
        "words": [
          "CHUCKLE",
          "GIGGLE",
          "CACKLE",
          "SNICKER"
        ]
      },
      {
        "label": "Can Follow \"SILVER\"",
        "color": "purple",
        "words": [
          "WARE",
          "SCREEN",
          "SIDE",
          "SMITH"
        ]
      }
    ]
  },
  {
    "id": 34,
    "groups": [
      {
        "label": "Things That Chirp",
        "color": "yellow",
        "words": [
          "CRICKET",
          "BIRD",
          "FROG",
          "CICADA"
        ]
      },
      {
        "label": "Types of Cheese",
        "color": "green",
        "words": [
          "BRIE",
          "GOUDA",
          "CHEDDAR",
          "FETA"
        ]
      },
      {
        "label": "Things in a Classroom",
        "color": "blue",
        "words": [
          "CHALK",
          "TEXTBOOK",
          "DESK",
          "ATTENDANCE"
        ]
      },
      {
        "label": "Can Precede \"CAKE\"",
        "color": "purple",
        "words": [
          "CUP",
          "CHEESE",
          "PAN",
          "FISH"
        ]
      }
    ]
  },
  {
    "id": 35,
    "groups": [
      {
        "label": "Types of Fabric",
        "color": "yellow",
        "words": [
          "SILK",
          "LINEN",
          "VELVET",
          "DENIM"
        ]
      },
      {
        "label": "Things That Are Cold",
        "color": "green",
        "words": [
          "ICE",
          "BLIZZARD",
          "REFRIGERATOR",
          "LIQUID NITROGEN"
        ]
      },
      {
        "label": "Parts of a Flower",
        "color": "blue",
        "words": [
          "PETAL",
          "STAMEN",
          "PISTIL",
          "SEPAL"
        ]
      },
      {
        "label": "Words Before \"PRINT\"",
        "color": "purple",
        "words": [
          "FOOT",
          "FINGER",
          "BLUE",
          "THUMB"
        ]
      }
    ]
  },
  {
    "id": 36,
    "groups": [
      {
        "label": "Things You Knit",
        "color": "yellow",
        "words": [
          "SCARF",
          "SWEATER",
          "GLOVES",
          "BEANIE"
        ]
      },
      {
        "label": "Types of Exercise",
        "color": "green",
        "words": [
          "SQUAT",
          "LUNGE",
          "PLANK",
          "BURPEE"
        ]
      },
      {
        "label": "Things That Are Sharp",
        "color": "blue",
        "words": [
          "THORN",
          "NEEDLE",
          "BLADE",
          "CHEDDAR"
        ]
      },
      {
        "label": "Can Follow \"EYE\"",
        "color": "purple",
        "words": [
          "BROW",
          "LID",
          "LASH",
          "SIGHT"
        ]
      }
    ]
  },
  {
    "id": 37,
    "groups": [
      {
        "label": "Things at a Wedding",
        "color": "yellow",
        "words": [
          "VEIL",
          "BOUQUET",
          "RING",
          "TUXEDO"
        ]
      },
      {
        "label": "Types of Chocolate",
        "color": "green",
        "words": [
          "DARK",
          "MILK",
          "WHITE",
          "RAW"
        ]
      },
      {
        "label": "Parts of a Computer",
        "color": "blue",
        "words": [
          "PROCESSOR",
          "RAM",
          "HARD DRIVE",
          "GRAPHICS CARD"
        ]
      },
      {
        "label": "Can Follow \"UP\"",
        "color": "purple",
        "words": [
          "LOAD",
          "GRADE",
          "BEAT",
          "TOWN"
        ]
      }
    ]
  },
  {
    "id": 38,
    "groups": [
      {
        "label": "Things That Sink",
        "color": "yellow",
        "words": [
          "ANCHOR",
          "STONE",
          "IRON",
          "SUBMARINE"
        ]
      },
      {
        "label": "Types of Nut",
        "color": "green",
        "words": [
          "CASHEW",
          "PECAN",
          "PISTACHIO",
          "HAZELNUT"
        ]
      },
      {
        "label": "Things With Wings",
        "color": "blue",
        "words": [
          "ANGEL",
          "STAGE",
          "BUTTERFLY",
          "PLANE"
        ]
      },
      {
        "label": "Words After \"SUN\"",
        "color": "purple",
        "words": [
          "BURN",
          "SCREEN",
          "GLASS",
          "FLOWER"
        ]
      }
    ]
  },
  {
    "id": 39,
    "groups": [
      {
        "label": "Things on a Farm",
        "color": "yellow",
        "words": [
          "BARN",
          "TRACTOR",
          "SCARECROW",
          "SILO"
        ]
      },
      {
        "label": "Types of Hat",
        "color": "green",
        "words": [
          "FEDORA",
          "BERET",
          "STETSON",
          "CLOCHE"
        ]
      },
      {
        "label": "Things That Expand",
        "color": "blue",
        "words": [
          "BALLOON",
          "SPONGE",
          "LUNG",
          "DOUGH"
        ]
      },
      {
        "label": "Words Before \"FALL\"",
        "color": "purple",
        "words": [
          "WATER",
          "DOWN",
          "FREE",
          "RAIN"
        ]
      }
    ]
  },
  {
    "id": 40,
    "groups": [
      {
        "label": "Things in the Bathroom",
        "color": "yellow",
        "words": [
          "FAUCET",
          "LOOFAH",
          "TOWEL RACK",
          "MIRROR"
        ]
      },
      {
        "label": "Types of Coffee",
        "color": "green",
        "words": [
          "ESPRESSO",
          "AMERICANO",
          "FLAT WHITE",
          "COLD BREW"
        ]
      },
      {
        "label": "Things That Are Transparent",
        "color": "blue",
        "words": [
          "GLASS",
          "WATER",
          "AIR",
          "CELLOPHANE"
        ]
      },
      {
        "label": "Can Follow \"MASTER\"",
        "color": "purple",
        "words": [
          "MIND",
          "PIECE",
          "CLASS",
          "PLAN"
        ]
      }
    ]
  },
  {
    "id": 41,
    "groups": [
      {
        "label": "Shades of Blue",
        "color": "yellow",
        "words": [
          "NAVY",
          "COBALT",
          "TEAL",
          "AZURE"
        ]
      },
      {
        "label": "Things That Can Be \"BLIND\"",
        "color": "green",
        "words": [
          "SPOT",
          "FOLD",
          "DATE",
          "SIDE"
        ]
      },
      {
        "label": "Mythical Creatures",
        "color": "blue",
        "words": [
          "GRIFFIN",
          "CENTAUR",
          "SPHINX",
          "MINOTAUR"
        ]
      },
      {
        "label": "Words After \"NIGHT\"",
        "color": "purple",
        "words": [
          "CAP",
          "FALL",
          "MARE",
          "CLUB"
        ]
      }
    ]
  },
  {
    "id": 42,
    "groups": [
      {
        "label": "Things on a Sailboat",
        "color": "yellow",
        "words": [
          "BOOM",
          "JIB",
          "CLEAT",
          "RUDDER"
        ]
      },
      {
        "label": "Types of Market",
        "color": "green",
        "words": [
          "STOCK",
          "FLEA",
          "BULL",
          "BEAR"
        ]
      },
      {
        "label": "Things That Float",
        "color": "blue",
        "words": [
          "CORK",
          "LEAF",
          "ICEBERG",
          "JELLYFISH"
        ]
      },
      {
        "label": "Can Precede \"FALL\"",
        "color": "purple",
        "words": [
          "SHORT",
          "WATER",
          "PIT",
          "OUT"
        ]
      }
    ]
  },
  {
    "id": 43,
    "groups": [
      {
        "label": "Things With Pedals",
        "color": "yellow",
        "words": [
          "BICYCLE",
          "PIANO",
          "CAR",
          "SEWING MACHINE"
        ]
      },
      {
        "label": "Types of Boat",
        "color": "green",
        "words": [
          "KAYAK",
          "CANOE",
          "DINGHY",
          "CATAMARAN"
        ]
      },
      {
        "label": "Things That Are Bitter",
        "color": "blue",
        "words": [
          "COFFEE",
          "LEMON PEEL",
          "BEER HOPS",
          "DARK CHOCOLATE"
        ]
      },
      {
        "label": "Words Before \"HOUSE\"",
        "color": "purple",
        "words": [
          "WARE",
          "GREEN",
          "TREE",
          "FULL"
        ]
      }
    ]
  },
  {
    "id": 44,
    "groups": [
      {
        "label": "Things You Plug In",
        "color": "yellow",
        "words": [
          "LAMP",
          "IRON",
          "TOASTER",
          "FAN"
        ]
      },
      {
        "label": "Parts of a Tooth",
        "color": "green",
        "words": [
          "ENAMEL",
          "CROWN",
          "ROOT",
          "PULP"
        ]
      },
      {
        "label": "Things That Are Woven",
        "color": "blue",
        "words": [
          "BASKET",
          "RUG",
          "HAMMOCK",
          "TAPESTRY"
        ]
      },
      {
        "label": "Can Follow \"DIAMOND\"",
        "color": "purple",
        "words": [
          "BACK",
          "RING",
          "MINE",
          "HARD"
        ]
      }
    ]
  },
  {
    "id": 45,
    "groups": [
      {
        "label": "Things That Are Hollow",
        "color": "yellow",
        "words": [
          "TUBE",
          "DRUM",
          "CAVE",
          "VASE"
        ]
      },
      {
        "label": "Types of Pie",
        "color": "green",
        "words": [
          "SHEPHERD'S",
          "APPLE",
          "PUMPKIN",
          "POT"
        ]
      },
      {
        "label": "Things That Lock",
        "color": "blue",
        "words": [
          "DOOR",
          "SAFE",
          "PHONE",
          "CANAL"
        ]
      },
      {
        "label": "Words After \"OVER\"",
        "color": "purple",
        "words": [
          "COAT",
          "HAUL",
          "SEAS",
          "RATE"
        ]
      }
    ]
  },
  {
    "id": 46,
    "groups": [
      {
        "label": "Parts of a Plant",
        "color": "yellow",
        "words": [
          "STEM",
          "ROOT",
          "LEAF",
          "BLOSSOM"
        ]
      },
      {
        "label": "Things You Swipe",
        "color": "green",
        "words": [
          "CARD",
          "SCREEN",
          "MATCH",
          "COUPON"
        ]
      },
      {
        "label": "Words That Mean Tired",
        "color": "blue",
        "words": [
          "WEARY",
          "DRAINED",
          "DROWSY",
          "FATIGUED"
        ]
      },
      {
        "label": "Can Follow \"CROSS\"",
        "color": "purple",
        "words": [
          "WORD",
          "ROAD",
          "BOW",
          "FIT"
        ]
      }
    ]
  },
  {
    "id": 47,
    "groups": [
      {
        "label": "Things at an Airport",
        "color": "yellow",
        "words": [
          "TERMINAL",
          "RUNWAY",
          "GATE",
          "BAGGAGE CLAIM"
        ]
      },
      {
        "label": "Types of Energy",
        "color": "green",
        "words": [
          "SOLAR",
          "KINETIC",
          "NUCLEAR",
          "THERMAL"
        ]
      },
      {
        "label": "Things That Are Rough",
        "color": "blue",
        "words": [
          "SANDPAPER",
          "GRAVEL",
          "BARK",
          "STUBBLE"
        ]
      },
      {
        "label": "Words Before \"BREAK\"",
        "color": "purple",
        "words": [
          "DAY",
          "JAIL",
          "GROUND",
          "WIND"
        ]
      }
    ]
  },
  {
    "id": 48,
    "groups": [
      {
        "label": "Things That Rust",
        "color": "yellow",
        "words": [
          "IRON",
          "NAIL",
          "CHAIN",
          "RAZOR"
        ]
      },
      {
        "label": "Types of Collar",
        "color": "green",
        "words": [
          "DOG",
          "BLUE",
          "WHITE",
          "SAILOR"
        ]
      },
      {
        "label": "Things With a Dial",
        "color": "blue",
        "words": [
          "RADIO",
          "SAFE",
          "THERMOMETER",
          "STOVE"
        ]
      },
      {
        "label": "Can Follow \"COUNTER\"",
        "color": "purple",
        "words": [
          "PART",
          "FIT",
          "ACT",
          "POINT"
        ]
      }
    ]
  },
  {
    "id": 49,
    "groups": [
      {
        "label": "Things You Crack",
        "color": "yellow",
        "words": [
          "EGG",
          "KNUCKLE",
          "CODE",
          "SAFE"
        ]
      },
      {
        "label": "Types of Race",
        "color": "green",
        "words": [
          "SPRINT",
          "RELAY",
          "HURDLE",
          "MARATHON"
        ]
      },
      {
        "label": "Things That Orbit",
        "color": "blue",
        "words": [
          "MOON",
          "SATELLITE",
          "ELECTRON",
          "SPACE STATION"
        ]
      },
      {
        "label": "Words Before \"BALL\"",
        "color": "purple",
        "words": [
          "FIRE",
          "CURVE",
          "HARD",
          "ODD"
        ]
      }
    ]
  },
  {
    "id": 50,
    "groups": [
      {
        "label": "Things You Squeeze",
        "color": "yellow",
        "words": [
          "LEMON",
          "TOOTHPASTE",
          "HAND",
          "TRIGGER"
        ]
      },
      {
        "label": "Types of Feather",
        "color": "green",
        "words": [
          "DOWN",
          "QUILL",
          "CONTOUR",
          "FLIGHT"
        ]
      },
      {
        "label": "Things That Are Elastic",
        "color": "blue",
        "words": [
          "RUBBER BAND",
          "WAISTBAND",
          "TRAMPOLINE",
          "SKIN"
        ]
      },
      {
        "label": "Can Precede \"BOARD\"",
        "color": "purple",
        "words": [
          "CARD",
          "SURF",
          "SNOW",
          "CUP"
        ]
      }
    ]
  },
  {
    "id": 51,
    "groups": [
      {
        "label": "Shades of Green",
        "color": "yellow",
        "words": [
          "LIME",
          "OLIVE",
          "EMERALD",
          "SAGE"
        ]
      },
      {
        "label": "Things You Can't See",
        "color": "green",
        "words": [
          "WIFI",
          "GRAVITY",
          "WIND",
          "BACTERIA"
        ]
      },
      {
        "label": "Types of Window",
        "color": "blue",
        "words": [
          "BAY",
          "FRENCH",
          "PORTHOLE",
          "SASH"
        ]
      },
      {
        "label": "Can Follow \"PEPPER\"",
        "color": "purple",
        "words": [
          "MINT",
          "CORN",
          "JACK",
          "ONI"
        ]
      }
    ]
  },
  {
    "id": 52,
    "groups": [
      {
        "label": "Things That Drip",
        "color": "yellow",
        "words": [
          "FAUCET",
          "CANDLE",
          "PAINT",
          "ICICLE"
        ]
      },
      {
        "label": "Parts of a Sentence",
        "color": "green",
        "words": [
          "SUBJECT",
          "PREDICATE",
          "CLAUSE",
          "PHRASE"
        ]
      },
      {
        "label": "Things That Are Magnetic",
        "color": "blue",
        "words": [
          "COMPASS",
          "FRIDGE",
          "SPEAKER",
          "SCRAPYARD"
        ]
      },
      {
        "label": "Words After \"KEY\"",
        "color": "purple",
        "words": [
          "BOARD",
          "STONE",
          "HOLE",
          "NOTE"
        ]
      }
    ]
  },
  {
    "id": 53,
    "groups": [
      {
        "label": "Things on a Chess Board",
        "color": "yellow",
        "words": [
          "BISHOP",
          "CASTLE",
          "KNIGHT",
          "PAWN"
        ]
      },
      {
        "label": "Types of Cloud",
        "color": "green",
        "words": [
          "CUMULUS",
          "STRATUS",
          "CIRRUS",
          "NIMBUS"
        ]
      },
      {
        "label": "Things That Have Keys",
        "color": "blue",
        "words": [
          "PIANO",
          "LOCK",
          "MAP",
          "COMPUTER"
        ]
      },
      {
        "label": "Can Follow \"THUNDER\"",
        "color": "purple",
        "words": [
          "BOLT",
          "STORM",
          "CLAP",
          "BIRD"
        ]
      }
    ]
  },
  {
    "id": 54,
    "groups": [
      {
        "label": "Things That Are Prickly",
        "color": "yellow",
        "words": [
          "CACTUS",
          "HEDGEHOG",
          "PINE CONE",
          "THISTLE"
        ]
      },
      {
        "label": "Types of Wave",
        "color": "green",
        "words": [
          "RADIO",
          "SOUND",
          "TIDAL",
          "MICRO"
        ]
      },
      {
        "label": "Things You Wear in Winter",
        "color": "blue",
        "words": [
          "SCARF",
          "EARMUFFS",
          "THERMAL",
          "SNOW BOOTS"
        ]
      },
      {
        "label": "Words Before \"POOL\"",
        "color": "purple",
        "words": [
          "CAR",
          "DEAD",
          "SWIM",
          "WHIRL"
        ]
      }
    ]
  },
  {
    "id": 55,
    "groups": [
      {
        "label": "Things That Have Layers",
        "color": "yellow",
        "words": [
          "ONION",
          "CAKE",
          "EARTH",
          "LASAGNA"
        ]
      },
      {
        "label": "Types of Jump",
        "color": "green",
        "words": [
          "HURDLE",
          "VAULT",
          "LEAP",
          "BOUND"
        ]
      },
      {
        "label": "Things That Are Slippery",
        "color": "blue",
        "words": [
          "ICE",
          "OIL",
          "BANANA PEEL",
          "WET FLOOR"
        ]
      },
      {
        "label": "Can Follow \"HEAD\"",
        "color": "purple",
        "words": [
          "BAND",
          "ACHE",
          "LIGHT",
          "QUARTER"
        ]
      }
    ]
  },
  {
    "id": 56,
    "groups": [
      {
        "label": "Things in a Purse",
        "color": "yellow",
        "words": [
          "LIPSTICK",
          "MIRROR",
          "RECEIPT",
          "EARPHONE"
        ]
      },
      {
        "label": "Types of Stitch",
        "color": "green",
        "words": [
          "CROSS",
          "CHAIN",
          "BACK",
          "RUNNING"
        ]
      },
      {
        "label": "Things That Can \"BREAK DOWN\"",
        "color": "blue",
        "words": [
          "CAR",
          "NEGOTIATION",
          "WALL",
          "BARRIER"
        ]
      },
      {
        "label": "Words After \"DOWN\"",
        "color": "purple",
        "words": [
          "TOWN",
          "STAIRS",
          "FALL",
          "LOAD"
        ]
      }
    ]
  },
  {
    "id": 57,
    "groups": [
      {
        "label": "Things You Rent",
        "color": "yellow",
        "words": [
          "APARTMENT",
          "CAR",
          "TUXEDO",
          "MOVIE"
        ]
      },
      {
        "label": "Parts of a Volcano",
        "color": "green",
        "words": [
          "CRATER",
          "MAGMA",
          "LAVA",
          "VENT"
        ]
      },
      {
        "label": "Things That Are Precious",
        "color": "blue",
        "words": [
          "TIME",
          "GEM",
          "MEMORY",
          "METAL"
        ]
      },
      {
        "label": "Can Precede \"STONE\"",
        "color": "purple",
        "words": [
          "LIME",
          "KEY",
          "SAND",
          "CORNER"
        ]
      }
    ]
  },
  {
    "id": 58,
    "groups": [
      {
        "label": "Things That Are Sweet and Salty",
        "color": "yellow",
        "words": [
          "CARAMEL POPCORN",
          "SALTED CARAMEL",
          "PRETZEL",
          "TRAIL MIX"
        ]
      },
      {
        "label": "Types of Signal",
        "color": "green",
        "words": [
          "SMOKE",
          "HAND",
          "DISTRESS",
          "TRAFFIC"
        ]
      },
      {
        "label": "Things You Tap",
        "color": "blue",
        "words": [
          "SHOULDER",
          "PHONE",
          "KEG",
          "MAPLE TREE"
        ]
      },
      {
        "label": "Words Before \"PACK\"",
        "color": "purple",
        "words": [
          "JET",
          "SIX",
          "BACK",
          "ICE"
        ]
      }
    ]
  },
  {
    "id": 59,
    "groups": [
      {
        "label": "Things That Buzz",
        "color": "yellow",
        "words": [
          "BEE",
          "DOORBELL",
          "CHAINSAW",
          "ELECTRIC RAZOR"
        ]
      },
      {
        "label": "Types of Knot",
        "color": "green",
        "words": [
          "REEF",
          "SLIP",
          "BOW",
          "CLOVE"
        ]
      },
      {
        "label": "Things That Are Recycled",
        "color": "blue",
        "words": [
          "BOTTLE",
          "NEWSPAPER",
          "CARDBOARD",
          "ALUMINIUM CAN"
        ]
      },
      {
        "label": "Can Follow \"STRING\"",
        "color": "purple",
        "words": [
          "BEAN",
          "RAY",
          "ENT",
          "THEORY"
        ]
      }
    ]
  },
  {
    "id": 60,
    "groups": [
      {
        "label": "Things That Are Cooked Slowly",
        "color": "yellow",
        "words": [
          "STEW",
          "BRISKET",
          "TAGINE",
          "CASSEROLE"
        ]
      },
      {
        "label": "Parts of a Bridge",
        "color": "green",
        "words": [
          "ARCH",
          "GIRDER",
          "CABLE",
          "ABUTMENT"
        ]
      },
      {
        "label": "Things That Are Sticky and Sweet",
        "color": "blue",
        "words": [
          "HONEY",
          "SYRUP",
          "JAM",
          "TOFFEE"
        ]
      },
      {
        "label": "Words After \"LONG\"",
        "color": "purple",
        "words": [
          "SHOT",
          "BOW",
          "HAND",
          "SIDE"
        ]
      }
    ]
  },
  {
    "id": 61,
    "groups": [
      {
        "label": "Words That Sound Like Letters",
        "color": "yellow",
        "words": [
          "ARE",
          "SEA",
          "WHY",
          "JAY"
        ]
      },
      {
        "label": "Things That Have a Shell",
        "color": "green",
        "words": [
          "SNAIL",
          "EGG",
          "TORTOISE",
          "WALNUT"
        ]
      },
      {
        "label": "Types of Beat",
        "color": "blue",
        "words": [
          "DRUM",
          "HEART",
          "DEADBEAT",
          "UPBEAT"
        ]
      },
      {
        "label": "Can Follow \"DOUBLE\"",
        "color": "purple",
        "words": [
          "DUTCH",
          "AGENT",
          "TAKE",
          "DECKER"
        ]
      }
    ]
  },
  {
    "id": 62,
    "groups": [
      {
        "label": "Things That Come in Pairs",
        "color": "yellow",
        "words": [
          "GLOVES",
          "SOCKS",
          "CHOPSTICKS",
          "EARRINGS"
        ]
      },
      {
        "label": "Types of Sauce",
        "color": "green",
        "words": [
          "BECHAMEL",
          "HOLLANDAISE",
          "VELOUTE",
          "ESPAGNOLE"
        ]
      },
      {
        "label": "Things That Are Also Verbs",
        "color": "blue",
        "words": [
          "COOK",
          "IRON",
          "BRUSH",
          "LOCK"
        ]
      },
      {
        "label": "Words After \"BREAK\"",
        "color": "purple",
        "words": [
          "FAST",
          "DANCE",
          "AWAY",
          "THROUGH"
        ]
      }
    ]
  },
  {
    "id": 63,
    "groups": [
      {
        "label": "Things Found in a Desert",
        "color": "yellow",
        "words": [
          "DUNE",
          "OASIS",
          "CAMEL",
          "SCORPION"
        ]
      },
      {
        "label": "Parts of a Song",
        "color": "green",
        "words": [
          "VERSE",
          "CHORUS",
          "BRIDGE",
          "OUTRO"
        ]
      },
      {
        "label": "Things That Melt in the Sun",
        "color": "blue",
        "words": [
          "ICE CREAM",
          "CHOCOLATE",
          "BUTTER",
          "SNOWMAN"
        ]
      },
      {
        "label": "Can Precede \"WORK\"",
        "color": "purple",
        "words": [
          "FRAME",
          "NET",
          "GROUND",
          "OVER"
        ]
      }
    ]
  },
  {
    "id": 64,
    "groups": [
      {
        "label": "Things With Spots",
        "color": "yellow",
        "words": [
          "DALMATIAN",
          "LEOPARD",
          "LADYBUG",
          "DICE"
        ]
      },
      {
        "label": "Types of Cheese Texture",
        "color": "green",
        "words": [
          "CRUMBLY",
          "CREAMY",
          "FIRM",
          "SPREADABLE"
        ]
      },
      {
        "label": "Things That Are Also Adjectives",
        "color": "blue",
        "words": [
          "COOL",
          "SHARP",
          "FRESH",
          "LIGHT"
        ]
      },
      {
        "label": "Words Before \"POINT\"",
        "color": "purple",
        "words": [
          "GUN",
          "BALL",
          "VIEW",
          "SWORD"
        ]
      }
    ]
  },
  {
    "id": 65,
    "groups": [
      {
        "label": "Things That Whistle",
        "color": "yellow",
        "words": [
          "KETTLE",
          "WIND",
          "REFEREE",
          "TRAIN"
        ]
      },
      {
        "label": "Types of Fog",
        "color": "green",
        "words": [
          "ADVECTION",
          "RADIATION",
          "SEA",
          "VALLEY"
        ]
      },
      {
        "label": "Things That Are Contagious",
        "color": "blue",
        "words": [
          "YAWN",
          "LAUGHTER",
          "FLU",
          "ENTHUSIASM"
        ]
      },
      {
        "label": "Can Follow \"LAND\"",
        "color": "purple",
        "words": [
          "MARK",
          "SLIDE",
          "FILL",
          "LORD"
        ]
      }
    ]
  },
  {
    "id": 66,
    "groups": [
      {
        "label": "Things You Do With Your Eyes",
        "color": "yellow",
        "words": [
          "WINK",
          "BLINK",
          "SQUINT",
          "GLARE"
        ]
      },
      {
        "label": "Types of Lock",
        "color": "green",
        "words": [
          "COMBINATION",
          "PADLOCK",
          "DEADBOLT",
          "MORTISE"
        ]
      },
      {
        "label": "Things That Have Pockets",
        "color": "blue",
        "words": [
          "JACKET",
          "KANGAROO",
          "BILLIARDS TABLE",
          "PITA BREAD"
        ]
      },
      {
        "label": "Words After \"QUICK\"",
        "color": "purple",
        "words": [
          "SAND",
          "SILVER",
          "STEP",
          "FIRE"
        ]
      }
    ]
  },
  {
    "id": 67,
    "groups": [
      {
        "label": "Things That Are Coiled",
        "color": "yellow",
        "words": [
          "SPRING",
          "HOSE",
          "SNAKE",
          "WIRE"
        ]
      },
      {
        "label": "Types of Hug",
        "color": "green",
        "words": [
          "BEAR",
          "SIDE",
          "BACK",
          "SQUEEZE"
        ]
      },
      {
        "label": "Things That Require Patience",
        "color": "blue",
        "words": [
          "FISHING",
          "PUZZLE",
          "MEDITATION",
          "BREAD BAKING"
        ]
      },
      {
        "label": "Can Precede \"LIGHT\"",
        "color": "purple",
        "words": [
          "MOON",
          "SUN",
          "SPOT",
          "STAR"
        ]
      }
    ]
  },
  {
    "id": 68,
    "groups": [
      {
        "label": "Things That Are Braided",
        "color": "yellow",
        "words": [
          "HAIR",
          "ROPE",
          "BREAD",
          "RIVER"
        ]
      },
      {
        "label": "Types of Memory",
        "color": "green",
        "words": [
          "SHORT-TERM",
          "LONG-TERM",
          "MUSCLE",
          "PHOTOGRAPHIC"
        ]
      },
      {
        "label": "Things That Can Be \"BROKEN\"",
        "color": "blue",
        "words": [
          "SILENCE",
          "SPELL",
          "PROMISE",
          "HABIT"
        ]
      },
      {
        "label": "Words After \"COLD\"",
        "color": "purple",
        "words": [
          "FRONT",
          "SNAP",
          "SHOULDER",
          "BLOODED"
        ]
      }
    ]
  },
  {
    "id": 69,
    "groups": [
      {
        "label": "Things That Have a Trunk",
        "color": "yellow",
        "words": [
          "ELEPHANT",
          "CAR",
          "TREE",
          "SUITCASE"
        ]
      },
      {
        "label": "Types of Poll",
        "color": "green",
        "words": [
          "EXIT",
          "GALLUP",
          "STRAW",
          "OPINION"
        ]
      },
      {
        "label": "Things That Are Also Nouns and Verbs",
        "color": "blue",
        "words": [
          "BANK",
          "BOOK",
          "ROCK",
          "DRIVE"
        ]
      },
      {
        "label": "Can Follow \"OVER\"",
        "color": "purple",
        "words": [
          "BOARD",
          "CAST",
          "LAP",
          "TAKE"
        ]
      }
    ]
  },
  {
    "id": 70,
    "groups": [
      {
        "label": "Things Measured in Carats",
        "color": "yellow",
        "words": [
          "GOLD",
          "DIAMOND",
          "RUBY",
          "SAPPHIRE"
        ]
      },
      {
        "label": "Types of Humor",
        "color": "green",
        "words": [
          "DRY",
          "DARK",
          "DEADPAN",
          "SLAPSTICK"
        ]
      },
      {
        "label": "Things That Are Also \"PLANT\"",
        "color": "blue",
        "words": [
          "FACTORY",
          "SEED",
          "SPY",
          "POTTED"
        ]
      },
      {
        "label": "Words Before \"WORK\"",
        "color": "purple",
        "words": [
          "HOME",
          "TEAM",
          "GUESS",
          "PATCH"
        ]
      }
    ]
  },
  {
    "id": 71,
    "groups": [
      {
        "label": "Things With Claws",
        "color": "yellow",
        "words": [
          "CRAB",
          "HAWK",
          "BEAR",
          "LOBSTER"
        ]
      },
      {
        "label": "Types of Tax",
        "color": "green",
        "words": [
          "INCOME",
          "SALES",
          "CAPITAL GAINS",
          "PROPERTY"
        ]
      },
      {
        "label": "Things That Are Also Measures",
        "color": "blue",
        "words": [
          "FOOT",
          "POUND",
          "YARD",
          "STONE"
        ]
      },
      {
        "label": "Can Follow \"BLUE\"",
        "color": "purple",
        "words": [
          "PRINT",
          "BELL",
          "BIRD",
          "TOOTH"
        ]
      }
    ]
  },
  {
    "id": 72,
    "groups": [
      {
        "label": "Things That Spin Fast",
        "color": "yellow",
        "words": [
          "TURBINE",
          "TOP",
          "DRYER",
          "CENTRIFUGE"
        ]
      },
      {
        "label": "Types of Market Stall",
        "color": "green",
        "words": [
          "FLOWER",
          "CHEESE",
          "CRAFT",
          "PRODUCE"
        ]
      },
      {
        "label": "Things That Can Be \"Charged\"",
        "color": "blue",
        "words": [
          "BATTERY",
          "CRIME",
          "BULL",
          "ACCOUNT"
        ]
      },
      {
        "label": "Words After \"STOCK\"",
        "color": "purple",
        "words": [
          "PILE",
          "ROOM",
          "HOLM",
          "BROKER"
        ]
      }
    ]
  },
  {
    "id": 73,
    "groups": [
      {
        "label": "Things That Can Be Pitched",
        "color": "yellow",
        "words": [
          "TENT",
          "IDEA",
          "BALL",
          "VOICE"
        ]
      },
      {
        "label": "Types of Drain",
        "color": "green",
        "words": [
          "STORM",
          "BRAIN",
          "FRENCH",
          "MAIN"
        ]
      },
      {
        "label": "Things in a Magician's Act",
        "color": "blue",
        "words": [
          "WAND",
          "RABBIT",
          "CARD",
          "SMOKE"
        ]
      },
      {
        "label": "Can Follow \"SAND\"",
        "color": "purple",
        "words": [
          "STONE",
          "BAG",
          "STORM",
          "CASTLE"
        ]
      }
    ]
  },
  {
    "id": 74,
    "groups": [
      {
        "label": "Things That Have a Needle",
        "color": "yellow",
        "words": [
          "SYRINGE",
          "COMPASS",
          "PINE TREE",
          "RECORD PLAYER"
        ]
      },
      {
        "label": "Types of Panic",
        "color": "green",
        "words": [
          "MORAL",
          "BUYING",
          "ATTACK",
          "SELLING"
        ]
      },
      {
        "label": "Things That Are Anchored",
        "color": "blue",
        "words": [
          "SHIP",
          "TENT",
          "NEWS PRESENTER",
          "SOUL"
        ]
      },
      {
        "label": "Words Before \"FALL\"",
        "color": "purple",
        "words": [
          "FOOT",
          "BANANA",
          "STUMBLE",
          "TRIP"
        ]
      }
    ]
  },
  {
    "id": 75,
    "groups": [
      {
        "label": "Things That Are Wound Up",
        "color": "yellow",
        "words": [
          "CLOCK",
          "SPRING",
          "TENSION",
          "BALL OF YARN"
        ]
      },
      {
        "label": "Types of Cap",
        "color": "green",
        "words": [
          "HUB",
          "KNEE",
          "ICE",
          "SKULL"
        ]
      },
      {
        "label": "Things That Have Cores",
        "color": "blue",
        "words": [
          "APPLE",
          "EARTH",
          "REACTOR",
          "WORKOUT"
        ]
      },
      {
        "label": "Can Follow \"IRON\"",
        "color": "purple",
        "words": [
          "WORKS",
          "CLAD",
          "STONE",
          "MONGER"
        ]
      }
    ]
  },
  {
    "id": 76,
    "groups": [
      {
        "label": "Things That Are Cut Short",
        "color": "yellow",
        "words": [
          "HAIRCUT",
          "SPEECH",
          "HOLIDAY",
          "LIFE"
        ]
      },
      {
        "label": "Types of Burn",
        "color": "green",
        "words": [
          "SUNBURN",
          "HEARTBURN",
          "CHEMICAL BURN",
          "CARPET BURN"
        ]
      },
      {
        "label": "Things That Are Pressing",
        "color": "blue",
        "words": [
          "IRON",
          "TROUSER CREASE",
          "URGENT MATTER",
          "FLOWER"
        ]
      },
      {
        "label": "Words After \"HAIR\"",
        "color": "purple",
        "words": [
          "PIN",
          "NET",
          "PIECE",
          "RAISING"
        ]
      }
    ]
  },
  {
    "id": 77,
    "groups": [
      {
        "label": "Things That Start Races",
        "color": "yellow",
        "words": [
          "GUN",
          "FLAG",
          "WHISTLE",
          "LIGHT"
        ]
      },
      {
        "label": "Types of Grip",
        "color": "green",
        "words": [
          "HAND",
          "OVER",
          "THUMB",
          "FINGER"
        ]
      },
      {
        "label": "Things That Can Be Viral",
        "color": "blue",
        "words": [
          "VIDEO",
          "DISEASE",
          "MEME",
          "CAMPAIGN"
        ]
      },
      {
        "label": "Can Precede \"RING\"",
        "color": "purple",
        "words": [
          "BOX",
          "EAR",
          "SPRING",
          "BOXING"
        ]
      }
    ]
  },
  {
    "id": 78,
    "groups": [
      {
        "label": "Things That Make You Cry",
        "color": "yellow",
        "words": [
          "ONION",
          "FILM",
          "PEPPER SPRAY",
          "JOY"
        ]
      },
      {
        "label": "Types of Proof",
        "color": "green",
        "words": [
          "BULLET",
          "FIRE",
          "WATER",
          "FOOL"
        ]
      },
      {
        "label": "Things That Can Be \"Tender\"",
        "color": "blue",
        "words": [
          "STEAK",
          "CHICKEN",
          "LEGAL",
          "HEART"
        ]
      },
      {
        "label": "Words Before \"JACK\"",
        "color": "purple",
        "words": [
          "BLACK",
          "CRACKER",
          "HI",
          "LUMBER"
        ]
      }
    ]
  },
  {
    "id": 79,
    "groups": [
      {
        "label": "Things You Can Crack",
        "color": "yellow",
        "words": [
          "JOKE",
          "WALL",
          "PROBLEM",
          "NUT"
        ]
      },
      {
        "label": "Types of Current",
        "color": "green",
        "words": [
          "ALTERNATING",
          "DIRECT",
          "RIP",
          "GULF STREAM"
        ]
      },
      {
        "label": "Things That Can Be \"Blind\"",
        "color": "blue",
        "words": [
          "VENETIAN",
          "TEST",
          "DATE",
          "ALLEY"
        ]
      },
      {
        "label": "Can Follow \"CROSS\"",
        "color": "purple",
        "words": [
          "ROADS",
          "FIRE",
          "WORD",
          "COUNTRY"
        ]
      }
    ]
  },
  {
    "id": 80,
    "groups": [
      {
        "label": "Things That Can \"Run\"",
        "color": "yellow",
        "words": [
          "FAUCET",
          "STOCKING",
          "NOSE",
          "CLOCK"
        ]
      },
      {
        "label": "Types of Cover",
        "color": "green",
        "words": [
          "GROUND",
          "UNDER",
          "DISC",
          "BED"
        ]
      },
      {
        "label": "Things That Are Also Colors and Emotions",
        "color": "blue",
        "words": [
          "BLUE",
          "GREEN",
          "RED",
          "YELLOW"
        ]
      },
      {
        "label": "Words After \"UNDER\"",
        "color": "purple",
        "words": [
          "WORLD",
          "DOG",
          "TONE",
          "BELLY"
        ]
      }
    ]
  },
  {
    "id": 81,
    "groups": [
      {
        "label": "Things That Have Banks",
        "color": "yellow",
        "words": [
          "RIVER",
          "COUNTRY",
          "BLOOD",
          "MEMORY"
        ]
      },
      {
        "label": "Types of Pressure",
        "color": "green",
        "words": [
          "BLOOD",
          "PEER",
          "AIR",
          "WATER"
        ]
      },
      {
        "label": "Things That Are Also \"POOL\"",
        "color": "blue",
        "words": [
          "GENE",
          "TALENT",
          "SWIMMING",
          "DEAD"
        ]
      },
      {
        "label": "Can Follow \"DARK\"",
        "color": "purple",
        "words": [
          "HORSE",
          "ROOM",
          "SIDE",
          "NET"
        ]
      }
    ]
  },
  {
    "id": 82,
    "groups": [
      {
        "label": "Things With a Spine",
        "color": "yellow",
        "words": [
          "BOOK",
          "HUMAN",
          "CACTUS",
          "HEDGEHOG"
        ]
      },
      {
        "label": "Types of Ceiling",
        "color": "green",
        "words": [
          "GLASS",
          "CLOUD",
          "DROP",
          "VAULTED"
        ]
      },
      {
        "label": "Things That Are Also \"Light\"",
        "color": "blue",
        "words": [
          "TRAFFIC",
          "MOON",
          "GREEN",
          "FLASH"
        ]
      },
      {
        "label": "Words Before \"BOARD\"",
        "color": "purple",
        "words": [
          "OVER",
          "KEY",
          "SKATE",
          "PASTE"
        ]
      }
    ]
  },
  {
    "id": 83,
    "groups": [
      {
        "label": "Things That Can Be Cooked \"Al Dente\"",
        "color": "yellow",
        "words": [
          "PASTA",
          "ASPARAGUS",
          "RICE",
          "BEANS"
        ]
      },
      {
        "label": "Types of Drift",
        "color": "green",
        "words": [
          "SNOW",
          "CONTINENTAL",
          "GENETIC",
          "OVER"
        ]
      },
      {
        "label": "Things That Are Also \"FIRE\"",
        "color": "blue",
        "words": [
          "RAPID",
          "CROSS",
          "HELL",
          "CAMP"
        ]
      },
      {
        "label": "Can Follow \"BRUSH\"",
        "color": "purple",
        "words": [
          "WOOD",
          "FIRE",
          "STROKE",
          "BACK"
        ]
      }
    ]
  },
  {
    "id": 84,
    "groups": [
      {
        "label": "Things That Have Strings Attached",
        "color": "yellow",
        "words": [
          "KITE",
          "PUPPET",
          "GRANT",
          "GUITAR"
        ]
      },
      {
        "label": "Types of Zone",
        "color": "green",
        "words": [
          "TIME",
          "COMFORT",
          "END",
          "STRIKE"
        ]
      },
      {
        "label": "Things That Can \"Set\"",
        "color": "blue",
        "words": [
          "SUN",
          "GLUE",
          "JELLY",
          "RECORD"
        ]
      },
      {
        "label": "Words After \"EAR\"",
        "color": "purple",
        "words": [
          "RING",
          "DRUM",
          "PLUG",
          "MARK"
        ]
      }
    ]
  },
  {
    "id": 85,
    "groups": [
      {
        "label": "Things That Are Stacked",
        "color": "yellow",
        "words": [
          "PANCAKES",
          "CHAIRS",
          "CHIPS",
          "DECK OF CARDS"
        ]
      },
      {
        "label": "Types of Field",
        "color": "green",
        "words": [
          "MINE",
          "BATTLE",
          "CORN",
          "MAGNETIC"
        ]
      },
      {
        "label": "Things With a \"Base\"",
        "color": "blue",
        "words": [
          "BASEBALL",
          "ARMY",
          "LAMP",
          "FOUNDATION"
        ]
      },
      {
        "label": "Can Precede \"LINE\"",
        "color": "purple",
        "words": [
          "DEAD",
          "PUNCH",
          "POWER",
          "BORDER"
        ]
      }
    ]
  },
  {
    "id": 86,
    "groups": [
      {
        "label": "Things That Can Be \"Hard\"",
        "color": "yellow",
        "words": [
          "ROCK",
          "EVIDENCE",
          "FEELINGS",
          "CHEESE"
        ]
      },
      {
        "label": "Types of Impression",
        "color": "green",
        "words": [
          "FIRST",
          "CARBON",
          "LASTING",
          "RUBBER"
        ]
      },
      {
        "label": "Things That Can \"Stick\"",
        "color": "blue",
        "words": [
          "GLUE",
          "MUD",
          "MEMORY",
          "TONGUE"
        ]
      },
      {
        "label": "Words Before \"SIDE\"",
        "color": "purple",
        "words": [
          "BLIND",
          "OUT",
          "RING",
          "FLIP"
        ]
      }
    ]
  },
  {
    "id": 87,
    "groups": [
      {
        "label": "Things That Can Be \"Broken In\"",
        "color": "yellow",
        "words": [
          "SHOES",
          "HORSE",
          "ROOM",
          "NEW EMPLOYEE"
        ]
      },
      {
        "label": "Types of Arm",
        "color": "green",
        "words": [
          "FIRE",
          "SIDE",
          "COAT OF",
          "STRONG"
        ]
      },
      {
        "label": "Things That Can \"Float\"",
        "color": "blue",
        "words": [
          "IDEA",
          "BOAT",
          "LOAN",
          "DEAD"
        ]
      },
      {
        "label": "Can Follow \"OVER\"",
        "color": "purple",
        "words": [
          "SHADOW",
          "WHELM",
          "TURN",
          "RULE"
        ]
      }
    ]
  },
  {
    "id": 88,
    "groups": [
      {
        "label": "Things That Can Be \"Picked\"",
        "color": "yellow",
        "words": [
          "LOCK",
          "FIGHT",
          "POCKET",
          "NOSE"
        ]
      },
      {
        "label": "Types of Character",
        "color": "green",
        "words": [
          "LEAD",
          "SUPPORTING",
          "STOCK",
          "CAMEO"
        ]
      },
      {
        "label": "Things That Have a \"Head\"",
        "color": "blue",
        "words": [
          "NAIL",
          "SHOWERHEAD",
          "BALD EAGLE",
          "THUNDERHEAD"
        ]
      },
      {
        "label": "Words After \"UNDER\"",
        "color": "purple",
        "words": [
          "LINE",
          "COVER",
          "PASS",
          "SCORE"
        ]
      }
    ]
  },
  {
    "id": 89,
    "groups": [
      {
        "label": "Things That Are \"Still\"",
        "color": "yellow",
        "words": [
          "LAKE",
          "WATER",
          "PHOTO",
          "NIGHT"
        ]
      },
      {
        "label": "Types of Twist",
        "color": "green",
        "words": [
          "PLOT",
          "SALT",
          "TONGUE",
          "FATE"
        ]
      },
      {
        "label": "Things That Can Be \"Driven\"",
        "color": "blue",
        "words": [
          "CAR",
          "NAIL",
          "SNOW",
          "AMBITION"
        ]
      },
      {
        "label": "Can Follow \"STAR\"",
        "color": "purple",
        "words": [
          "FISH",
          "BOARD",
          "LIGHT",
          "GAZE"
        ]
      }
    ]
  },
  {
    "id": 90,
    "groups": [
      {
        "label": "Things That Can Be \"Raised\"",
        "color": "yellow",
        "words": [
          "FLAG",
          "CHILD",
          "BARN",
          "EYEBROW"
        ]
      },
      {
        "label": "Types of Shot",
        "color": "green",
        "words": [
          "GUNSHOT",
          "LONG SHOT",
          "MOON SHOT",
          "SHOT PUT"
        ]
      },
      {
        "label": "Things With a \"Face\"",
        "color": "blue",
        "words": [
          "CLOCK",
          "CLIFF",
          "POKER",
          "INTERFACE"
        ]
      },
      {
        "label": "Words Before \"DOWN\"",
        "color": "purple",
        "words": [
          "TOUCH",
          "MELT",
          "SHOW",
          "BREAK"
        ]
      }
    ]
  },
  {
    "id": 91,
    "groups": [
      {
        "label": "Things That Can \"Lead\"",
        "color": "yellow",
        "words": [
          "METAL",
          "PENCIL",
          "CLUE",
          "PARADE"
        ]
      },
      {
        "label": "Types of Space",
        "color": "green",
        "words": [
          "OUTER",
          "PERSONAL",
          "PARKING",
          "BREATHING"
        ]
      },
      {
        "label": "Things That Can Be \"Tight\"",
        "color": "blue",
        "words": [
          "ROPE",
          "BUDGET",
          "DEADLINE",
          "SCHEDULE"
        ]
      },
      {
        "label": "Can Follow \"WATER\"",
        "color": "purple",
        "words": [
          "MARK",
          "SHED",
          "FALL",
          "COLOUR"
        ]
      }
    ]
  },
  {
    "id": 92,
    "groups": [
      {
        "label": "Things That Can \"Strike\"",
        "color": "yellow",
        "words": [
          "LIGHTNING",
          "MATCH",
          "WORKER",
          "BOWLING BALL"
        ]
      },
      {
        "label": "Types of Debt",
        "color": "green",
        "words": [
          "NATIONAL",
          "CREDIT CARD",
          "STUDENT LOAN",
          "SOVEREIGN"
        ]
      },
      {
        "label": "Things That Can Be \"Wild\"",
        "color": "blue",
        "words": [
          "CARD",
          "FIRE",
          "LIFE",
          "PARTY"
        ]
      },
      {
        "label": "Words After \"PITCH\"",
        "color": "purple",
        "words": [
          "FORK",
          "BLACK",
          "DARK",
          "PERFECT"
        ]
      }
    ]
  },
  {
    "id": 93,
    "groups": [
      {
        "label": "Things That Are \"Cut\"",
        "color": "yellow",
        "words": [
          "DIAMOND",
          "SHORT CUT",
          "PAPER CUT",
          "HAIR CUT"
        ]
      },
      {
        "label": "Types of Charge",
        "color": "green",
        "words": [
          "ELECTRIC",
          "CRIMINAL",
          "CAVALRY",
          "PHONE"
        ]
      },
      {
        "label": "Things That Can Be \"Fresh\"",
        "color": "blue",
        "words": [
          "AIR",
          "START",
          "FACE",
          "BREAD"
        ]
      },
      {
        "label": "Can Follow \"HIGH\"",
        "color": "purple",
        "words": [
          "LIGHT",
          "LAND",
          "WAY",
          "RISE"
        ]
      }
    ]
  },
  {
    "id": 94,
    "groups": [
      {
        "label": "Things That Can \"Ring\"",
        "color": "yellow",
        "words": [
          "PHONE",
          "BELL",
          "ALARM",
          "BOXING"
        ]
      },
      {
        "label": "Types of Seal",
        "color": "green",
        "words": [
          "NAVY",
          "WAX",
          "HEAT",
          "RUBBER"
        ]
      },
      {
        "label": "Things That Can Be \"Sharp\"",
        "color": "blue",
        "words": [
          "KNIFE",
          "MIND",
          "PAIN",
          "CONTRAST"
        ]
      },
      {
        "label": "Words Before \"CUT\"",
        "color": "purple",
        "words": [
          "HAIR",
          "PAPER",
          "SHORT",
          "UNDER"
        ]
      }
    ]
  },
  {
    "id": 95,
    "groups": [
      {
        "label": "Things That Have Teeth",
        "color": "yellow",
        "words": [
          "COMB",
          "GEAR",
          "SAW",
          "ZIPPER"
        ]
      },
      {
        "label": "Types of Trade",
        "color": "green",
        "words": [
          "FREE",
          "SLAVE",
          "FAIR",
          "DRUG"
        ]
      },
      {
        "label": "Things That Can \"Flow\"",
        "color": "blue",
        "words": [
          "RIVER",
          "TRAFFIC",
          "CONVERSATION",
          "LAVA"
        ]
      },
      {
        "label": "Can Precede \"WORK\"",
        "color": "purple",
        "words": [
          "GUESS",
          "FOOT",
          "OVER",
          "DIRT"
        ]
      }
    ]
  },
  {
    "id": 96,
    "groups": [
      {
        "label": "Things You Can Tap",
        "color": "yellow",
        "words": [
          "PHONE",
          "KEG",
          "SHOULDER",
          "DANCE"
        ]
      },
      {
        "label": "Types of Run",
        "color": "green",
        "words": [
          "DRY",
          "HOME",
          "BULL",
          "TRIAL"
        ]
      },
      {
        "label": "Things That Can Be \"Flat\"",
        "color": "blue",
        "words": [
          "TIRE",
          "BATTERY",
          "NOTE",
          "STOMACH"
        ]
      },
      {
        "label": "Words After \"FLASH\"",
        "color": "purple",
        "words": [
          "BACK",
          "LIGHT",
          "POINT",
          "MOB"
        ]
      }
    ]
  },
  {
    "id": 97,
    "groups": [
      {
        "label": "Things That Can \"Open\"",
        "color": "yellow",
        "words": [
          "DOOR",
          "MIND",
          "WOUND",
          "ACCOUNT"
        ]
      },
      {
        "label": "Types of Blind",
        "color": "green",
        "words": [
          "VENETIAN",
          "ROLLER",
          "ROMAN",
          "PLEATED"
        ]
      },
      {
        "label": "Things That Can Be \"Deep\"",
        "color": "blue",
        "words": [
          "SLEEP",
          "THOUGHT",
          "WATER",
          "SOUTH"
        ]
      },
      {
        "label": "Can Follow \"SLEEP\"",
        "color": "purple",
        "words": [
          "WALKER",
          "OVER",
          "LESS",
          "WEAR"
        ]
      }
    ]
  },
  {
    "id": 98,
    "groups": [
      {
        "label": "Things That Can \"Blow\"",
        "color": "yellow",
        "words": [
          "WIND",
          "WHISTLE",
          "FUSE",
          "MIND"
        ]
      },
      {
        "label": "Types of Cast",
        "color": "green",
        "words": [
          "BROAD",
          "OVER",
          "POD",
          "TELE"
        ]
      },
      {
        "label": "Things That Can Be \"Hanging\"",
        "color": "blue",
        "words": [
          "JURY",
          "GARDEN",
          "MATTER",
          "CHAD"
        ]
      },
      {
        "label": "Words Before \"SIDE\"",
        "color": "purple",
        "words": [
          "OUT",
          "IN",
          "DOWN",
          "UP"
        ]
      }
    ]
  },
  {
    "id": 99,
    "groups": [
      {
        "label": "Things That Have \"Arms\"",
        "color": "yellow",
        "words": [
          "SOFA",
          "STAR",
          "CACTUS",
          "CLOCK"
        ]
      },
      {
        "label": "Types of Slip",
        "color": "green",
        "words": [
          "FREUDIAN",
          "PARACHUTE",
          "PINK",
          "TONGUE"
        ]
      },
      {
        "label": "Things That Can Be \"Broken\"",
        "color": "blue",
        "words": [
          "OATH",
          "WAVE",
          "TRAIL",
          "CODE"
        ]
      },
      {
        "label": "Can Follow \"TURN\"",
        "color": "purple",
        "words": [
          "OVER",
          "STILE",
          "AROUND",
          "OUT"
        ]
      }
    ]
  },
  {
    "id": 100,
    "groups": [
      {
        "label": "Things That Have a \"Face\" and \"Hands\"",
        "color": "yellow",
        "words": [
          "CLOCK",
          "WATCH",
          "COMPASS",
          "SUNDIAL"
        ]
      },
      {
        "label": "Types of Note",
        "color": "green",
        "words": [
          "STICKY",
          "BANKNOTE",
          "SUICIDE",
          "RANSOM"
        ]
      },
      {
        "label": "Things That Can Be \"Master\"",
        "color": "blue",
        "words": [
          "CLASS",
          "MIND",
          "PIECE",
          "PLAN"
        ]
      },
      {
        "label": "Words That Are Anagrams of Each Other",
        "color": "purple",
        "words": [
          "LEMON",
          "MELON",
          "ENOL",
          "LEON"
        ]
      }
    ]
  }
];
