import { UserProfile, Course, Task, TaskType, Priority, Note, Flashcard } from './types';
import { DEFAULT_COURSES, COURSE_NAMES } from './constants';

export const initialUser: UserProfile = {
  name: 'Syahrul Izwan',
  studentId: '2022456789',
  program: 'FSKM - Information System Engineering',
  part: 4,
  currentWeek: 11,
  startDate: '2025-10-14',
};

export const initialCourses: Course[] = DEFAULT_COURSES.map((id) => ({
  id,
  name: COURSE_NAMES[id] || `Course ${id}`,
  creditHours: 3,
  workload: [2, 3, 4, 6, 5, 7, 8, 4, 6, 8, 10, 9, 10, 4],
}));

export const initialTasks: Task[] = [
  {
    id: 't1',
    title: 'Final Project: Backend API',
    courseId: 'CSC584',
    type: TaskType.Project,
    dueDate: '2024-12-27',
    dueTime: '23:59',
    priority: Priority.High,
    effort: 12,
    notes: 'Implement JWT authentication and CRUD for student modules.',
    isDone: false,
    deadlineRisk: 'High',
    suggestedWeek: 11,
    sourceMessage: 'Dr. Zali: Please ensure the API documentation is updated by Friday night.',
  },
  {
    id: 't7',
    title: 'ISP573: Case Study Analysis',
    courseId: 'ISP573',
    type: TaskType.Assignment,
    dueDate: '2024-12-26',
    dueTime: '12:00',
    priority: Priority.Medium,
    effort: 5,
    notes: 'Analyze the business process for the assigned company.',
    isDone: false,
    deadlineRisk: 'Medium',
    suggestedWeek: 11,
  },
  {
    id: 't9',
    title: 'LCC401: Critical Reading Exercise',
    courseId: 'LCC401',
    type: TaskType.Assignment,
    dueDate: '2024-12-26',
    dueTime: '17:00',
    priority: Priority.Low,
    effort: 2,
    notes: 'Submit the summary for the article "AI in Education".',
    isDone: false,
    deadlineRisk: 'Low',
    suggestedWeek: 11,
  },
  {
    id: 't8',
    title: 'TAC451: Mandarin Speaking Test',
    courseId: 'TAC451',
    type: TaskType.Test,
    dueDate: '2024-12-27',
    dueTime: '14:00',
    priority: Priority.High,
    effort: 4,
    notes: 'Prepare dialogue script for Chapter 3-5.',
    isDone: false,
    deadlineRisk: 'High',
    suggestedWeek: 11,
  },
  {
    id: 't2',
    title: 'Lab 5: Retrofit & REST API',
    courseId: 'ICT551',
    type: TaskType.Lab,
    dueDate: '2024-12-30',
    dueTime: '17:00',
    priority: Priority.Medium,
    effort: 4,
    notes: 'Connect the mobile app to the mock server using Retrofit library.',
    isDone: false,
    deadlineRisk: 'Medium',
    suggestedWeek: 12,
  },
  {
    id: 't13',
    title: 'CTU551: Group Discussion Report',
    courseId: 'CTU551',
    type: TaskType.Assignment,
    dueDate: '2024-12-30',
    dueTime: '23:59',
    priority: Priority.Low,
    effort: 2,
    notes: 'Summary of the forum on "Islamic Ethics in AI".',
    isDone: false,
    deadlineRisk: 'Low',
    suggestedWeek: 12,
  },
  {
    id: 't10',
    title: 'ICT502: Networking Lab Report',
    courseId: 'ICT502',
    type: TaskType.Lab,
    dueDate: '2024-12-31',
    dueTime: '16:00',
    priority: Priority.Medium,
    effort: 4,
    notes: 'Documentation for Packet Tracer routing configuration.',
    isDone: false,
    deadlineRisk: 'Medium',
    suggestedWeek: 12,
  },
  {
    id: 't14',
    title: 'CSC584: Hibernate Mapping Lab',
    courseId: 'CSC584',
    type: TaskType.Lab,
    dueDate: '2025-01-06',
    dueTime: '10:00',
    priority: Priority.High,
    effort: 3,
    notes: 'Complete the One-to-Many and Many-to-Many exercise.',
    isDone: false,
    deadlineRisk: 'High',
    suggestedWeek: 13,
  },
  {
    id: 't3',
    title: 'System Design Document',
    courseId: 'IPS551',
    type: TaskType.Assignment,
    dueDate: '2025-01-08',
    dueTime: '23:59',
    priority: Priority.High,
    effort: 8,
    notes: 'Prepare the DFD Level 0, 1 and ERD for the case study.',
    isDone: false,
    deadlineRisk: 'High',
    suggestedWeek: 13,
  },
  {
    id: 't5',
    title: 'Reflection Video: CTU551',
    courseId: 'CTU551',
    type: TaskType.Project,
    dueDate: '2025-01-10',
    dueTime: '23:59',
    priority: Priority.Medium,
    effort: 3,
    notes: 'Record a 3-minute video on Islamic contributions to modern science.',
    isDone: false,
    deadlineRisk: 'Medium',
    suggestedWeek: 13,
  },
  {
    id: 't11',
    title: 'IPS551: Requirements Gathering Report',
    courseId: 'IPS551',
    type: TaskType.Assignment,
    dueDate: '2024-12-20',
    dueTime: '23:59',
    priority: Priority.High,
    effort: 6,
    notes: 'Interview notes and user requirement specifications.',
    isDone: true,
    deadlineRisk: 'Low',
    suggestedWeek: 10,
  },
  {
    id: 't4',
    title: 'Quiz 2: Enterprise Patterns',
    courseId: 'CSC584',
    type: TaskType.Quiz,
    dueDate: '2024-12-23',
    dueTime: '08:00',
    priority: Priority.Medium,
    effort: 2,
    notes: 'Study MVC, Singleton, and Bridge patterns.',
    isDone: true,
    deadlineRisk: 'Low',
    suggestedWeek: 11,
  },
  {
    id: 't6',
    title: 'Infrastructure Test 1',
    courseId: 'ICT502',
    type: TaskType.Test,
    dueDate: '2024-12-18',
    dueTime: '10:00',
    priority: Priority.High,
    effort: 6,
    notes: 'Coverage: Chapter 1 to 4. OSI Model and Subnetting.',
    isDone: true,
    deadlineRisk: 'Low',
    suggestedWeek: 10,
  },
];

export const initialNotes: Note[] = [
  { id: 'n1', subjectId: 'CSC584', title: 'MVC Architecture', content: 'Model-View-Controller separates concerns:\n\n• Model: Data and business logic\n• View: User interface presentation\n• Controller: Handles input and updates model\n\nSpring Boot uses @Controller, @Service, @Repository annotations.', tag: 'Lecture', updatedAt: '2024-12-20' },
  { id: 'n2', subjectId: 'CSC584', title: 'Hibernate Mapping', content: 'Entity relationships in JPA/Hibernate:\n\n• @OneToMany: One entity has many related entities\n• @ManyToOne: Many entities belong to one\n• @ManyToMany: Bidirectional relationship with join table\n\nUse CascadeType.ALL for automatic persistence.', tag: 'Tutorial', updatedAt: '2024-12-23' },
  { id: 'n3', subjectId: 'CSC584', title: 'REST API Design', content: 'RESTful principles:\n\n• GET: Retrieve resources\n• POST: Create new resources\n• PUT: Update existing resources\n• DELETE: Remove resources\n\nUse proper HTTP status codes: 200 OK, 201 Created, 404 Not Found.', tag: 'Lecture', updatedAt: '2024-12-25' },
  { id: 'n4', subjectId: 'IPS551', title: 'Requirements Engineering', content: 'Gathering requirements:\n\n1. Stakeholder interviews\n2. Document analysis\n3. Observation\n4. Prototyping\n\nOutput: Software Requirements Specification (SRS) document.', tag: 'Lecture', updatedAt: '2024-12-18' },
  { id: 'n5', subjectId: 'IPS551', title: 'DFD Diagrams', content: 'Data Flow Diagram levels:\n\n• Level 0: Context diagram (single process)\n• Level 1: Major processes breakdown\n• Level 2: Detailed sub-processes\n\nComponents: Process, Data Store, External Entity, Data Flow.', tag: 'Tutorial', updatedAt: '2024-12-22' },
  { id: 'n6', subjectId: 'ICT551', title: 'Android Lifecycle', content: 'Activity lifecycle methods:\n\n• onCreate(): Initialize activity\n• onStart(): Activity becomes visible\n• onResume(): Activity gains focus\n• onPause(): Activity loses focus\n• onStop(): Activity no longer visible\n• onDestroy(): Activity destroyed', tag: 'Lecture', updatedAt: '2024-12-19' },
  { id: 'n7', subjectId: 'ICT551', title: 'Retrofit Setup', content: 'Setting up Retrofit for API calls:\n\n1. Add dependencies in build.gradle\n2. Create API interface with @GET, @POST\n3. Build Retrofit instance with base URL\n4. Use Call<T> for async requests\n5. Handle responses in callbacks', tag: 'Lecture', updatedAt: '2024-12-24' },
  { id: 'n8', subjectId: 'ICT502', title: 'OSI Model', content: 'Seven layers of networking:\n\n7. Application - HTTP, FTP\n6. Presentation - Encryption, compression\n5. Session - Connection management\n4. Transport - TCP, UDP\n3. Network - IP routing\n2. Data Link - MAC addresses\n1. Physical - Cables, signals', tag: 'Lecture', updatedAt: '2024-12-15' },
  { id: 'n9', subjectId: 'CTU551', title: 'Islamic Ethics in Tech', content: 'Key principles:\n\n• Amanah (Trust): Data privacy responsibility\n• Maslahah (Public interest): Technology for good\n• Adalah (Justice): Fair algorithms and AI\n• Ihsan (Excellence): Quality in work\n\nApply these principles in IT career.', tag: 'Lecture', updatedAt: '2024-12-21' },
];

export const initialFlashcards: Flashcard[] = [
  { id: 'f1', noteId: 'n1', question: 'What does MVC stand for?', answer: 'Model-View-Controller - a design pattern that separates application concerns' },
  { id: 'f2', noteId: 'n1', question: 'What is the role of Controller in MVC?', answer: 'Handles user input, updates the model, and selects views for response' },
  { id: 'f3', noteId: 'n2', question: 'What annotation is used for one-to-many relationships?', answer: '@OneToMany - indicates one entity has multiple related entities' },
  { id: 'f4', noteId: 'n3', question: 'What HTTP method is used to create resources?', answer: 'POST - creates new resources on the server' },
  { id: 'f5', noteId: 'n3', question: 'What HTTP status code means success?', answer: '200 OK - request was successful' },
  { id: 'f6', noteId: 'n5', question: 'What is a Context Diagram?', answer: 'DFD Level 0 - shows the entire system as a single process with external entities' },
  { id: 'f7', noteId: 'n4', question: 'What document contains all requirements?', answer: 'SRS - Software Requirements Specification' },
  { id: 'f8', noteId: 'n8', question: 'Which OSI layer handles IP routing?', answer: 'Layer 3 - Network layer' },
  { id: 'f9', noteId: 'n8', question: 'Which OSI layer uses MAC addresses?', answer: 'Layer 2 - Data Link layer' },
  { id: 'f10', noteId: 'n8', question: 'What protocols work at the Transport layer?', answer: 'TCP and UDP' },
];
