// Word/clue banks for Pack 2 — Movie Night.
//
// Same shape as crosswordBanks.ts. Deliberately film *craft* and vocabulary
// rather than film titles or character names: those age badly, vary by country,
// and belong to somebody. A student in Shah Alam and one in Kota Bharu should
// have the same chance at every clue.
import type { Theme } from './crosswordBanks';

export const MOVIE_THEMES: Theme[] = [
  {
    title: 'Movie Genres',
    bonus: 'GENRE',
    entries: [
      { word: 'GENRE', clue: 'The kind of film something is' },
      { word: 'DRAMA', clue: 'Serious, feelings-first genre' },
      { word: 'COMEDY', clue: 'Made to make you laugh' },
      { word: 'HORROR', clue: 'Made to make you jump' },
      { word: 'ACTION', clue: 'Chases, fights and explosions' },
      { word: 'CRIME', clue: 'Genre full of robbers and police' },
      { word: 'NOIR', clue: 'Shadowy detective style, French for black' },
      { word: 'EPIC', clue: 'Long film on a huge scale' },
      { word: 'FARCE', clue: 'Silly comedy of mistakes' },
      { word: 'SATIRE', clue: 'Comedy that mocks the powerful' },
      { word: 'WESTERN', clue: 'Cowboy genre' },
      { word: 'FANTASY', clue: 'Genre with magic and dragons' },
      { word: 'ROMANCE', clue: 'Love-story genre' },
      { word: 'MUSICAL', clue: 'Genre where they burst into song' },
    ],
  },
  {
    title: 'At the Cinema',
    bonus: 'CINEMA',
    entries: [
      { word: 'CINEMA', clue: 'Where you go to watch a film' },
      { word: 'TICKET', clue: 'You buy one to get in' },
      { word: 'SCREEN', clue: 'The big white rectangle' },
      { word: 'USHER', clue: 'Staff member with a torch' },
      { word: 'AISLE', clue: 'Walkway between seat blocks' },
      { word: 'SEAT', clue: 'What your ticket number points to' },
      { word: 'POPCORN', clue: 'Classic cinema snack' },
      { word: 'LOBBY', clue: 'Area before the screens' },
      { word: 'TRAILER', clue: 'Preview of a film still to come' },
      { word: 'MATINEE', clue: 'Daytime showing' },
      { word: 'ROW', clue: 'Letter on your ticket' },
      { word: 'SODA', clue: 'Fizzy drink in a huge cup' },
      { word: 'QUEUE', clue: 'Line you wait in' },
      { word: 'FOYER', clue: 'Entrance hall' },
    ],
  },
  {
    title: 'Film Crew',
    bonus: 'CREW',
    entries: [
      { word: 'CREW', clue: 'Everyone working behind the camera' },
      { word: 'GAFFER', clue: 'Chief electrician on a set' },
      { word: 'GRIP', clue: 'Crew member who moves the rigging' },
      { word: 'EDITOR', clue: 'Cuts the shots together' },
      { word: 'WRITER', clue: 'Person behind the script' },
      { word: 'ACTOR', clue: 'Person in front of the camera' },
      { word: 'EXTRA', clue: 'Background performer' },
      { word: 'STUNT', clue: 'Dangerous bit done by a double' },
      { word: 'CAST', clue: 'All the actors together' },
      { word: 'RUNNER', clue: 'Junior who fetches and carries' },
      { word: 'BOOM', clue: 'Long pole holding the microphone' },
      { word: 'SCOUT', clue: 'Finds places to film' },
      { word: 'MAKEUP', clue: 'Department with brushes and powder' },
      { word: 'SCRIPT', clue: 'Pages the actors learn from' },
    ],
  },
  {
    title: 'Camera Shots',
    bonus: 'CAMERA',
    entries: [
      { word: 'CAMERA', clue: 'It records the picture' },
      { word: 'ZOOM', clue: 'Move in without moving the camera' },
      { word: 'PAN', clue: 'Swing the camera left or right' },
      { word: 'TILT', clue: 'Swing the camera up or down' },
      { word: 'WIDE', clue: 'Shot showing the whole scene' },
      { word: 'ANGLE', clue: 'Where the camera looks from' },
      { word: 'FRAME', clue: 'One single picture' },
      { word: 'FOCUS', clue: 'Make the picture sharp' },
      { word: 'LENS', clue: 'Glass at the front of the camera' },
      { word: 'TRACK', clue: 'Rails the camera rolls along' },
      { word: 'CRANE', clue: 'Arm that lifts the camera high' },
      { word: 'DOLLY', clue: 'Wheeled platform for the camera' },
      { word: 'SHOT', clue: 'One unbroken piece of filming' },
      { word: 'TAKE', clue: 'Attempt number three, say' },
    ],
  },
  {
    title: 'Animation',
    bonus: 'CARTOON',
    entries: [
      { word: 'CARTOON', clue: 'Drawn film' },
      { word: 'CEL', clue: 'Clear sheet old animators painted on' },
      { word: 'FRAME', clue: 'Twenty-four of these a second' },
      { word: 'PIXEL', clue: 'Tiny square of a digital picture' },
      { word: 'MODEL', clue: 'Digital shape an animator moves' },
      { word: 'RIG', clue: 'Skeleton built inside a character' },
      { word: 'ANIME', clue: 'Japanese animation style' },
      { word: 'CLAY', clue: 'Material for stop-motion figures' },
      { word: 'DRAW', clue: 'What an animator does by hand' },
      { word: 'SKETCH', clue: 'Rough early drawing' },
      { word: 'RENDER', clue: 'Turn the model into a finished picture' },
      { word: 'MOTION', clue: 'Movement, the whole point of it' },
      { word: 'SCENE', clue: 'One place, one stretch of story' },
      { word: 'STORY', clue: 'What the drawings add up to' },
    ],
  },
  {
    title: 'Making a Film',
    bonus: 'DIRECT',
    entries: [
      { word: 'DIRECT', clue: 'Tell the cast and crew what to do' },
      { word: 'SET', clue: 'Place built for filming' },
      { word: 'SCENE', clue: 'Chunk of the film in one place' },
      { word: 'ACT', clue: 'One of three big parts of a story' },
      { word: 'CUT', clue: 'Word that stops the cameras' },
      { word: 'EDIT', clue: 'Trim and rearrange the footage' },
      { word: 'SHOOT', clue: 'Film the scene' },
      { word: 'REHEARSE', clue: 'Practise before the take' },
      { word: 'BUDGET', clue: 'Money the film is allowed' },
      { word: 'STAGE', clue: 'Big shed where sets are built' },
      { word: 'LOCATION', clue: 'Real place used instead of a set' },
      { word: 'CASTING', clue: 'Choosing who plays whom' },
      { word: 'SLATE', clue: 'Clapper board' },
      { word: 'REEL', clue: 'Spool of film' },
    ],
  },
  {
    title: 'Movie Awards',
    bonus: 'TROPHY',
    entries: [
      { word: 'TROPHY', clue: 'What a winner lifts' },
      { word: 'AWARD', clue: 'Prize for the best of something' },
      { word: 'PRIZE', clue: 'What you win' },
      { word: 'NOMINEE', clue: 'One of five hoping to win' },
      { word: 'WINNER', clue: 'The name in the envelope' },
      { word: 'GALA', clue: 'Grand evening event' },
      { word: 'VOTE', clue: 'How the members decide' },
      { word: 'STATUE', clue: 'Little gold figure' },
      { word: 'SPEECH', clue: 'Thank-you talk on stage' },
      { word: 'MEDAL', clue: 'Another thing winners get' },
      { word: 'GLOBE', clue: 'Round award named after the world' },
      { word: 'PANEL', clue: 'Group that judges' },
      { word: 'HOST', clue: 'Person who runs the ceremony' },
      { word: 'STAGE', clue: 'Where the speech happens' },
    ],
  },
  {
    title: 'Special Effects',
    bonus: 'EFFECTS',
    entries: [
      { word: 'EFFECTS', clue: 'Tricks that make the impossible look real' },
      { word: 'GREEN', clue: 'Colour of the screen they film against' },
      { word: 'SMOKE', clue: 'Machine-made haze on set' },
      { word: 'WIRE', clue: 'Hidden line that makes an actor fly' },
      { word: 'MASK', clue: 'Face covering for a creature' },
      { word: 'BLAST', clue: 'Explosion, safely done' },
      { word: 'DUMMY', clue: 'Fake body used for a fall' },
      { word: 'MODEL', clue: 'Small version of a big thing' },
      { word: 'PROP', clue: 'Object an actor handles' },
      { word: 'PAINT', clue: 'Matte artists do it on glass' },
      { word: 'DIGITAL', clue: 'Made in a computer' },
      { word: 'MOTION', clue: 'Capture of an actor as dots' },
      { word: 'FOAM', clue: 'Light stuff fake rocks are made of' },
      { word: 'RIG', clue: 'Hidden frame holding something up' },
    ],
  },
  {
    title: 'Movie Sound',
    bonus: 'FOLEY',
    entries: [
      { word: 'FOLEY', clue: 'Everyday sounds made by hand in a studio' },
      { word: 'SCORE', clue: 'Music written for the film' },
      { word: 'THEME', clue: 'Tune you hum on the way out' },
      { word: 'DUB', clue: 'Record new voices over the old' },
      { word: 'MIX', clue: 'Balance all the sounds together' },
      { word: 'ECHO', clue: 'Sound bouncing back' },
      { word: 'MONO', clue: 'One channel only' },
      { word: 'STEREO', clue: 'Left and right channels' },
      { word: 'TRACK', clue: 'One layer of recorded sound' },
      { word: 'MUSIC', clue: 'What the orchestra plays' },
      { word: 'VOICE', clue: 'What an actor speaks with' },
      { word: 'NOISE', clue: 'Unwanted sound' },
      { word: 'TONE', clue: 'Quality of a sound' },
      { word: 'CUE', clue: 'Signal to start' },
    ],
  },
  {
    title: 'Lights on Set',
    bonus: 'LIGHTING',
    entries: [
      { word: 'LIGHTING', clue: 'Whole craft of lighting a scene' },
      { word: 'LAMP', clue: 'Single light unit' },
      { word: 'BULB', clue: 'The bit that glows' },
      { word: 'BEAM', clue: 'Shaft of light' },
      { word: 'GLOW', clue: 'Soft light' },
      { word: 'SHADE', clue: 'Area the light misses' },
      { word: 'SHADOW', clue: 'Dark shape cast by a body' },
      { word: 'GLARE', clue: 'Light that is too harsh' },
      { word: 'SPOT', clue: 'Tight circle of light' },
      { word: 'FLOOD', clue: 'Wide, even light' },
      { word: 'DIMMER', clue: 'Control that lowers the level' },
      { word: 'STAND', clue: 'Legs a lamp sits on' },
      { word: 'GEL', clue: 'Coloured sheet over a lamp' },
      { word: 'HAZE', clue: 'Thin mist that shows the beams' },
    ],
  },
  {
    title: 'Costume and Makeup',
    bonus: 'COSTUME',
    entries: [
      { word: 'COSTUME', clue: 'What a character wears' },
      { word: 'WIG', clue: 'False hair' },
      { word: 'CAPE', clue: 'Cloth that flows behind a hero' },
      { word: 'MASK', clue: 'Worn to hide a face' },
      { word: 'ROBE', clue: 'Long loose garment' },
      { word: 'BOOTS', clue: 'Footwear for a cowboy' },
      { word: 'ARMOUR', clue: 'Metal worn in a battle scene' },
      { word: 'POWDER', clue: 'Stops an actor shining' },
      { word: 'BRUSH', clue: 'Tool for applying makeup' },
      { word: 'SCAR', clue: 'Fake mark on the skin' },
      { word: 'PAINT', clue: 'Colour on the face' },
      { word: 'DRESS', clue: 'Garment for the ballroom scene' },
      { word: 'HAT', clue: 'Headwear' },
      { word: 'SEWING', clue: 'Needle-and-thread work' },
    ],
  },
  {
    title: 'The Script',
    bonus: 'SCREENPLAY',
    entries: [
      { word: 'SCREENPLAY', clue: 'The film written down' },
      { word: 'PLOT', clue: 'What happens, in order' },
      { word: 'TWIST', clue: 'Surprise near the end' },
      { word: 'HERO', clue: 'Character you root for' },
      { word: 'VILLAIN', clue: 'Character you root against' },
      { word: 'DRAFT', clue: 'One version of the writing' },
      { word: 'LINE', clue: 'One thing a character says' },
      { word: 'PAGE', clue: 'Roughly one minute of film' },
      { word: 'SCENE', clue: 'One unit of the script' },
      { word: 'ENDING', clue: 'How it all finishes' },
      { word: 'DIALOG', clue: 'The talking parts' },
      { word: 'THEME', clue: 'What the story is really about' },
      { word: 'ARC', clue: 'How a character changes' },
      { word: 'NOTE', clue: 'Comment from the studio' },
    ],
  },
  {
    title: 'Horror Films',
    bonus: 'SCREAM',
    entries: [
      { word: 'SCREAM', clue: 'Loud sound of fright' },
      { word: 'GHOST', clue: 'Spirit that haunts a house' },
      { word: 'CREEPY', clue: 'Unsettling in a quiet way' },
      { word: 'CURSE', clue: 'Bad luck placed on someone' },
      { word: 'CRYPT', clue: 'Underground burial room' },
      { word: 'FEAR', clue: 'What the genre runs on' },
      { word: 'DARK', clue: 'Where the scary things are' },
      { word: 'MOON', clue: 'It is always full in these films' },
      { word: 'GRAVE', clue: 'Where the body was buried' },
      { word: 'CHILL', clue: 'Cold feeling down the spine' },
      { word: 'HAUNT', clue: 'Keep coming back to a place' },
      { word: 'TERROR', clue: 'Very great fear' },
      { word: 'BLOOD', clue: 'Red stuff, usually fake' },
      { word: 'MIST', clue: 'Low fog in the graveyard' },
    ],
  },
  {
    title: 'Science Fiction',
    bonus: 'FUTURE',
    entries: [
      { word: 'FUTURE', clue: 'When these films are usually set' },
      { word: 'ROBOT', clue: 'Machine that acts like a person' },
      { word: 'ALIEN', clue: 'Visitor from another world' },
      { word: 'LASER', clue: 'Beam weapon' },
      { word: 'ORBIT', clue: 'Path around a planet' },
      { word: 'SPACE', clue: 'The final frontier' },
      { word: 'PLANET', clue: 'World going round a star' },
      { word: 'ROCKET', clue: 'It launches upward' },
      { word: 'CLONE', clue: 'Exact copy of a person' },
      { word: 'ANDROID', clue: 'Robot built to look human' },
      { word: 'WARP', clue: 'Bend space to travel fast' },
      { word: 'BEAM', clue: 'Teleport someone up' },
      { word: 'STAR', clue: 'Burning ball of gas' },
      { word: 'MOON', clue: 'Body that circles a planet' },
    ],
  },
  {
    title: 'Action Films',
    bonus: 'CHASE',
    entries: [
      { word: 'CHASE', clue: 'Sequence where one car follows another' },
      { word: 'ESCAPE', clue: 'Get out just in time' },
      { word: 'FIGHT', clue: 'Choreographed punch-up' },
      { word: 'JUMP', clue: 'Leap between rooftops' },
      { word: 'RESCUE', clue: 'Save someone' },
      { word: 'CRASH', clue: 'What the stunt car does' },
      { word: 'SPEED', clue: 'How fast it all happens' },
      { word: 'AGENT', clue: 'Hero with a licence' },
      { word: 'ENEMY', clue: 'Who the hero is up against' },
      { word: 'BOMB', clue: 'Thing with a countdown' },
      { word: 'RACE', clue: 'Contest of speed' },
      { word: 'ROOF', clue: 'Where the final fight happens' },
      { word: 'DIVE', clue: 'Throw yourself out of the way' },
      { word: 'TRAP', clue: 'Hidden danger' },
    ],
  },
  {
    title: 'Comedy Films',
    bonus: 'LAUGH',
    entries: [
      { word: 'LAUGH', clue: 'What the audience should do' },
      { word: 'JOKE', clue: 'Line written to be funny' },
      { word: 'GAG', clue: 'Visual joke' },
      { word: 'SPOOF', clue: 'Film that sends up another' },
      { word: 'IRONY', clue: 'Saying one thing, meaning another' },
      { word: 'SILLY', clue: 'Pleasantly daft' },
      { word: 'PRANK', clue: 'Trick played on someone' },
      { word: 'WIT', clue: 'Quick cleverness' },
      { word: 'SLAPSTICK', clue: 'Comedy of falling over' },
      { word: 'TIMING', clue: 'The secret of a good joke' },
      { word: 'PUN', clue: 'Joke about two meanings of a word' },
      { word: 'SMILE', clue: 'Smaller than a laugh' },
      { word: 'ROAST', clue: 'Comic mocking of a guest' },
      { word: 'CLOWN', clue: 'Funny performer' },
    ],
  },
  {
    title: 'Film Festivals',
    bonus: 'PREMIERE',
    entries: [
      { word: 'PREMIERE', clue: 'First public showing' },
      { word: 'CARPET', clue: 'It is red and stars walk on it' },
      { word: 'JURY', clue: 'Panel that picks the winner' },
      { word: 'ENTRY', clue: 'Film submitted for judging' },
      { word: 'SHORT', clue: 'Film under forty minutes' },
      { word: 'DEBUT', clue: 'A first film' },
      { word: 'CROWD', clue: 'People outside the venue' },
      { word: 'PRESS', clue: 'Reporters at the event' },
      { word: 'PHOTO', clue: 'What the cameras outside want' },
      { word: 'TICKET', clue: 'Pass to get in' },
      { word: 'VENUE', clue: 'Where it is all held' },
      { word: 'GUEST', clue: 'Invited attendee' },
      { word: 'FLASH', clue: 'Burst of light from a camera' },
      { word: 'BUZZ', clue: 'Excited talk about a film' },
    ],
  },
  {
    title: 'Film Editing',
    bonus: 'MONTAGE',
    entries: [
      { word: 'MONTAGE', clue: 'Quick run of shots showing time passing' },
      { word: 'SPLICE', clue: 'Join two pieces of film' },
      { word: 'FADE', clue: 'Picture slowly going to black' },
      { word: 'WIPE', clue: 'One shot pushing another off screen' },
      { word: 'TRIM', clue: 'Shorten a shot' },
      { word: 'JUMP', clue: 'Cut that skips forward jarringly' },
      { word: 'ORDER', clue: 'The sequence shots end up in' },
      { word: 'PACE', clue: 'How fast the film feels' },
      { word: 'ROUGH', clue: 'First assembled version' },
      { word: 'FINAL', clue: 'The locked version' },
      { word: 'CLIP', clue: 'Short piece of footage' },
      { word: 'FOOTAGE', clue: 'All the material that was shot' },
      { word: 'SPLIT', clue: 'Screen divided in two' },
      { word: 'CUT', clue: 'The join itself' },
    ],
  },
  {
    title: 'Movie Theatres',
    bonus: 'PROJECTOR',
    entries: [
      { word: 'PROJECTOR', clue: 'Machine that throws the picture' },
      { word: 'BOOTH', clue: 'Little room at the back' },
      { word: 'SILVER', clue: 'Nickname for the screen' },
      { word: 'CURTAIN', clue: 'It opens before the film' },
      { word: 'BALCONY', clue: 'Upper seating' },
      { word: 'STALLS', clue: 'Ground-floor seats' },
      { word: 'EXIT', clue: 'Green sign by the door' },
      { word: 'DOOR', clue: 'Way in and out' },
      { word: 'LIGHT', clue: 'It dims as the film starts' },
      { word: 'SOUND', clue: 'It comes from all around you' },
      { word: 'SEATS', clue: 'Rows of them' },
      { word: 'STEP', clue: 'Mind it in the dark' },
      { word: 'SCREEN', clue: 'What you all stare at' },
      { word: 'SHOW', clue: 'The screening itself' },
    ],
  },
  {
    title: 'Behind the Scenes',
    bonus: 'BLOOPER',
    entries: [
      { word: 'BLOOPER', clue: 'Mistake kept for the credits' },
      { word: 'DOUBLE', clue: 'Stands in for the star' },
      { word: 'TRAILER', clue: 'Van an actor rests in' },
      { word: 'CALL', clue: 'Time you must be on set' },
      { word: 'WRAP', clue: 'Word that ends the shoot' },
      { word: 'BREAK', clue: 'Rest between takes' },
      { word: 'LUNCH', clue: 'Midday stop' },
      { word: 'CHAIR', clue: 'It has a name printed on the back' },
      { word: 'CREW', clue: 'The whole working team' },
      { word: 'SETUP', clue: 'Arranging camera and lights' },
      { word: 'DELAY', clue: 'What rain causes' },
      { word: 'NIGHT', clue: 'When some scenes must be shot' },
      { word: 'TAPE', clue: 'It marks where to stand' },
      { word: 'NOTES', clue: 'Comments after a take' },
    ],
  },
  {
    title: 'Film Story',
    bonus: 'SEQUEL',
    entries: [
      { word: 'SEQUEL', clue: 'The one that comes after' },
      { word: 'PREQUEL', clue: 'The one set before' },
      { word: 'REMAKE', clue: 'Same story, filmed again' },
      { word: 'SERIES', clue: 'Run of connected films' },
      { word: 'REBOOT', clue: 'Start the whole thing over' },
      { word: 'CAMEO', clue: 'Tiny appearance by someone famous' },
      { word: 'CREDIT', clue: 'Name in the list at the end' },
      { word: 'TITLE', clue: 'What the film is called' },
      { word: 'OPENING', clue: 'The first few minutes' },
      { word: 'CLIMAX', clue: 'The biggest moment' },
      { word: 'SCENE', clue: 'One piece of the whole' },
      { word: 'PART', clue: 'Number two, say' },
      { word: 'EPIC', clue: 'Long and grand' },
      { word: 'TALE', clue: 'A story' },
    ],
  },
  {
    title: 'Western Films',
    bonus: 'COWBOY',
    entries: [
      { word: 'COWBOY', clue: 'Hero on horseback' },
      { word: 'HORSE', clue: 'He rides one' },
      { word: 'SALOON', clue: 'Bar with swinging doors' },
      { word: 'SHERIFF', clue: 'Lawman with a star' },
      { word: 'DUEL', clue: 'Face-off in the street' },
      { word: 'RANCH', clue: 'Cattle farm' },
      { word: 'DESERT', clue: 'Dry, sandy setting' },
      { word: 'WAGON', clue: 'Cart pulled by horses' },
      { word: 'BADGE', clue: 'Metal star on a chest' },
      { word: 'OUTLAW', clue: 'Wanted man' },
      { word: 'CANYON', clue: 'Deep rocky valley' },
      { word: 'SPURS', clue: 'They jingle on boots' },
      { word: 'TOWN', clue: 'One dusty street of it' },
      { word: 'TRAIL', clue: 'Path across the plains' },
    ],
  },
  {
    title: 'Movie Snacks',
    bonus: 'POPCORN',
    entries: [
      { word: 'POPCORN', clue: 'It bursts when heated' },
      { word: 'NACHOS', clue: 'Chips with melted cheese' },
      { word: 'CANDY', clue: 'Sweets in a box' },
      { word: 'SODA', clue: 'Fizzy drink' },
      { word: 'STRAW', clue: 'You sip through it' },
      { word: 'SALT', clue: 'Sprinkled on the popcorn' },
      { word: 'BUTTER', clue: 'The other popcorn topping' },
      { word: 'ICE', clue: 'It rattles in the cup' },
      { word: 'CHIPS', clue: 'Crunchy snack' },
      { word: 'SWEET', clue: 'Opposite of savoury' },
      { word: 'CUP', clue: 'It holds the drink' },
      { word: 'TRAY', clue: 'You carry it all on this' },
      { word: 'SNACK', clue: 'Small thing to eat' },
      { word: 'COMBO', clue: 'Drink and popcorn together' },
    ],
  },
  {
    title: 'Film Studios',
    bonus: 'BACKLOT',
    entries: [
      { word: 'BACKLOT', clue: 'Outdoor area with standing sets' },
      { word: 'STAGE', clue: 'Soundproof shed for filming' },
      { word: 'VAULT', clue: 'Where old films are kept' },
      { word: 'GATE', clue: 'You need a pass to get past it' },
      { word: 'LOGO', clue: 'Animation before the film starts' },
      { word: 'TOUR', clue: 'Visitors ride round on one' },
      { word: 'SET', clue: 'Built world for a scene' },
      { word: 'OFFICE', clue: 'Where the executives sit' },
      { word: 'STORE', clue: 'Where props are kept' },
      { word: 'LOT', clue: 'The studio grounds' },
      { word: 'SIGN', clue: 'Big letters on a hill' },
      { word: 'CRANE', clue: 'It lifts heavy things' },
      { word: 'TRUCK', clue: 'It hauls the gear' },
      { word: 'POWER', clue: 'The lights need a lot of it' },
    ],
  },
  {
    title: 'Movie Villains',
    bonus: 'MENACE',
    entries: [
      { word: 'MENACE', clue: 'Something threatening' },
      { word: 'EVIL', clue: 'What the villain is' },
      { word: 'PLAN', clue: 'The scheme to take over' },
      { word: 'LAIR', clue: 'Secret hideout' },
      { word: 'THREAT', clue: 'Promise of harm' },
      { word: 'TRAP', clue: 'Set for the hero' },
      { word: 'MINION', clue: 'Henchman' },
      { word: 'GREED', clue: 'Wanting far too much' },
      { word: 'SCAR', clue: 'Mark that hints at a past' },
      { word: 'LAUGH', clue: 'The villain does it slowly' },
      { word: 'CRIME', clue: 'What they commit' },
      { word: 'ESCAPE', clue: 'They always manage one' },
      { word: 'MASTER', clue: 'The one giving the orders' },
      { word: 'DOOM', clue: 'Terrible fate' },
    ],
  },
  {
    title: 'On Location',
    bonus: 'SCOUTING',
    entries: [
      { word: 'SCOUTING', clue: 'Hunting for places to film' },
      { word: 'PERMIT', clue: 'Paper letting you film there' },
      { word: 'STREET', clue: 'It gets closed for the shoot' },
      { word: 'BRIDGE', clue: 'Crossing over water' },
      { word: 'FOREST', clue: 'Trees everywhere' },
      { word: 'BEACH', clue: 'Sand and sea' },
      { word: 'CASTLE', clue: 'Stone place with towers' },
      { word: 'ISLAND', clue: 'Land with water all round' },
      { word: 'DESERT', clue: 'Very dry place' },
      { word: 'ALLEY', clue: 'Narrow lane between buildings' },
      { word: 'ROOF', clue: 'Top of a building' },
      { word: 'FIELD', clue: 'Open ground' },
      { word: 'CAFE', clue: 'Small place to eat' },
      { word: 'TRAIN', clue: 'It runs on rails' },
    ],
  },
  {
    title: 'Film Tech',
    bonus: 'RESOLUTION',
    entries: [
      { word: 'RESOLUTION', clue: 'How much detail a picture holds' },
      { word: 'DIGITAL', clue: 'Not shot on film' },
      { word: 'TRIPOD', clue: 'Three-legged camera support' },
      { word: 'FILTER', clue: 'Glass that changes the look' },
      { word: 'CABLE', clue: 'It carries the signal' },
      { word: 'MONITOR', clue: 'Screen the director watches' },
      { word: 'DRONE', clue: 'Flying camera' },
      { word: 'BATTERY', clue: 'It powers the kit' },
      { word: 'MEMORY', clue: 'Card the footage lands on' },
      { word: 'CODEC', clue: 'How video is squeezed down' },
      { word: 'GIMBAL', clue: 'It keeps the camera steady' },
      { word: 'SENSOR', clue: 'Chip that catches the light' },
      { word: 'MOUNT', clue: 'It attaches the lens' },
      { word: 'RIG', clue: 'Frame holding the gear' },
    ],
  },
  {
    title: 'Fantasy Films',
    bonus: 'QUEST',
    entries: [
      { word: 'QUEST', clue: 'Long journey with a purpose' },
      { word: 'MAGIC', clue: 'What the wizard does' },
      { word: 'SWORD', clue: 'Blade pulled from a stone' },
      { word: 'DRAGON', clue: 'It breathes fire' },
      { word: 'WIZARD', clue: 'Old man with a staff' },
      { word: 'SPELL', clue: 'Magic words' },
      { word: 'CROWN', clue: 'Worn by a king' },
      { word: 'REALM', clue: 'Kingdom' },
      { word: 'ELF', clue: 'Pointy-eared forest folk' },
      { word: 'TOWER', clue: 'Tall and usually dark' },
      { word: 'RING', clue: 'Small circle with great power' },
      { word: 'BEAST', clue: 'Large wild creature' },
      { word: 'CURSE', clue: 'Magic gone bad' },
      { word: 'SCROLL', clue: 'Rolled-up document' },
    ],
  },
  {
    title: 'Watching at Home',
    bonus: 'STREAMING',
    entries: [
      { word: 'STREAMING', clue: 'Watching without downloading' },
      { word: 'PAUSE', clue: 'Stop it for a moment' },
      { word: 'REMOTE', clue: 'You always lose it' },
      { word: 'SOFA', clue: 'Where you watch from' },
      { word: 'SCREEN', clue: 'The television itself' },
      { word: 'VOLUME', clue: 'Turn it down, it is late' },
      { word: 'SUBTITLE', clue: 'Words at the bottom' },
      { word: 'REPLAY', clue: 'Watch that bit again' },
      { word: 'BINGE', clue: 'Watch far too many in a row' },
      { word: 'SKIP', clue: 'Jump past the intro' },
      { word: 'BUFFER', clue: 'The spinning circle' },
      { word: 'DEVICE', clue: 'Phone, tablet or TV' },
      { word: 'LIST', clue: 'Things you mean to watch' },
      { word: 'RATING', clue: 'Stars out of five' },
    ],
  },
  {
    title: 'Film Words',
    bonus: 'CLAPPER',
    entries: [
      { word: 'CLAPPER', clue: 'Board that snaps shut before a take' },
      { word: 'ACTION', clue: 'Word that starts the take' },
      { word: 'ROLL', clue: 'Start the camera' },
      { word: 'QUIET', clue: 'What is called for on set' },
      { word: 'MARK', clue: 'Spot the actor must stand on' },
      { word: 'ANGLE', clue: 'Point of view of a shot' },
      { word: 'CLOSE', clue: 'Shot right up at a face' },
      { word: 'FRAME', clue: 'What is inside the picture' },
      { word: 'SHOT', clue: 'A single run of camera' },
      { word: 'TAKE', clue: 'Another go at the same shot' },
      { word: 'SCENE', clue: 'Numbered part of the script' },
      { word: 'SOUND', clue: 'It rolls before the picture' },
      { word: 'SPEED', clue: 'Called when the recorder is ready' },
      { word: 'RESET', clue: 'Put everything back for another take' },
    ],
  },
];
