// Word/clue banks for the crossword generator. Each theme provides a generous
// pool of words (3-7 letters); the generator interlocks as many as it can on a
// 7x7 grid. `bonus` names the preferred bonus word (★ extra points) if placed.

export interface BankEntry {
  word: string;
  clue: string;
}
export interface Theme {
  title: string;
  bonus: string;
  entries: BankEntry[];
}

export const THEMES: Theme[] = [
  {
    title: 'Animals',
    bonus: 'TIGER',
    entries: [
      { word: 'TIGER', clue: 'Big striped cat' },
      { word: 'HORSE', clue: 'Animal you can ride' },
      { word: 'SHEEP', clue: 'Wool-giving farm animal' },
      { word: 'OTTER', clue: 'Playful river swimmer' },
      { word: 'GOAT', clue: 'Horned animal that climbs' },
      { word: 'BEAR', clue: 'It hibernates in winter' },
      { word: 'LION', clue: 'King of the jungle' },
      { word: 'WOLF', clue: 'Wild relative of the dog' },
      { word: 'DEER', clue: 'Forest animal with antlers' },
      { word: 'SEAL', clue: 'It claps and barks at the zoo' },
      { word: 'RHINO', clue: 'Thick-skinned beast with a horn' },
      { word: 'ZEBRA', clue: 'Striped relative of the horse' },
      { word: 'MOOSE', clue: 'Large deer with broad antlers' },
      { word: 'PANDA', clue: 'Black-and-white bamboo eater' },
    ],
  },
  {
    title: 'Fruits',
    bonus: 'BANANA',
    entries: [
      { word: 'BANANA', clue: 'Long yellow fruit' },
      { word: 'APPLE', clue: 'Keeps the doctor away' },
      { word: 'GRAPE', clue: 'Small fruit grown in bunches' },
      { word: 'LEMON', clue: 'Sour yellow citrus' },
      { word: 'MANGO', clue: 'Sweet tropical fruit' },
      { word: 'MELON', clue: 'Big juicy summer fruit' },
      { word: 'PEACH', clue: 'Fuzzy orange fruit' },
      { word: 'PEAR', clue: 'Bell-shaped fruit' },
      { word: 'PLUM', clue: 'Small purple fruit' },
      { word: 'LIME', clue: 'Small green citrus' },
      { word: 'KIWI', clue: 'Fuzzy fruit, green inside' },
      { word: 'BERRY', clue: 'Small soft fruit, like a straw-' },
      { word: 'CHERRY', clue: 'Small red fruit with a stone' },
      { word: 'ORANGE', clue: 'Round citrus, same name as a color' },
    ],
  },
  {
    title: 'Space',
    bonus: 'ROCKET',
    entries: [
      { word: 'ROCKET', clue: 'It launches into space' },
      { word: 'PLANET', clue: 'Earth is one' },
      { word: 'COMET', clue: 'Icy body with a glowing tail' },
      { word: 'ORBIT', clue: 'Path around the sun' },
      { word: 'STAR', clue: 'The sun is one' },
      { word: 'MARS', clue: 'The red planet' },
      { word: 'MOON', clue: 'It orbits the Earth' },
      { word: 'VENUS', clue: 'Second planet from the sun' },
      { word: 'SOLAR', clue: '___ system' },
      { word: 'ALIEN', clue: 'Imagined being from space' },
      { word: 'METEOR', clue: 'Shooting star' },
      { word: 'NOVA', clue: 'Exploding star' },
      { word: 'EARTH', clue: 'The planet we live on' },
      { word: 'SATURN', clue: 'Planet famous for its rings' },
    ],
  },
  {
    title: 'In the Kitchen',
    bonus: 'SPOON',
    entries: [
      { word: 'SPOON', clue: 'You eat soup with it' },
      { word: 'PLATE', clue: 'You serve food on it' },
      { word: 'KNIFE', clue: 'You cut food with it' },
      { word: 'STOVE', clue: 'You cook on it' },
      { word: 'OVEN', clue: 'You bake in it' },
      { word: 'BOWL', clue: 'You eat cereal from it' },
      { word: 'FORK', clue: 'It has prongs for eating' },
      { word: 'CUP', clue: 'You drink from it' },
      { word: 'PAN', clue: 'You fry eggs in it' },
      { word: 'MUG', clue: 'Holds your coffee' },
      { word: 'GRILL', clue: 'Cook meat over flames' },
      { word: 'WHISK', clue: 'Tool for beating eggs' },
      { word: 'KETTLE', clue: 'It boils water for tea' },
      { word: 'APRON', clue: 'You wear it while cooking' },
    ],
  },
  {
    title: 'Weather',
    bonus: 'CLOUD',
    entries: [
      { word: 'CLOUD', clue: 'It floats and may bring rain' },
      { word: 'STORM', clue: 'Wind, rain and thunder' },
      { word: 'SUNNY', clue: 'Bright and clear sky' },
      { word: 'WINDY', clue: 'Lots of breeze' },
      { word: 'RAIN', clue: 'Water falling from the sky' },
      { word: 'SNOW', clue: 'White winter flakes' },
      { word: 'HAIL', clue: 'Ice balls from the sky' },
      { word: 'FOG', clue: 'Low cloud you can walk in' },
      { word: 'FROST', clue: 'Icy coating on cold mornings' },
      { word: 'THAW', clue: 'When ice melts' },
      { word: 'GUST', clue: 'A sudden burst of wind' },
      { word: 'CHILL', clue: 'A cold feeling in the air' },
      { word: 'THUNDER', clue: 'The boom after lightning' },
      { word: 'BREEZE', clue: 'A gentle wind' },
    ],
  },
  {
    title: 'Sports',
    bonus: 'SOCCER',
    entries: [
      { word: 'SOCCER', clue: 'Game played with a round ball and feet' },
      { word: 'TENNIS', clue: 'Racket game over a net' },
      { word: 'HOCKEY', clue: 'Game played with sticks and a puck' },
      { word: 'BOXING', clue: 'Sport with gloves and punches' },
      { word: 'RUGBY', clue: 'Rough game with an oval ball' },
      { word: 'GOLF', clue: 'Game of clubs and holes' },
      { word: 'RACE', clue: 'A contest of speed' },
      { word: 'GOAL', clue: 'Where you score in soccer' },
      { word: 'TEAM', clue: 'A group of players' },
      { word: 'NET', clue: 'Ball passes over or into it' },
      { word: 'COACH', clue: 'Person who trains the team' },
      { word: 'MEDAL', clue: 'Prize for winning' },
      { word: 'SURF', clue: 'Ride waves on a board' },
      { word: 'SKATE', clue: 'Glide on ice or wheels' },
    ],
  },
  {
    title: 'Music',
    bonus: 'GUITAR',
    entries: [
      { word: 'GUITAR', clue: 'Six-stringed instrument' },
      { word: 'PIANO', clue: 'Instrument with black and white keys' },
      { word: 'VIOLIN', clue: 'Small string instrument played with a bow' },
      { word: 'FLUTE', clue: 'Slim wind instrument' },
      { word: 'DRUM', clue: 'You hit it to keep the beat' },
      { word: 'SONG', clue: 'Music with words' },
      { word: 'BAND', clue: 'Group that plays music' },
      { word: 'NOTE', clue: 'A single musical sound' },
      { word: 'TUNE', clue: 'A melody' },
      { word: 'CHORD', clue: 'Several notes played together' },
      { word: 'OPERA', clue: 'Drama that is sung' },
      { word: 'LYRIC', clue: 'The words of a song' },
      { word: 'TEMPO', clue: 'Speed of the music' },
      { word: 'BEAT', clue: 'The rhythm you tap to' },
    ],
  },
  {
    title: 'The Body',
    bonus: 'HEART',
    entries: [
      { word: 'HEART', clue: 'It pumps your blood' },
      { word: 'BRAIN', clue: 'You think with it' },
      { word: 'LIVER', clue: 'Organ that cleans the blood' },
      { word: 'NERVE', clue: 'It carries signals in the body' },
      { word: 'ELBOW', clue: 'Joint in the middle of the arm' },
      { word: 'ANKLE', clue: 'Joint above the foot' },
      { word: 'WRIST', clue: 'Joint where your watch sits' },
      { word: 'SPINE', clue: 'Your backbone' },
      { word: 'THUMB', clue: 'The short, wide finger' },
      { word: 'CHEST', clue: 'Front of the upper body' },
      { word: 'KNEE', clue: 'Joint in the middle of the leg' },
      { word: 'BONE', clue: 'Hard part of the skeleton' },
      { word: 'LUNG', clue: 'You breathe with it' },
      { word: 'SKIN', clue: 'It covers your whole body' },
    ],
  },
  {
    title: 'At School',
    bonus: 'PENCIL',
    entries: [
      { word: 'PENCIL', clue: 'You write with it and erase it' },
      { word: 'ERASER', clue: 'It rubs out mistakes' },
      { word: 'RULER', clue: 'Tool for measuring straight lines' },
      { word: 'CHALK', clue: 'You write on a blackboard with it' },
      { word: 'BOARD', clue: 'Teacher writes on it' },
      { word: 'CLASS', clue: 'A group of students' },
      { word: 'GRADE', clue: 'A mark for your work' },
      { word: 'BOOK', clue: 'You read it to learn' },
      { word: 'EXAM', clue: 'A big test' },
      { word: 'DESK', clue: 'You sit and work at it' },
      { word: 'TUTOR', clue: 'A private teacher' },
      { word: 'STUDY', clue: 'What you do before a test' },
      { word: 'PAPER', clue: 'You write on a sheet of it' },
      { word: 'MARKER', clue: 'Thick colored pen' },
    ],
  },
  {
    title: 'In the Ocean',
    bonus: 'WHALE',
    entries: [
      { word: 'WHALE', clue: 'The largest sea animal' },
      { word: 'SHARK', clue: 'Fish with sharp teeth and a fin' },
      { word: 'CORAL', clue: 'Colorful reef builder' },
      { word: 'WAVE', clue: 'It rolls onto the shore' },
      { word: 'TIDE', clue: 'The rise and fall of the sea' },
      { word: 'SHELL', clue: 'Hard cover you find on the beach' },
      { word: 'CRAB', clue: 'It walks sideways with claws' },
      { word: 'SQUID', clue: 'Sea creature with ten arms' },
      { word: 'REEF', clue: 'Underwater ridge of coral' },
      { word: 'PEARL', clue: 'Gem that grows in an oyster' },
      { word: 'DIVER', clue: 'Person who explores underwater' },
      { word: 'EEL', clue: 'Long, snake-like fish' },
      { word: 'OCTOPUS', clue: 'Sea animal with eight arms' },
      { word: 'SEAL', clue: 'It barks and balances balls' },
      { word: 'TUNA', clue: 'Fish often found in a sandwich' },
      { word: 'SAIL', clue: 'Cloth that catches wind on a boat' },
      { word: 'FIN', clue: 'A fish steers with it' },
      { word: 'NET', clue: 'Used to catch fish' },
    ],
  },
  {
    title: 'Birds',
    bonus: 'EAGLE',
    entries: [
      { word: 'EAGLE', clue: 'Large bird of prey' },
      { word: 'ROBIN', clue: 'Small bird with a red breast' },
      { word: 'SPARROW', clue: 'Common small brown bird' },
      { word: 'CROW', clue: 'Black bird with a harsh caw' },
      { word: 'DOVE', clue: 'White bird of peace' },
      { word: 'SWAN', clue: 'Graceful white water bird' },
      { word: 'HERON', clue: 'Tall wading bird with long legs' },
      { word: 'FINCH', clue: 'Small songbird' },
      { word: 'RAVEN', clue: 'Big black bird' },
      { word: 'STORK', clue: 'Long-legged bird said to bring babies' },
      { word: 'PARROT', clue: 'Colorful bird that can talk' },
      { word: 'DUCK', clue: 'Water bird that quacks' },
      { word: 'GOOSE', clue: 'Larger relative of the duck' },
      { word: 'HAWK', clue: 'Sharp-eyed hunting bird' },
    ],
  },
  {
    title: 'Vegetables',
    bonus: 'CARROT',
    entries: [
      { word: 'CARROT', clue: 'Orange root rabbits love' },
      { word: 'ONION', clue: 'It can make you cry' },
      { word: 'POTATO', clue: 'Made into chips and fries' },
      { word: 'CELERY', clue: 'Long, crunchy green stalk' },
      { word: 'BEAN', clue: 'It grows in a pod' },
      { word: 'CORN', clue: 'Yellow kernels on a cob' },
      { word: 'LEEK', clue: 'Long onion-like vegetable' },
      { word: 'KALE', clue: 'Leafy green superfood' },
      { word: 'BEET', clue: 'Deep red root vegetable' },
      { word: 'OKRA', clue: 'Green pod used in gumbo' },
      { word: 'SPINACH', clue: "Popeye's leafy green" },
      { word: 'TURNIP', clue: 'White-and-purple root vegetable' },
      { word: 'RADISH', clue: 'Small, spicy red root' },
      { word: 'PEA', clue: 'Tiny green ball in a pod' },
    ],
  },
  {
    title: 'Colors & Shapes',
    bonus: 'PURPLE',
    entries: [
      { word: 'PURPLE', clue: 'Color of grapes' },
      { word: 'ORANGE', clue: 'Color of a carrot' },
      { word: 'GREEN', clue: 'Color of grass' },
      { word: 'BROWN', clue: 'Color of chocolate' },
      { word: 'BLACK', clue: 'Color of the night sky' },
      { word: 'WHITE', clue: 'Color of snow' },
      { word: 'CIRCLE', clue: 'A perfectly round shape' },
      { word: 'SQUARE', clue: 'Shape with four equal sides' },
      { word: 'OVAL', clue: 'Egg-shaped' },
      { word: 'STAR', clue: 'Five-pointed shape' },
      { word: 'CONE', clue: 'Shape of an ice-cream holder' },
      { word: 'CUBE', clue: 'A 3-D square block' },
      { word: 'PINK', clue: 'Light red color' },
      { word: 'HEART', clue: 'Love-shaped symbol' },
    ],
  },
  {
    title: 'Jobs',
    bonus: 'DOCTOR',
    entries: [
      { word: 'DOCTOR', clue: 'They help sick people get well' },
      { word: 'NURSE', clue: 'They care for patients' },
      { word: 'PILOT', clue: 'They fly planes' },
      { word: 'CHEF', clue: 'They cook in a restaurant' },
      { word: 'BAKER', clue: 'They make bread and cakes' },
      { word: 'FARMER', clue: 'They grow crops and raise animals' },
      { word: 'ACTOR', clue: 'They perform in films' },
      { word: 'JUDGE', clue: 'They decide cases in court' },
      { word: 'LAWYER', clue: 'They argue cases in court' },
      { word: 'ARTIST', clue: 'They paint and draw' },
      { word: 'WRITER', clue: 'They write books' },
      { word: 'SINGER', clue: 'They perform songs' },
      { word: 'TAILOR', clue: 'They make and fix clothes' },
      { word: 'CLERK', clue: 'They work at a shop counter' },
      { word: 'COOK', clue: 'They prepare meals' },
      { word: 'VET', clue: 'Animal doctor' },
      { word: 'POET', clue: 'They write verse' },
      { word: 'MAID', clue: 'They clean hotel rooms' },
    ],
  },
  {
    title: 'Travel',
    bonus: 'TICKET',
    entries: [
      { word: 'TICKET', clue: 'You need it to board' },
      { word: 'HOTEL', clue: 'Where you sleep on a trip' },
      { word: 'TRAIN', clue: 'It runs on rails' },
      { word: 'PLANE', clue: 'It flies in the sky' },
      { word: 'CRUISE', clue: 'A holiday on a big ship' },
      { word: 'VISA', clue: 'Permission to enter a country' },
      { word: 'TOUR', clue: 'A guided trip around sights' },
      { word: 'GUIDE', clue: 'Person who shows you around' },
      { word: 'ROUTE', clue: 'The path you take' },
      { word: 'TAXI', clue: 'Car you pay to ride in' },
      { word: 'FLIGHT', clue: 'A journey by air' },
      { word: 'MAP', clue: 'It shows you the way' },
      { word: 'BEACH', clue: 'Sandy holiday spot' },
      { word: 'AIRPORT', clue: 'Where planes take off and land' },
    ],
  },
  {
    title: 'Clothing',
    bonus: 'JACKET',
    entries: [
      { word: 'JACKET', clue: 'Light coat for your top half' },
      { word: 'SHIRT', clue: 'Top with buttons and a collar' },
      { word: 'PANTS', clue: 'You wear them on your legs' },
      { word: 'DRESS', clue: 'One-piece outfit' },
      { word: 'SKIRT', clue: 'It hangs from the waist' },
      { word: 'SHOES', clue: 'You wear them on your feet' },
      { word: 'SOCKS', clue: 'They go on before shoes' },
      { word: 'COAT', clue: 'Heavy outer garment' },
      { word: 'GLOVE', clue: 'It covers your hand' },
      { word: 'SCARF', clue: 'You wrap it around your neck' },
      { word: 'BELT', clue: 'It holds up your pants' },
      { word: 'JEANS', clue: 'Denim trousers' },
      { word: 'BOOT', clue: 'Tall, sturdy shoe' },
      { word: 'HAT', clue: 'You wear it on your head' },
    ],
  },
  {
    title: 'House & Home',
    bonus: 'WINDOW',
    entries: [
      { word: 'WINDOW', clue: 'You look outside through it' },
      { word: 'TABLE', clue: 'You eat at it' },
      { word: 'CHAIR', clue: 'You sit on it' },
      { word: 'COUCH', clue: 'Long, soft seat for the living room' },
      { word: 'LAMP', clue: 'It gives light on a desk' },
      { word: 'DOOR', clue: 'You open it to enter' },
      { word: 'WALL', clue: 'It divides the rooms' },
      { word: 'ROOF', clue: 'It covers the house on top' },
      { word: 'FLOOR', clue: 'You walk on it' },
      { word: 'STAIRS', clue: 'You climb them between floors' },
      { word: 'SHELF', clue: 'You put books on it' },
      { word: 'MIRROR', clue: 'You see your reflection in it' },
      { word: 'SINK', clue: 'You wash your hands in it' },
      { word: 'CLOSET', clue: 'Small room for storing clothes' },
    ],
  },
  {
    title: 'Nature',
    bonus: 'FOREST',
    entries: [
      { word: 'FOREST', clue: 'A large area full of trees' },
      { word: 'RIVER', clue: 'Water flowing to the sea' },
      { word: 'VALLEY', clue: 'Low land between hills' },
      { word: 'DESERT', clue: 'Dry, sandy region' },
      { word: 'MEADOW', clue: 'Grassy field with flowers' },
      { word: 'CANYON', clue: 'Deep gorge with steep sides' },
      { word: 'ISLAND', clue: 'Land surrounded by water' },
      { word: 'HILL', clue: 'A small mountain' },
      { word: 'LAKE', clue: 'A large body of still water' },
      { word: 'CAVE', clue: 'A hollow in a hillside' },
      { word: 'CLIFF', clue: 'A steep rock face' },
      { word: 'STONE', clue: 'A small rock' },
      { word: 'TREE', clue: 'It has a trunk and leaves' },
      { word: 'FERN', clue: 'Leafy plant with no flowers' },
    ],
  },
  {
    title: 'Food & Meals',
    bonus: 'CHEESE',
    entries: [
      { word: 'CHEESE', clue: 'Dairy food made from milk' },
      { word: 'BUTTER', clue: 'You spread it on toast' },
      { word: 'BREAD', clue: 'Made from flour and baked' },
      { word: 'PASTA', clue: 'Spaghetti is a type of it' },
      { word: 'PIZZA', clue: 'Round dish with cheese and toppings' },
      { word: 'SALAD', clue: 'Bowl of fresh vegetables' },
      { word: 'SOUP', clue: 'You eat it with a spoon' },
      { word: 'RICE', clue: 'Small white grains' },
      { word: 'MEAT', clue: 'Beef and chicken are types of it' },
      { word: 'CAKE', clue: 'Sweet treat for a birthday' },
      { word: 'HONEY', clue: 'Sweet food made by bees' },
      { word: 'STEAK', clue: 'A thick cut of beef' },
      { word: 'NOODLE', clue: 'Long strand in your soup' },
      { word: 'TOAST', clue: 'Browned bread' },
    ],
  },
  {
    title: 'Technology',
    bonus: 'LAPTOP',
    entries: [
      { word: 'LAPTOP', clue: 'Portable computer' },
      { word: 'SCREEN', clue: 'You watch it on a device' },
      { word: 'MOUSE', clue: 'You click with it' },
      { word: 'PHONE', clue: 'You make calls with it' },
      { word: 'EMAIL', clue: 'Electronic message' },
      { word: 'CABLE', clue: 'Wire that connects devices' },
      { word: 'ROBOT', clue: 'A machine that can move on its own' },
      { word: 'PIXEL', clue: 'Tiny dot on a screen' },
      { word: 'MODEM', clue: 'Box that connects you to the internet' },
      { word: 'ROUTER', clue: 'It shares the Wi-Fi signal' },
      { word: 'CHIP', clue: 'Tiny computer part' },
      { word: 'DATA', clue: 'Stored information' },
      { word: 'CODE', clue: 'Instructions for a program' },
      { word: 'DRONE', clue: 'Small flying machine with a camera' },
    ],
  },
  {
    title: 'Camping',
    bonus: 'LANTERN',
    entries: [
      { word: 'LANTERN', clue: 'Portable light for the dark' },
      { word: 'TENT', clue: 'You sleep in it outdoors' },
      { word: 'FIRE', clue: 'You roast marshmallows over it' },
      { word: 'ROPE', clue: 'You tie things with it' },
      { word: 'TORCH', clue: 'Handheld flashlight' },
      { word: 'STOVE', clue: 'Small camp cooker' },
      { word: 'TRAIL', clue: 'A path through the woods' },
      { word: 'HIKE', clue: 'A long walk in nature' },
      { word: 'MAP', clue: 'It shows the trails' },
      { word: 'AXE', clue: 'You chop wood with it' },
      { word: 'CABIN', clue: 'Small wooden hut' },
      { word: 'WOODS', clue: 'A small forest' },
      { word: 'KNIFE', clue: 'Handy cutting tool' },
      { word: 'COMPASS', clue: 'It points north' },
    ],
  },
  {
    title: 'The Beach',
    bonus: 'SHELL',
    entries: [
      { word: 'SHELL', clue: 'You collect it in the sand' },
      { word: 'SAND', clue: 'It covers the beach' },
      { word: 'WAVE', clue: 'It crashes on the shore' },
      { word: 'TOWEL', clue: 'You lie on it at the beach' },
      { word: 'SURF', clue: 'Ride the waves' },
      { word: 'CRAB', clue: 'It scuttles on the sand' },
      { word: 'TIDE', clue: 'The sea rises and falls with it' },
      { word: 'PALM', clue: 'Tropical beach tree' },
      { word: 'KITE', clue: 'You fly it in the wind' },
      { word: 'SANDAL', clue: 'Open summer shoe' },
      { word: 'CORAL', clue: 'Colorful sea growth' },
      { word: 'BOAT', clue: 'It floats on the water' },
      { word: 'DUNE', clue: 'A hill of sand' },
      { word: 'SHORE', clue: 'Where the land meets the sea' },
    ],
  },
  {
    title: 'Winter',
    bonus: 'FROST',
    entries: [
      { word: 'FROST', clue: 'Icy coating on cold mornings' },
      { word: 'SNOW', clue: 'White flakes that fall in winter' },
      { word: 'SLED', clue: 'You ride it down a snowy hill' },
      { word: 'SCARF', clue: 'You wrap it around your neck' },
      { word: 'GLOVE', clue: 'It keeps your hand warm' },
      { word: 'SKATE', clue: 'Glide across the ice' },
      { word: 'COCOA', clue: 'Warm chocolate drink' },
      { word: 'CHILL', clue: 'A cold feeling' },
      { word: 'FREEZE', clue: 'Turn to ice' },
      { word: 'STORM', clue: 'A blizzard is a snow ___' },
      { word: 'IGLOO', clue: 'House made of ice blocks' },
      { word: 'PARKA', clue: 'Warm hooded coat' },
      { word: 'SLEET', clue: 'Rain mixed with snow' },
      { word: 'FLAKE', clue: 'A single piece of snow' },
      { word: 'ICE', clue: 'Frozen water' },
      { word: 'SKI', clue: 'Slide down a snowy slope' },
      { word: 'COLD', clue: 'Low in temperature' },
      { word: 'WIND', clue: 'Moving air' },
    ],
  },
  {
    title: 'In the Garden',
    bonus: 'FLOWER',
    entries: [
      { word: 'FLOWER', clue: 'A rose or a tulip' },
      { word: 'PETAL', clue: 'Colorful part of a flower' },
      { word: 'ROOT', clue: 'It grows underground' },
      { word: 'SEED', clue: 'You plant it to grow a plant' },
      { word: 'LEAF', clue: 'Green part of a plant' },
      { word: 'STEM', clue: 'It holds up the flower' },
      { word: 'SOIL', clue: 'The dirt plants grow in' },
      { word: 'ROSE', clue: 'Flower with thorns' },
      { word: 'TULIP', clue: 'Cup-shaped spring flower' },
      { word: 'DAISY', clue: 'White flower with a yellow center' },
      { word: 'HOSE', clue: 'You water plants with it' },
      { word: 'RAKE', clue: 'Tool for gathering leaves' },
      { word: 'WEED', clue: 'Unwanted plant' },
      { word: 'BLOOM', clue: 'What a flower does in spring' },
    ],
  },
  {
    title: 'Insects',
    bonus: 'SPIDER',
    entries: [
      { word: 'SPIDER', clue: 'It spins a web' },
      { word: 'BEETLE', clue: 'Hard-shelled crawling bug' },
      { word: 'CRICKET', clue: 'It chirps at night' },
      { word: 'HORNET', clue: 'A large, stinging wasp' },
      { word: 'LOCUST', clue: 'Swarming grasshopper' },
      { word: 'MANTIS', clue: 'Bug that prays with its front legs' },
      { word: 'ANT', clue: 'Tiny insect that lives in colonies' },
      { word: 'BEE', clue: 'It makes honey' },
      { word: 'WASP', clue: 'Stinging insect with a thin waist' },
      { word: 'MOTH', clue: "Butterfly's night-flying cousin" },
      { word: 'FLY', clue: 'It buzzes around food' },
      { word: 'GNAT', clue: 'Tiny biting fly' },
      { word: 'FLEA', clue: 'Tiny jumping pest on pets' },
      { word: 'APHID', clue: 'Tiny insect that harms plants' },
    ],
  },
  {
    title: 'Tools',
    bonus: 'HAMMER',
    entries: [
      { word: 'HAMMER', clue: 'You hit nails with it' },
      { word: 'WRENCH', clue: 'You tighten bolts with it' },
      { word: 'PLIERS', clue: 'You grip things with them' },
      { word: 'CHISEL', clue: 'Tool for carving wood' },
      { word: 'DRILL', clue: 'It makes holes' },
      { word: 'SAW', clue: 'You cut wood with it' },
      { word: 'NAIL', clue: 'You hammer it in' },
      { word: 'SCREW', clue: 'It twists into wood' },
      { word: 'LEVEL', clue: 'It checks if things are flat' },
      { word: 'CLAMP', clue: 'It holds things tight' },
      { word: 'FILE', clue: 'Tool for smoothing edges' },
      { word: 'TAPE', clue: 'A measuring ___' },
      { word: 'BOLT', clue: 'Metal pin fastened with a nut' },
      { word: 'SANDER', clue: 'It smooths a surface' },
    ],
  },
  {
    title: 'Emotions',
    bonus: 'HAPPY',
    entries: [
      { word: 'HAPPY', clue: 'Feeling full of joy' },
      { word: 'ANGRY', clue: 'Feeling mad' },
      { word: 'PROUD', clue: 'Pleased with your achievement' },
      { word: 'CALM', clue: 'Peaceful and relaxed' },
      { word: 'BORED', clue: 'Nothing fun to do' },
      { word: 'SCARED', clue: 'Feeling afraid' },
      { word: 'LONELY', clue: 'Feeling all alone' },
      { word: 'BRAVE', clue: 'Not afraid of danger' },
      { word: 'TENSE', clue: 'Nervous and on edge' },
      { word: 'MERRY', clue: 'Cheerful and jolly' },
      { word: 'GRUMPY', clue: 'In a bad mood' },
      { word: 'JOY', clue: 'A feeling of great happiness' },
      { word: 'FEAR', clue: 'The feeling of being scared' },
      { word: 'HOPE', clue: 'Wishing for something good' },
    ],
  },
  {
    title: 'Drinks',
    bonus: 'COFFEE',
    entries: [
      { word: 'COFFEE', clue: 'Hot drink that wakes you up' },
      { word: 'WATER', clue: 'Clear, plain drink' },
      { word: 'JUICE', clue: 'Drink squeezed from fruit' },
      { word: 'MILK', clue: 'White drink from a cow' },
      { word: 'COCOA', clue: 'Warm chocolate drink' },
      { word: 'SODA', clue: 'Fizzy sweet drink' },
      { word: 'CIDER', clue: 'Drink made from apples' },
      { word: 'LATTE', clue: 'Coffee with steamed milk' },
      { word: 'SHAKE', clue: 'Thick blended milk drink' },
      { word: 'COLA', clue: 'Dark, fizzy soft drink' },
      { word: 'WINE', clue: 'Drink made from grapes' },
      { word: 'PUNCH', clue: 'Mixed fruity party drink' },
      { word: 'MOCHA', clue: 'Coffee with chocolate' },
      { word: 'TEA', clue: 'Drink made by steeping leaves' },
    ],
  },
  {
    title: 'Countries',
    bonus: 'BRAZIL',
    entries: [
      { word: 'BRAZIL', clue: 'Largest country in South America' },
      { word: 'FRANCE', clue: 'Country with the Eiffel Tower' },
      { word: 'CANADA', clue: 'Country north of the USA' },
      { word: 'NORWAY', clue: 'Country famous for fjords' },
      { word: 'JAPAN', clue: 'Land of the rising sun' },
      { word: 'CHINA', clue: 'Country with the Great Wall' },
      { word: 'INDIA', clue: 'Country of the Taj Mahal' },
      { word: 'SPAIN', clue: 'Country known for flamenco' },
      { word: 'EGYPT', clue: 'Country of the pyramids' },
      { word: 'ITALY', clue: 'Boot-shaped European country' },
      { word: 'KENYA', clue: 'African country known for safaris' },
      { word: 'CHILE', clue: 'Long, thin South American country' },
      { word: 'PERU', clue: 'Home of Machu Picchu' },
      { word: 'NEPAL', clue: 'Country with Mount Everest' },
    ],
  },
  {
    title: 'Time & Calendar',
    bonus: 'MINUTE',
    entries: [
      { word: 'MINUTE', clue: 'Sixty seconds' },
      { word: 'SECOND', clue: 'The smallest unit on a clock face' },
      { word: 'HOUR', clue: 'Sixty minutes' },
      { word: 'WEEK', clue: 'Seven days' },
      { word: 'MONTH', clue: 'About thirty days' },
      { word: 'YEAR', clue: 'Twelve months' },
      { word: 'CLOCK', clue: 'It tells the time' },
      { word: 'ALARM', clue: 'It wakes you up' },
      { word: 'NOON', clue: 'Twelve in the middle of the day' },
      { word: 'DAWN', clue: 'When the sun rises' },
      { word: 'DUSK', clue: 'When the sun sets' },
      { word: 'TODAY', clue: 'This very day' },
      { word: 'MONDAY', clue: 'First day of the work week' },
      { word: 'NIGHT', clue: 'The dark part of the day' },
    ],
  },
];
