/**
 * Mirrors the in-app Connections (Word Game) puzzles into a static data file the
 * admin web can import to show answers/categories.
 *
 * Run:  npx tsx scripts/genWordGameData.ts
 * Output: ../admin-web/src/data/connectionsPuzzles.ts
 */
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getAllPuzzles } from '../src/data/connectionsPuzzles';

const puzzles = getAllPuzzles();

const header = `// AUTO-GENERATED by scripts/genWordGameData.ts — do not edit by hand.\n// Connections (Word Game) puzzles, mirrored for the admin web.\n`;
const types = `export type ConnectionsColor = 'yellow' | 'green' | 'blue' | 'purple';
export interface ConnectionsGroup {
  label: string;
  words: string[];
  color: ConnectionsColor;
}
export interface ConnectionsPuzzle {
  id: number;
  groups: ConnectionsGroup[];
}
`;
const body = `export const CONNECTIONS_PUZZLES: ConnectionsPuzzle[] = ${JSON.stringify(puzzles, null, 2)};\n`;
const full = header + types + '\n' + body;

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = resolve(__dirname, '../../admin-web/src/data/connectionsPuzzles.ts');
const dir = dirname(out);
if (existsSync(resolve(dir, '..'))) {
  mkdirSync(dir, { recursive: true });
  writeFileSync(out, full);
  console.log(`Wrote ${out} (${puzzles.length} puzzles)`);
} else {
  console.log(`Skipped: ${dir} parent missing`);
}
