// AUTO-GENERATED by scripts/genCrossword.ts — do not edit by hand.
// 7x7 mini crosswords for the Crossword mini-game.
export type CrosswordDir = 'across' | 'down';
export interface CrosswordClue {
  number: number;
  direction: CrosswordDir;
  clue: string;
  answer: string;
  row: number;
  col: number;
}
export interface CrosswordPuzzle {
  id: number;
  title: string;
  size: number;
  solution: (string | null)[][];
  clues: CrosswordClue[];
  /** Hidden bonus word — not part of the grid. Players guess it for extra points. */
  bonusWord: string;
  /** Subtle hint shown for the hidden bonus word. */
  bonusHint: string;
}

export const CROSSWORD_PUZZLES: CrosswordPuzzle[] = [
  {
    "id": 1,
    "title": "Animals",
    "size": 7,
    "solution": [
      [
        "P",
        "A",
        "N",
        "D",
        "A",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        "S",
        null
      ],
      [
        null,
        "R",
        null,
        "E",
        null,
        "H",
        null
      ],
      [
        null,
        "H",
        "O",
        "R",
        "S",
        "E",
        null
      ],
      [
        null,
        "I",
        null,
        null,
        null,
        "E",
        null
      ],
      [
        null,
        "N",
        null,
        null,
        null,
        "P",
        null
      ],
      [
        "G",
        "O",
        "A",
        "T",
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Black-and-white bamboo eater",
        "answer": "PANDA",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Forest animal with antlers",
        "answer": "DEER",
        "row": 0,
        "col": 3
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Wool-giving farm animal",
        "answer": "SHEEP",
        "row": 1,
        "col": 5
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Thick-skinned beast with a horn",
        "answer": "RHINO",
        "row": 2,
        "col": 1
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Animal you can ride",
        "answer": "HORSE",
        "row": 3,
        "col": 1
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Horned animal that climbs",
        "answer": "GOAT",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "TIGER",
    "bonusHint": "Big striped cat"
  },
  {
    "id": 2,
    "title": "Fruits",
    "size": 7,
    "solution": [
      [
        "P",
        null,
        "A",
        "P",
        "P",
        "L",
        "E"
      ],
      [
        "E",
        null,
        null,
        null,
        "E",
        null,
        null
      ],
      [
        "A",
        null,
        "B",
        null,
        "A",
        null,
        null
      ],
      [
        "C",
        "H",
        "E",
        "R",
        "R",
        "Y",
        null
      ],
      [
        "H",
        null,
        "R",
        null,
        null,
        null,
        null
      ],
      [
        null,
        "O",
        "R",
        "A",
        "N",
        "G",
        "E"
      ],
      [
        null,
        null,
        "Y",
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Fuzzy orange fruit",
        "answer": "PEACH",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Keeps the doctor away",
        "answer": "APPLE",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Bell-shaped fruit",
        "answer": "PEAR",
        "row": 0,
        "col": 4
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Small soft fruit, like a straw-",
        "answer": "BERRY",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Small red fruit with a stone",
        "answer": "CHERRY",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Round citrus, same name as a color",
        "answer": "ORANGE",
        "row": 5,
        "col": 1
      }
    ],
    "bonusWord": "BANANA",
    "bonusHint": "Long yellow fruit"
  },
  {
    "id": 3,
    "title": "Space",
    "size": 7,
    "solution": [
      [
        null,
        "P",
        "L",
        "A",
        "N",
        "E",
        "T"
      ],
      [
        "C",
        null,
        null,
        "L",
        null,
        null,
        null
      ],
      [
        "O",
        null,
        null,
        "I",
        null,
        "O",
        null
      ],
      [
        "M",
        "E",
        "T",
        "E",
        "O",
        "R",
        null
      ],
      [
        "E",
        null,
        null,
        "N",
        null,
        "B",
        null
      ],
      [
        "T",
        null,
        null,
        null,
        null,
        "I",
        null
      ],
      [
        null,
        null,
        "E",
        "A",
        "R",
        "T",
        "H"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Earth is one",
        "answer": "PLANET",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Imagined being from space",
        "answer": "ALIEN",
        "row": 0,
        "col": 3
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Icy body with a glowing tail",
        "answer": "COMET",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Path around the sun",
        "answer": "ORBIT",
        "row": 2,
        "col": 5
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Shooting star",
        "answer": "METEOR",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "The planet we live on",
        "answer": "EARTH",
        "row": 6,
        "col": 2
      }
    ],
    "bonusWord": "ROCKET",
    "bonusHint": "It launches into space"
  },
  {
    "id": 4,
    "title": "In the Kitchen",
    "size": 7,
    "solution": [
      [
        "F",
        null,
        "M",
        "U",
        "G",
        null,
        null
      ],
      [
        "O",
        null,
        null,
        null,
        "R",
        null,
        null
      ],
      [
        "R",
        null,
        "S",
        null,
        "I",
        null,
        null
      ],
      [
        "K",
        "E",
        "T",
        "T",
        "L",
        "E",
        null
      ],
      [
        null,
        null,
        "O",
        null,
        "L",
        null,
        null
      ],
      [
        null,
        null,
        "V",
        null,
        null,
        null,
        null
      ],
      [
        "O",
        "V",
        "E",
        "N",
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "It has prongs for eating",
        "answer": "FORK",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Holds your coffee",
        "answer": "MUG",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Cook meat over flames",
        "answer": "GRILL",
        "row": 0,
        "col": 4
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "You cook on it",
        "answer": "STOVE",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "It boils water for tea",
        "answer": "KETTLE",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "You bake in it",
        "answer": "OVEN",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "SPOON",
    "bonusHint": "You eat soup with it"
  },
  {
    "id": 5,
    "title": "Weather",
    "size": 7,
    "solution": [
      [
        null,
        "S",
        "N",
        "O",
        "W",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "I",
        null,
        null
      ],
      [
        "S",
        null,
        "S",
        null,
        "N",
        null,
        "F"
      ],
      [
        "T",
        "H",
        "U",
        "N",
        "D",
        "E",
        "R"
      ],
      [
        "O",
        null,
        "N",
        null,
        "Y",
        null,
        "O"
      ],
      [
        "R",
        null,
        "N",
        null,
        null,
        null,
        "S"
      ],
      [
        "M",
        null,
        "Y",
        null,
        null,
        null,
        "T"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "White winter flakes",
        "answer": "SNOW",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Lots of breeze",
        "answer": "WINDY",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Wind, rain and thunder",
        "answer": "STORM",
        "row": 2,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Bright and clear sky",
        "answer": "SUNNY",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Icy coating on cold mornings",
        "answer": "FROST",
        "row": 2,
        "col": 6
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "The boom after lightning",
        "answer": "THUNDER",
        "row": 3,
        "col": 0
      }
    ],
    "bonusWord": "CLOUD",
    "bonusHint": "It floats and may bring rain"
  },
  {
    "id": 6,
    "title": "Sports",
    "size": 7,
    "solution": [
      [
        null,
        "R",
        null,
        null,
        "B",
        null,
        null
      ],
      [
        null,
        "A",
        null,
        "G",
        "O",
        "A",
        "L"
      ],
      [
        null,
        "C",
        null,
        null,
        "X",
        null,
        null
      ],
      [
        "T",
        "E",
        "N",
        "N",
        "I",
        "S",
        null
      ],
      [
        "E",
        null,
        null,
        null,
        "N",
        null,
        null
      ],
      [
        "A",
        null,
        "R",
        "U",
        "G",
        "B",
        "Y"
      ],
      [
        "M",
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "A contest of speed",
        "answer": "RACE",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Sport with gloves and punches",
        "answer": "BOXING",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Where you score in soccer",
        "answer": "GOAL",
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Racket game over a net",
        "answer": "TENNIS",
        "row": 3,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "A group of players",
        "answer": "TEAM",
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Rough game with an oval ball",
        "answer": "RUGBY",
        "row": 5,
        "col": 2
      }
    ],
    "bonusWord": "SOCCER",
    "bonusHint": "Game played with a round ball and feet"
  },
  {
    "id": 7,
    "title": "Music",
    "size": 7,
    "solution": [
      [
        "F",
        "L",
        "U",
        "T",
        "E",
        null,
        null
      ],
      [
        null,
        "Y",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "R",
        null,
        null,
        "P",
        null,
        null
      ],
      [
        "V",
        "I",
        "O",
        "L",
        "I",
        "N",
        null
      ],
      [
        null,
        "C",
        null,
        null,
        "A",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "N",
        null,
        null
      ],
      [
        "T",
        "E",
        "M",
        "P",
        "O",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Slim wind instrument",
        "answer": "FLUTE",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "The words of a song",
        "answer": "LYRIC",
        "row": 0,
        "col": 1
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Instrument with black and white keys",
        "answer": "PIANO",
        "row": 2,
        "col": 4
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Small string instrument played with a bow",
        "answer": "VIOLIN",
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Speed of the music",
        "answer": "TEMPO",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "GUITAR",
    "bonusHint": "Six-stringed instrument"
  },
  {
    "id": 8,
    "title": "The Body",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        null,
        "B",
        "O",
        "N",
        "E"
      ],
      [
        null,
        "R",
        null,
        "R",
        null,
        null,
        null
      ],
      [
        null,
        "I",
        null,
        "A",
        null,
        "N",
        null
      ],
      [
        null,
        "S",
        "P",
        "I",
        "N",
        "E",
        null
      ],
      [
        null,
        "T",
        null,
        "N",
        null,
        "R",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "V",
        null
      ],
      [
        null,
        null,
        "L",
        "I",
        "V",
        "E",
        "R"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Joint where your watch sits",
        "answer": "WRIST",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Hard part of the skeleton",
        "answer": "BONE",
        "row": 0,
        "col": 3
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You think with it",
        "answer": "BRAIN",
        "row": 0,
        "col": 3
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "It carries signals in the body",
        "answer": "NERVE",
        "row": 2,
        "col": 5
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Your backbone",
        "answer": "SPINE",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Organ that cleans the blood",
        "answer": "LIVER",
        "row": 6,
        "col": 2
      }
    ],
    "bonusWord": "HEART",
    "bonusHint": "It pumps your blood"
  },
  {
    "id": 9,
    "title": "At School",
    "size": 7,
    "solution": [
      [
        "R",
        null,
        null,
        null,
        null,
        "B",
        null
      ],
      [
        "U",
        null,
        null,
        "B",
        "O",
        "O",
        "K"
      ],
      [
        "L",
        null,
        "P",
        null,
        null,
        "A",
        null
      ],
      [
        "E",
        "R",
        "A",
        "S",
        "E",
        "R",
        null
      ],
      [
        "R",
        null,
        "P",
        null,
        null,
        "D",
        null
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        null,
        null
      ],
      [
        null,
        "G",
        "R",
        "A",
        "D",
        "E",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Tool for measuring straight lines",
        "answer": "RULER",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Teacher writes on it",
        "answer": "BOARD",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "You read it to learn",
        "answer": "BOOK",
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "You write on a sheet of it",
        "answer": "PAPER",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "It rubs out mistakes",
        "answer": "ERASER",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "A mark for your work",
        "answer": "GRADE",
        "row": 6,
        "col": 1
      }
    ],
    "bonusWord": "PENCIL",
    "bonusHint": "You write with it and erase it"
  },
  {
    "id": 10,
    "title": "In the Ocean",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "T",
        "U",
        "N",
        "A",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        null,
        null
      ],
      [
        "O",
        "C",
        "T",
        "O",
        "P",
        "U",
        "S"
      ],
      [
        null,
        "R",
        null,
        null,
        null,
        null,
        "A"
      ],
      [
        "W",
        "A",
        "V",
        "E",
        null,
        null,
        "I"
      ],
      [
        null,
        "B",
        null,
        null,
        "E",
        "E",
        "L"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Fish often found in a sandwich",
        "answer": "TUNA",
        "row": 1,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Used to catch fish",
        "answer": "NET",
        "row": 1,
        "col": 2
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Sea animal with eight arms",
        "answer": "OCTOPUS",
        "row": 3,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "It walks sideways with claws",
        "answer": "CRAB",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Cloth that catches wind on a boat",
        "answer": "SAIL",
        "row": 3,
        "col": 6
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "It rolls onto the shore",
        "answer": "WAVE",
        "row": 5,
        "col": 0
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Long, snake-like fish",
        "answer": "EEL",
        "row": 6,
        "col": 4
      }
    ],
    "bonusWord": "WHALE",
    "bonusHint": "The largest sea animal"
  },
  {
    "id": 11,
    "title": "Birds",
    "size": 7,
    "solution": [
      [
        "G",
        null,
        null,
        null,
        "S",
        null,
        null
      ],
      [
        "O",
        null,
        null,
        null,
        "T",
        null,
        "H"
      ],
      [
        "O",
        null,
        "R",
        null,
        "O",
        null,
        "A"
      ],
      [
        "S",
        "P",
        "A",
        "R",
        "R",
        "O",
        "W"
      ],
      [
        "E",
        null,
        "V",
        null,
        "K",
        null,
        "K"
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        null,
        null
      ],
      [
        "F",
        "I",
        "N",
        "C",
        "H",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Larger relative of the duck",
        "answer": "GOOSE",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Long-legged bird said to bring babies",
        "answer": "STORK",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Sharp-eyed hunting bird",
        "answer": "HAWK",
        "row": 1,
        "col": 6
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Big black bird",
        "answer": "RAVEN",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Common small brown bird",
        "answer": "SPARROW",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Small songbird",
        "answer": "FINCH",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "EAGLE",
    "bonusHint": "Large bird of prey"
  },
  {
    "id": 12,
    "title": "Vegetables",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        "B",
        "E",
        "E",
        "T"
      ],
      [
        "K",
        "A",
        "L",
        "E",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "A",
        null,
        null,
        null
      ],
      [
        "S",
        "P",
        "I",
        "N",
        "A",
        "C",
        "H"
      ],
      [
        null,
        "E",
        null,
        null,
        null,
        "O",
        null
      ],
      [
        null,
        "A",
        null,
        "O",
        "K",
        "R",
        "A"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "N",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Deep red root vegetable",
        "answer": "BEET",
        "row": 0,
        "col": 3
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "It grows in a pod",
        "answer": "BEAN",
        "row": 0,
        "col": 3
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Leafy green superfood",
        "answer": "KALE",
        "row": 1,
        "col": 0
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Popeye's leafy green",
        "answer": "SPINACH",
        "row": 3,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Tiny green ball in a pod",
        "answer": "PEA",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Yellow kernels on a cob",
        "answer": "CORN",
        "row": 3,
        "col": 5
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Green pod used in gumbo",
        "answer": "OKRA",
        "row": 5,
        "col": 3
      }
    ],
    "bonusWord": "CARROT",
    "bonusHint": "Orange root rabbits love"
  },
  {
    "id": 13,
    "title": "Colors & Shapes",
    "size": 7,
    "solution": [
      [
        "B",
        "R",
        "O",
        "W",
        "N",
        null,
        null
      ],
      [
        "L",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "A",
        null,
        "G",
        null,
        null,
        "H",
        null
      ],
      [
        "C",
        "I",
        "R",
        "C",
        "L",
        "E",
        null
      ],
      [
        "K",
        null,
        "E",
        null,
        null,
        "A",
        null
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        "R",
        null
      ],
      [
        "P",
        "I",
        "N",
        "K",
        null,
        "T",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Color of chocolate",
        "answer": "BROWN",
        "row": 0,
        "col": 0
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "Color of the night sky",
        "answer": "BLACK",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Color of grass",
        "answer": "GREEN",
        "row": 2,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Love-shaped symbol",
        "answer": "HEART",
        "row": 2,
        "col": 5
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "A perfectly round shape",
        "answer": "CIRCLE",
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Light red color",
        "answer": "PINK",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "PURPLE",
    "bonusHint": "Color of grapes"
  },
  {
    "id": 14,
    "title": "Jobs",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        "J",
        null,
        null,
        "V"
      ],
      [
        null,
        null,
        "N",
        "U",
        "R",
        "S",
        "E"
      ],
      [
        null,
        "P",
        null,
        "D",
        null,
        null,
        "T"
      ],
      [
        "S",
        "I",
        "N",
        "G",
        "E",
        "R",
        null
      ],
      [
        null,
        "L",
        null,
        "E",
        null,
        null,
        null
      ],
      [
        null,
        "O",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "T",
        "A",
        "I",
        "L",
        "O",
        "R"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "They decide cases in court",
        "answer": "JUDGE",
        "row": 0,
        "col": 3
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Animal doctor",
        "answer": "VET",
        "row": 0,
        "col": 6
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "They care for patients",
        "answer": "NURSE",
        "row": 1,
        "col": 2
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "They fly planes",
        "answer": "PILOT",
        "row": 2,
        "col": 1
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "They perform songs",
        "answer": "SINGER",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "They make and fix clothes",
        "answer": "TAILOR",
        "row": 6,
        "col": 1
      }
    ],
    "bonusWord": "DOCTOR",
    "bonusHint": "They help sick people get well"
  },
  {
    "id": 15,
    "title": "Travel",
    "size": 7,
    "solution": [
      [
        "V",
        null,
        "T",
        "R",
        "A",
        "I",
        "N"
      ],
      [
        "I",
        null,
        "O",
        null,
        null,
        null,
        null
      ],
      [
        "S",
        null,
        "U",
        null,
        "H",
        null,
        null
      ],
      [
        "A",
        "I",
        "R",
        "P",
        "O",
        "R",
        "T"
      ],
      [
        null,
        null,
        null,
        null,
        "T",
        null,
        "A"
      ],
      [
        "R",
        "O",
        "U",
        "T",
        "E",
        null,
        "X"
      ],
      [
        null,
        null,
        null,
        null,
        "L",
        null,
        "I"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Permission to enter a country",
        "answer": "VISA",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "It runs on rails",
        "answer": "TRAIN",
        "row": 0,
        "col": 2
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "A guided trip around sights",
        "answer": "TOUR",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Where you sleep on a trip",
        "answer": "HOTEL",
        "row": 2,
        "col": 4
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Where planes take off and land",
        "answer": "AIRPORT",
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Car you pay to ride in",
        "answer": "TAXI",
        "row": 3,
        "col": 6
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "The path you take",
        "answer": "ROUTE",
        "row": 5,
        "col": 0
      }
    ],
    "bonusWord": "TICKET",
    "bonusHint": "You need it to board"
  },
  {
    "id": 16,
    "title": "Clothing",
    "size": 7,
    "solution": [
      [
        "D",
        "R",
        "E",
        "S",
        "S",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "C",
        null,
        null
      ],
      [
        null,
        null,
        "S",
        null,
        "A",
        null,
        null
      ],
      [
        null,
        "S",
        "H",
        "I",
        "R",
        "T",
        null
      ],
      [
        null,
        null,
        "O",
        null,
        "F",
        null,
        "H"
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        null,
        "A"
      ],
      [
        null,
        null,
        "S",
        "K",
        "I",
        "R",
        "T"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "One-piece outfit",
        "answer": "DRESS",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You wrap it around your neck",
        "answer": "SCARF",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "You wear them on your feet",
        "answer": "SHOES",
        "row": 2,
        "col": 2
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Top with buttons and a collar",
        "answer": "SHIRT",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "You wear it on your head",
        "answer": "HAT",
        "row": 4,
        "col": 6
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "It hangs from the waist",
        "answer": "SKIRT",
        "row": 6,
        "col": 2
      }
    ],
    "bonusWord": "JACKET",
    "bonusHint": "Light coat for your top half"
  },
  {
    "id": 17,
    "title": "House & Home",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        null,
        null,
        "D",
        null
      ],
      [
        "L",
        null,
        "F",
        "L",
        "O",
        "O",
        "R"
      ],
      [
        "A",
        null,
        null,
        null,
        null,
        "O",
        null
      ],
      [
        "M",
        "I",
        "R",
        "R",
        "O",
        "R",
        null
      ],
      [
        "P",
        null,
        null,
        "O",
        null,
        null,
        null
      ],
      [
        null,
        "C",
        "L",
        "O",
        "S",
        "E",
        "T"
      ],
      [
        null,
        null,
        null,
        "F",
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "You open it to enter",
        "answer": "DOOR",
        "row": 0,
        "col": 5
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "It gives light on a desk",
        "answer": "LAMP",
        "row": 1,
        "col": 0
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "You walk on it",
        "answer": "FLOOR",
        "row": 1,
        "col": 2
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "You see your reflection in it",
        "answer": "MIRROR",
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "It covers the house on top",
        "answer": "ROOF",
        "row": 3,
        "col": 3
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Small room for storing clothes",
        "answer": "CLOSET",
        "row": 5,
        "col": 1
      }
    ],
    "bonusWord": "WINDOW",
    "bonusHint": "You look outside through it"
  },
  {
    "id": 18,
    "title": "Nature",
    "size": 7,
    "solution": [
      [
        "M",
        null,
        "T",
        "R",
        "E",
        "E",
        null
      ],
      [
        "E",
        null,
        null,
        "I",
        null,
        null,
        null
      ],
      [
        "A",
        null,
        null,
        "V",
        null,
        "S",
        null
      ],
      [
        "D",
        "E",
        "S",
        "E",
        "R",
        "T",
        null
      ],
      [
        "O",
        null,
        null,
        "R",
        null,
        "O",
        null
      ],
      [
        "W",
        null,
        null,
        null,
        null,
        "N",
        null
      ],
      [
        null,
        "V",
        "A",
        "L",
        "L",
        "E",
        "Y"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Grassy field with flowers",
        "answer": "MEADOW",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "It has a trunk and leaves",
        "answer": "TREE",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Water flowing to the sea",
        "answer": "RIVER",
        "row": 0,
        "col": 3
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "A small rock",
        "answer": "STONE",
        "row": 2,
        "col": 5
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Dry, sandy region",
        "answer": "DESERT",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Low land between hills",
        "answer": "VALLEY",
        "row": 6,
        "col": 1
      }
    ],
    "bonusWord": "FOREST",
    "bonusHint": "A large area full of trees"
  },
  {
    "id": 19,
    "title": "Food & Meals",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        "R",
        "I",
        "C",
        "E"
      ],
      [
        "H",
        null,
        null,
        null,
        null,
        "A",
        null
      ],
      [
        "O",
        null,
        "T",
        null,
        null,
        "K",
        null
      ],
      [
        "N",
        "O",
        "O",
        "D",
        "L",
        "E",
        null
      ],
      [
        "E",
        null,
        "A",
        null,
        null,
        null,
        null
      ],
      [
        "Y",
        null,
        "S",
        "A",
        "L",
        "A",
        "D"
      ],
      [
        null,
        null,
        "T",
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Small white grains",
        "answer": "RICE",
        "row": 0,
        "col": 3
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Sweet treat for a birthday",
        "answer": "CAKE",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Sweet food made by bees",
        "answer": "HONEY",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Browned bread",
        "answer": "TOAST",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Long strand in your soup",
        "answer": "NOODLE",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Bowl of fresh vegetables",
        "answer": "SALAD",
        "row": 5,
        "col": 2
      }
    ],
    "bonusWord": "CHEESE",
    "bonusHint": "Dairy food made from milk"
  },
  {
    "id": 20,
    "title": "Technology",
    "size": 7,
    "solution": [
      [
        "M",
        null,
        null,
        null,
        "M",
        null,
        null
      ],
      [
        "O",
        null,
        null,
        "C",
        "O",
        "D",
        "E"
      ],
      [
        "U",
        null,
        "D",
        null,
        "D",
        null,
        null
      ],
      [
        "S",
        "C",
        "R",
        "E",
        "E",
        "N",
        null
      ],
      [
        "E",
        null,
        "O",
        null,
        "M",
        null,
        null
      ],
      [
        null,
        null,
        "N",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "E",
        "M",
        "A",
        "I",
        "L"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "You click with it",
        "answer": "MOUSE",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Box that connects you to the internet",
        "answer": "MODEM",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Instructions for a program",
        "answer": "CODE",
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Small flying machine with a camera",
        "answer": "DRONE",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "You watch it on a device",
        "answer": "SCREEN",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Electronic message",
        "answer": "EMAIL",
        "row": 6,
        "col": 2
      }
    ],
    "bonusWord": "LAPTOP",
    "bonusHint": "Portable computer"
  },
  {
    "id": 21,
    "title": "Camping",
    "size": 7,
    "solution": [
      [
        "T",
        "R",
        "A",
        "I",
        "L",
        null,
        null
      ],
      [
        "O",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "R",
        null,
        null,
        null,
        "C",
        null,
        null
      ],
      [
        "C",
        "O",
        "M",
        "P",
        "A",
        "S",
        "S"
      ],
      [
        "H",
        null,
        null,
        null,
        "B",
        null,
        null
      ],
      [
        null,
        null,
        "K",
        "N",
        "I",
        "F",
        "E"
      ],
      [
        null,
        null,
        null,
        null,
        "N",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "A path through the woods",
        "answer": "TRAIL",
        "row": 0,
        "col": 0
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "Handheld flashlight",
        "answer": "TORCH",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Small wooden hut",
        "answer": "CABIN",
        "row": 2,
        "col": 4
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "It points north",
        "answer": "COMPASS",
        "row": 3,
        "col": 0
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Handy cutting tool",
        "answer": "KNIFE",
        "row": 5,
        "col": 2
      }
    ],
    "bonusWord": "LANTERN",
    "bonusHint": "Portable light for the dark"
  },
  {
    "id": 22,
    "title": "The Beach",
    "size": 7,
    "solution": [
      [
        null,
        "C",
        "R",
        "A",
        "B",
        null,
        null
      ],
      [
        null,
        "O",
        null,
        null,
        null,
        "P",
        null
      ],
      [
        null,
        "R",
        null,
        null,
        null,
        "A",
        null
      ],
      [
        "S",
        "A",
        "N",
        "D",
        "A",
        "L",
        null
      ],
      [
        null,
        "L",
        null,
        "U",
        null,
        "M",
        null
      ],
      [
        null,
        null,
        null,
        "N",
        null,
        null,
        null
      ],
      [
        "T",
        "O",
        "W",
        "E",
        "L",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "It scuttles on the sand",
        "answer": "CRAB",
        "row": 0,
        "col": 1
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "Colorful sea growth",
        "answer": "CORAL",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tropical beach tree",
        "answer": "PALM",
        "row": 1,
        "col": 5
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Open summer shoe",
        "answer": "SANDAL",
        "row": 3,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "A hill of sand",
        "answer": "DUNE",
        "row": 3,
        "col": 3
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "You lie on it at the beach",
        "answer": "TOWEL",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "SHELL",
    "bonusHint": "You collect it in the sand"
  },
  {
    "id": 23,
    "title": "Winter",
    "size": 7,
    "solution": [
      [
        null,
        "S",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "C",
        null,
        "S",
        "K",
        "I",
        null
      ],
      [
        null,
        "A",
        null,
        "L",
        null,
        "C",
        null
      ],
      [
        "F",
        "R",
        "E",
        "E",
        "Z",
        "E",
        null
      ],
      [
        null,
        "F",
        null,
        "E",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "S",
        "T",
        "O",
        "R",
        "M"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "You wrap it around your neck",
        "answer": "SCARF",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Slide down a snowy slope",
        "answer": "SKI",
        "row": 1,
        "col": 3
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Rain mixed with snow",
        "answer": "SLEET",
        "row": 1,
        "col": 3
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Frozen water",
        "answer": "ICE",
        "row": 1,
        "col": 5
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Turn to ice",
        "answer": "FREEZE",
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "A blizzard is a snow ___",
        "answer": "STORM",
        "row": 5,
        "col": 2
      }
    ],
    "bonusWord": "FROST",
    "bonusHint": "Icy coating on cold mornings"
  },
  {
    "id": 24,
    "title": "In the Garden",
    "size": 7,
    "solution": [
      [
        null,
        null,
        "D",
        "A",
        "I",
        "S",
        "Y"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "T",
        null
      ],
      [
        null,
        null,
        null,
        "S",
        null,
        "E",
        null
      ],
      [
        null,
        "B",
        "L",
        "O",
        "O",
        "M",
        null
      ],
      [
        null,
        null,
        null,
        "I",
        null,
        null,
        null
      ],
      [
        null,
        "T",
        "U",
        "L",
        "I",
        "P",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "White flower with a yellow center",
        "answer": "DAISY",
        "row": 0,
        "col": 2
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "It holds up the flower",
        "answer": "STEM",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "The dirt plants grow in",
        "answer": "SOIL",
        "row": 2,
        "col": 3
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "What a flower does in spring",
        "answer": "BLOOM",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Cup-shaped spring flower",
        "answer": "TULIP",
        "row": 5,
        "col": 1
      }
    ],
    "bonusWord": "FLOWER",
    "bonusHint": "A rose or a tulip"
  },
  {
    "id": 25,
    "title": "Insects",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        "A",
        "S",
        "P",
        null,
        null
      ],
      [
        "L",
        null,
        "P",
        null,
        null,
        "B",
        null
      ],
      [
        "O",
        null,
        "H",
        null,
        null,
        "E",
        null
      ],
      [
        "C",
        "R",
        "I",
        "C",
        "K",
        "E",
        "T"
      ],
      [
        "U",
        null,
        "D",
        null,
        null,
        "T",
        null
      ],
      [
        "S",
        null,
        null,
        null,
        null,
        "L",
        null
      ],
      [
        "T",
        null,
        null,
        "F",
        "L",
        "E",
        "A"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Stinging insect with a thin waist",
        "answer": "WASP",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tiny insect that harms plants",
        "answer": "APHID",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Swarming grasshopper",
        "answer": "LOCUST",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "It makes honey",
        "answer": "BEE",
        "row": 1,
        "col": 5
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Hard-shelled crawling bug",
        "answer": "BEETLE",
        "row": 1,
        "col": 5
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "It chirps at night",
        "answer": "CRICKET",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Tiny jumping pest on pets",
        "answer": "FLEA",
        "row": 6,
        "col": 3
      }
    ],
    "bonusWord": "SPIDER",
    "bonusHint": "It spins a web"
  },
  {
    "id": 26,
    "title": "Tools",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        "R",
        "E",
        "N",
        "C",
        "H"
      ],
      [
        "T",
        null,
        null,
        null,
        null,
        "H",
        null
      ],
      [
        "A",
        null,
        null,
        "L",
        null,
        "I",
        null
      ],
      [
        "P",
        "L",
        "I",
        "E",
        "R",
        "S",
        null
      ],
      [
        "E",
        null,
        null,
        "V",
        null,
        "E",
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        "L",
        null
      ],
      [
        null,
        "B",
        "O",
        "L",
        "T",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "You tighten bolts with it",
        "answer": "WRENCH",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tool for carving wood",
        "answer": "CHISEL",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "A measuring ___",
        "answer": "TAPE",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "It checks if things are flat",
        "answer": "LEVEL",
        "row": 2,
        "col": 3
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "You grip things with them",
        "answer": "PLIERS",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Metal pin fastened with a nut",
        "answer": "BOLT",
        "row": 6,
        "col": 1
      }
    ],
    "bonusWord": "HAMMER",
    "bonusHint": "You hit nails with it"
  },
  {
    "id": 27,
    "title": "Emotions",
    "size": 7,
    "solution": [
      [
        "T",
        null,
        null,
        null,
        "H",
        null,
        null
      ],
      [
        "E",
        null,
        null,
        "J",
        "O",
        "Y",
        null
      ],
      [
        "N",
        null,
        "C",
        null,
        "P",
        null,
        null
      ],
      [
        "S",
        "C",
        "A",
        "R",
        "E",
        "D",
        null
      ],
      [
        "E",
        null,
        "L",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "M",
        "E",
        "R",
        "R",
        "Y"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Nervous and on edge",
        "answer": "TENSE",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Wishing for something good",
        "answer": "HOPE",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "A feeling of great happiness",
        "answer": "JOY",
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Peaceful and relaxed",
        "answer": "CALM",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Feeling afraid",
        "answer": "SCARED",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Cheerful and jolly",
        "answer": "MERRY",
        "row": 5,
        "col": 2
      }
    ],
    "bonusWord": "HAPPY",
    "bonusHint": "Feeling full of joy"
  },
  {
    "id": 28,
    "title": "Drinks",
    "size": 7,
    "solution": [
      [
        null,
        null,
        "P",
        "U",
        "N",
        "C",
        "H"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "I",
        null
      ],
      [
        null,
        null,
        null,
        "L",
        null,
        "D",
        null
      ],
      [
        null,
        "S",
        "H",
        "A",
        "K",
        "E",
        null
      ],
      [
        null,
        "O",
        null,
        "T",
        null,
        "R",
        null
      ],
      [
        null,
        "D",
        null,
        "T",
        null,
        null,
        null
      ],
      [
        "W",
        "A",
        "T",
        "E",
        "R",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Mixed fruity party drink",
        "answer": "PUNCH",
        "row": 0,
        "col": 2
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Drink made from apples",
        "answer": "CIDER",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Coffee with steamed milk",
        "answer": "LATTE",
        "row": 2,
        "col": 3
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Thick blended milk drink",
        "answer": "SHAKE",
        "row": 3,
        "col": 1
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Fizzy sweet drink",
        "answer": "SODA",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Clear, plain drink",
        "answer": "WATER",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "COFFEE",
    "bonusHint": "Hot drink that wakes you up"
  },
  {
    "id": 29,
    "title": "Countries",
    "size": 7,
    "solution": [
      [
        "C",
        "H",
        "I",
        "N",
        "A",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        "I",
        null
      ],
      [
        null,
        "J",
        null,
        "P",
        null,
        "T",
        null
      ],
      [
        "C",
        "A",
        "N",
        "A",
        "D",
        "A",
        null
      ],
      [
        null,
        "P",
        null,
        "L",
        null,
        "L",
        null
      ],
      [
        null,
        "A",
        null,
        null,
        null,
        "Y",
        null
      ],
      [
        "I",
        "N",
        "D",
        "I",
        "A",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Country with the Great Wall",
        "answer": "CHINA",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Country with Mount Everest",
        "answer": "NEPAL",
        "row": 0,
        "col": 3
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Boot-shaped European country",
        "answer": "ITALY",
        "row": 1,
        "col": 5
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Land of the rising sun",
        "answer": "JAPAN",
        "row": 2,
        "col": 1
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Country north of the USA",
        "answer": "CANADA",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Country of the Taj Mahal",
        "answer": "INDIA",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "BRAZIL",
    "bonusHint": "Largest country in South America"
  },
  {
    "id": 30,
    "title": "Time & Calendar",
    "size": 7,
    "solution": [
      [
        null,
        "A",
        "L",
        "A",
        "R",
        "M",
        null
      ],
      [
        "D",
        null,
        null,
        null,
        null,
        "O",
        null
      ],
      [
        "U",
        null,
        null,
        "M",
        null,
        "N",
        null
      ],
      [
        "S",
        "E",
        "C",
        "O",
        "N",
        "D",
        null
      ],
      [
        "K",
        null,
        null,
        "N",
        null,
        "A",
        null
      ],
      [
        null,
        null,
        null,
        "T",
        null,
        "Y",
        null
      ],
      [
        "N",
        "I",
        "G",
        "H",
        "T",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "It wakes you up",
        "answer": "ALARM",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "First day of the work week",
        "answer": "MONDAY",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "When the sun sets",
        "answer": "DUSK",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "About thirty days",
        "answer": "MONTH",
        "row": 2,
        "col": 3
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "The smallest unit on a clock face",
        "answer": "SECOND",
        "row": 3,
        "col": 0
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "The dark part of the day",
        "answer": "NIGHT",
        "row": 6,
        "col": 0
      }
    ],
    "bonusWord": "MINUTE",
    "bonusHint": "Sixty seconds"
  }
];
