// AUTO-GENERATED by scripts/genCrossword.ts — do not edit by hand.
// 7x7 mini crosswords for the Crossword mini-game.
export type CrosswordDir = 'across' | 'down';
export interface CrosswordClue {
  number: number;
  direction: CrosswordDir;
  clue: string;
  answer: string;
  row: number;
  col: number;
  bonus: boolean;
}
export interface CrosswordPuzzle {
  id: number;
  title: string;
  size: number;
  solution: (string | null)[][];
  clues: CrosswordClue[];
  bonusWord: string;
}

export const CROSSWORD_PUZZLES: CrosswordPuzzle[] = [
  {
    "id": 1,
    "title": "Animals",
    "size": 7,
    "solution": [
      [
        "P",
        "A",
        "N",
        "D",
        "A",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        null,
        null
      ],
      [
        null,
        "R",
        null,
        "E",
        null,
        "Z",
        null
      ],
      [
        null,
        "H",
        "O",
        "R",
        "S",
        "E",
        null
      ],
      [
        null,
        "I",
        null,
        null,
        null,
        "B",
        null
      ],
      [
        null,
        "N",
        null,
        null,
        null,
        "R",
        null
      ],
      [
        null,
        "O",
        null,
        "S",
        "E",
        "A",
        "L"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Black-and-white bamboo eater",
        "answer": "PANDA",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Forest animal with antlers",
        "answer": "DEER",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Thick-skinned beast with a horn",
        "answer": "RHINO",
        "row": 2,
        "col": 1,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Striped relative of the horse",
        "answer": "ZEBRA",
        "row": 2,
        "col": 5,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Animal you can ride",
        "answer": "HORSE",
        "row": 3,
        "col": 1,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "It claps and barks at the zoo",
        "answer": "SEAL",
        "row": 6,
        "col": 3,
        "bonus": false
      }
    ],
    "bonusWord": "HORSE"
  },
  {
    "id": 2,
    "title": "Fruits",
    "size": 7,
    "solution": [
      [
        "L",
        null,
        "B",
        "E",
        "R",
        "R",
        "Y"
      ],
      [
        "E",
        null,
        "A",
        null,
        null,
        null,
        null
      ],
      [
        "M",
        null,
        "N",
        null,
        null,
        "M",
        null
      ],
      [
        "O",
        "R",
        "A",
        "N",
        "G",
        "E",
        null
      ],
      [
        "N",
        null,
        "N",
        null,
        null,
        "L",
        null
      ],
      [
        null,
        "M",
        "A",
        "N",
        "G",
        "O",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "N",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Sour yellow citrus",
        "answer": "LEMON",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Small soft fruit, like a straw-",
        "answer": "BERRY",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Long yellow fruit",
        "answer": "BANANA",
        "row": 0,
        "col": 2,
        "bonus": true
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Big juicy summer fruit",
        "answer": "MELON",
        "row": 2,
        "col": 5,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Round citrus, same name as a color",
        "answer": "ORANGE",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Sweet tropical fruit",
        "answer": "MANGO",
        "row": 5,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "BANANA"
  },
  {
    "id": 3,
    "title": "Space",
    "size": 7,
    "solution": [
      [
        null,
        "P",
        "L",
        "A",
        "N",
        "E",
        "T"
      ],
      [
        "C",
        null,
        null,
        "L",
        null,
        null,
        null
      ],
      [
        "O",
        null,
        null,
        "I",
        null,
        "O",
        null
      ],
      [
        "M",
        "E",
        "T",
        "E",
        "O",
        "R",
        null
      ],
      [
        "E",
        null,
        null,
        "N",
        null,
        "B",
        null
      ],
      [
        "T",
        null,
        null,
        null,
        null,
        "I",
        null
      ],
      [
        null,
        null,
        "E",
        "A",
        "R",
        "T",
        "H"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Earth is one",
        "answer": "PLANET",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Imagined being from space",
        "answer": "ALIEN",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Icy body with a glowing tail",
        "answer": "COMET",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Path around the sun",
        "answer": "ORBIT",
        "row": 2,
        "col": 5,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Shooting star",
        "answer": "METEOR",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "The planet we live on",
        "answer": "EARTH",
        "row": 6,
        "col": 2,
        "bonus": false
      }
    ],
    "bonusWord": "METEOR"
  },
  {
    "id": 4,
    "title": "In the Kitchen",
    "size": 7,
    "solution": [
      [
        "F",
        null,
        "M",
        "U",
        "G",
        null,
        null
      ],
      [
        "O",
        null,
        null,
        null,
        "R",
        null,
        null
      ],
      [
        "R",
        null,
        "S",
        null,
        "I",
        null,
        null
      ],
      [
        "K",
        "E",
        "T",
        "T",
        "L",
        "E",
        null
      ],
      [
        null,
        null,
        "O",
        null,
        "L",
        null,
        null
      ],
      [
        null,
        null,
        "V",
        null,
        null,
        null,
        null
      ],
      [
        "O",
        "V",
        "E",
        "N",
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "It has prongs for eating",
        "answer": "FORK",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Holds your coffee",
        "answer": "MUG",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Cook meat over flames",
        "answer": "GRILL",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "You cook on it",
        "answer": "STOVE",
        "row": 2,
        "col": 2,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "It boils water for tea",
        "answer": "KETTLE",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "You bake in it",
        "answer": "OVEN",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "KETTLE"
  },
  {
    "id": 5,
    "title": "Weather",
    "size": 7,
    "solution": [
      [
        "G",
        null,
        null,
        null,
        "W",
        null,
        null
      ],
      [
        "U",
        null,
        "C",
        "H",
        "I",
        "L",
        "L"
      ],
      [
        "S",
        null,
        null,
        null,
        "N",
        null,
        null
      ],
      [
        "T",
        "H",
        "U",
        "N",
        "D",
        "E",
        "R"
      ],
      [
        null,
        "A",
        null,
        null,
        "Y",
        null,
        "A"
      ],
      [
        null,
        "I",
        null,
        null,
        null,
        null,
        "I"
      ],
      [
        "C",
        "L",
        "O",
        "U",
        "D",
        null,
        "N"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "A sudden burst of wind",
        "answer": "GUST",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Lots of breeze",
        "answer": "WINDY",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "A cold feeling in the air",
        "answer": "CHILL",
        "row": 1,
        "col": 2,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "The boom after lightning",
        "answer": "THUNDER",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Ice balls from the sky",
        "answer": "HAIL",
        "row": 3,
        "col": 1,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "Water falling from the sky",
        "answer": "RAIN",
        "row": 3,
        "col": 6,
        "bonus": false
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "It floats and may bring rain",
        "answer": "CLOUD",
        "row": 6,
        "col": 0,
        "bonus": true
      }
    ],
    "bonusWord": "CLOUD"
  },
  {
    "id": 6,
    "title": "Sports",
    "size": 7,
    "solution": [
      [
        "H",
        "O",
        "C",
        "K",
        "E",
        "Y",
        null
      ],
      [
        null,
        null,
        "O",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "A",
        null,
        "M",
        null,
        null
      ],
      [
        "S",
        "O",
        "C",
        "C",
        "E",
        "R",
        null
      ],
      [
        "U",
        null,
        "H",
        null,
        "D",
        null,
        "N"
      ],
      [
        "R",
        null,
        null,
        "R",
        "A",
        "C",
        "E"
      ],
      [
        "F",
        null,
        null,
        null,
        "L",
        null,
        "T"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Game played with sticks and a puck",
        "answer": "HOCKEY",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Person who trains the team",
        "answer": "COACH",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Prize for winning",
        "answer": "MEDAL",
        "row": 2,
        "col": 4,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Game played with a round ball and feet",
        "answer": "SOCCER",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Ride waves on a board",
        "answer": "SURF",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Ball passes over or into it",
        "answer": "NET",
        "row": 4,
        "col": 6,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "A contest of speed",
        "answer": "RACE",
        "row": 5,
        "col": 3,
        "bonus": false
      }
    ],
    "bonusWord": "SOCCER"
  },
  {
    "id": 7,
    "title": "Music",
    "size": 7,
    "solution": [
      [
        "S",
        null,
        null,
        null,
        null,
        "O",
        null
      ],
      [
        "O",
        null,
        "T",
        "E",
        "M",
        "P",
        "O"
      ],
      [
        "N",
        null,
        null,
        null,
        null,
        "E",
        null
      ],
      [
        "G",
        "U",
        "I",
        "T",
        "A",
        "R",
        null
      ],
      [
        null,
        null,
        null,
        "U",
        null,
        "A",
        null
      ],
      [
        "P",
        "I",
        "A",
        "N",
        "O",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Music with words",
        "answer": "SONG",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Drama that is sung",
        "answer": "OPERA",
        "row": 0,
        "col": 5,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Speed of the music",
        "answer": "TEMPO",
        "row": 1,
        "col": 2,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Six-stringed instrument",
        "answer": "GUITAR",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "A melody",
        "answer": "TUNE",
        "row": 3,
        "col": 3,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Instrument with black and white keys",
        "answer": "PIANO",
        "row": 5,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "GUITAR"
  },
  {
    "id": 8,
    "title": "The Body",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        null,
        "B",
        "O",
        "N",
        "E"
      ],
      [
        null,
        "R",
        null,
        "R",
        null,
        null,
        null
      ],
      [
        null,
        "I",
        null,
        "A",
        null,
        "H",
        null
      ],
      [
        null,
        "S",
        "P",
        "I",
        "N",
        "E",
        null
      ],
      [
        null,
        "T",
        null,
        "N",
        null,
        "A",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "R",
        null
      ],
      [
        null,
        "C",
        "H",
        "E",
        "S",
        "T",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Joint where your watch sits",
        "answer": "WRIST",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Hard part of the skeleton",
        "answer": "BONE",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You think with it",
        "answer": "BRAIN",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "It pumps your blood",
        "answer": "HEART",
        "row": 2,
        "col": 5,
        "bonus": true
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Your backbone",
        "answer": "SPINE",
        "row": 3,
        "col": 1,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Front of the upper body",
        "answer": "CHEST",
        "row": 6,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "HEART"
  },
  {
    "id": 9,
    "title": "At School",
    "size": 7,
    "solution": [
      [
        "P",
        "E",
        "N",
        "C",
        "I",
        "L",
        null
      ],
      [
        "A",
        null,
        null,
        "L",
        null,
        null,
        null
      ],
      [
        "P",
        null,
        null,
        "A",
        null,
        "G",
        null
      ],
      [
        "E",
        "R",
        "A",
        "S",
        "E",
        "R",
        null
      ],
      [
        "R",
        null,
        null,
        "S",
        null,
        "A",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "D",
        null
      ],
      [
        null,
        "M",
        "A",
        "R",
        "K",
        "E",
        "R"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "You write with it and erase it",
        "answer": "PENCIL",
        "row": 0,
        "col": 0,
        "bonus": true
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "You write on a sheet of it",
        "answer": "PAPER",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "A group of students",
        "answer": "CLASS",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "A mark for your work",
        "answer": "GRADE",
        "row": 2,
        "col": 5,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "It rubs out mistakes",
        "answer": "ERASER",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Thick colored pen",
        "answer": "MARKER",
        "row": 6,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "PENCIL"
  },
  {
    "id": 10,
    "title": "In the Ocean",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "T",
        "U",
        "N",
        "A",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        null,
        null
      ],
      [
        "O",
        "C",
        "T",
        "O",
        "P",
        "U",
        "S"
      ],
      [
        null,
        "R",
        null,
        null,
        null,
        null,
        "A"
      ],
      [
        "W",
        "A",
        "V",
        "E",
        null,
        null,
        "I"
      ],
      [
        null,
        "B",
        null,
        null,
        "E",
        "E",
        "L"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Fish often found in a sandwich",
        "answer": "TUNA",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Used to catch fish",
        "answer": "NET",
        "row": 1,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Sea animal with eight arms",
        "answer": "OCTOPUS",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "It walks sideways with claws",
        "answer": "CRAB",
        "row": 3,
        "col": 1,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Cloth that catches wind on a boat",
        "answer": "SAIL",
        "row": 3,
        "col": 6,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "It rolls onto the shore",
        "answer": "WAVE",
        "row": 5,
        "col": 0,
        "bonus": false
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Long, snake-like fish",
        "answer": "EEL",
        "row": 6,
        "col": 4,
        "bonus": false
      }
    ],
    "bonusWord": "OCTOPUS"
  },
  {
    "id": 11,
    "title": "Birds",
    "size": 7,
    "solution": [
      [
        "G",
        null,
        null,
        null,
        null,
        null,
        "C"
      ],
      [
        "O",
        null,
        null,
        null,
        "P",
        null,
        "R"
      ],
      [
        "O",
        null,
        "R",
        null,
        "A",
        null,
        "O"
      ],
      [
        "S",
        "P",
        "A",
        "R",
        "R",
        "O",
        "W"
      ],
      [
        "E",
        null,
        "V",
        null,
        "R",
        null,
        null
      ],
      [
        null,
        "H",
        "E",
        "R",
        "O",
        "N",
        null
      ],
      [
        null,
        null,
        "N",
        null,
        "T",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Larger relative of the duck",
        "answer": "GOOSE",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Black bird with a harsh caw",
        "answer": "CROW",
        "row": 0,
        "col": 6,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Colorful bird that can talk",
        "answer": "PARROT",
        "row": 1,
        "col": 4,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Big black bird",
        "answer": "RAVEN",
        "row": 2,
        "col": 2,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Common small brown bird",
        "answer": "SPARROW",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Tall wading bird with long legs",
        "answer": "HERON",
        "row": 5,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "SPARROW"
  },
  {
    "id": 12,
    "title": "Vegetables",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        "B",
        "E",
        "E",
        "T"
      ],
      [
        "K",
        "A",
        "L",
        "E",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "A",
        null,
        null,
        null
      ],
      [
        "S",
        "P",
        "I",
        "N",
        "A",
        "C",
        "H"
      ],
      [
        null,
        "E",
        null,
        null,
        null,
        "O",
        null
      ],
      [
        null,
        "A",
        null,
        "O",
        "K",
        "R",
        "A"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "N",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Deep red root vegetable",
        "answer": "BEET",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "It grows in a pod",
        "answer": "BEAN",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Leafy green superfood",
        "answer": "KALE",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Popeye's leafy green",
        "answer": "SPINACH",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Tiny green ball in a pod",
        "answer": "PEA",
        "row": 3,
        "col": 1,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Yellow kernels on a cob",
        "answer": "CORN",
        "row": 3,
        "col": 5,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Green pod used in gumbo",
        "answer": "OKRA",
        "row": 5,
        "col": 3,
        "bonus": false
      }
    ],
    "bonusWord": "SPINACH"
  },
  {
    "id": 13,
    "title": "Colors & Shapes",
    "size": 7,
    "solution": [
      [
        "B",
        null,
        null,
        "C",
        "O",
        "N",
        "E"
      ],
      [
        "L",
        null,
        "P",
        null,
        "V",
        null,
        null
      ],
      [
        "A",
        null,
        "U",
        null,
        "A",
        null,
        null
      ],
      [
        "C",
        "I",
        "R",
        "C",
        "L",
        "E",
        null
      ],
      [
        "K",
        null,
        "P",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "L",
        null,
        null,
        null,
        null
      ],
      [
        "G",
        "R",
        "E",
        "E",
        "N",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Color of the night sky",
        "answer": "BLACK",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Shape of an ice-cream holder",
        "answer": "CONE",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Egg-shaped",
        "answer": "OVAL",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Color of grapes",
        "answer": "PURPLE",
        "row": 1,
        "col": 2,
        "bonus": true
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "A perfectly round shape",
        "answer": "CIRCLE",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Color of grass",
        "answer": "GREEN",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "PURPLE"
  },
  {
    "id": 14,
    "title": "Jobs",
    "size": 7,
    "solution": [
      [
        "D",
        null,
        null,
        "M",
        "A",
        "I",
        "D"
      ],
      [
        "O",
        null,
        "W",
        null,
        "C",
        null,
        null
      ],
      [
        "C",
        null,
        "R",
        null,
        "T",
        null,
        null
      ],
      [
        "T",
        "A",
        "I",
        "L",
        "O",
        "R",
        null
      ],
      [
        "O",
        null,
        "T",
        null,
        "R",
        null,
        "V"
      ],
      [
        "R",
        null,
        "E",
        null,
        null,
        null,
        "E"
      ],
      [
        null,
        "A",
        "R",
        "T",
        "I",
        "S",
        "T"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "They help sick people get well",
        "answer": "DOCTOR",
        "row": 0,
        "col": 0,
        "bonus": true
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "They clean hotel rooms",
        "answer": "MAID",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "They perform in films",
        "answer": "ACTOR",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "They write books",
        "answer": "WRITER",
        "row": 1,
        "col": 2,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "They make and fix clothes",
        "answer": "TAILOR",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "Animal doctor",
        "answer": "VET",
        "row": 4,
        "col": 6,
        "bonus": false
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "They paint and draw",
        "answer": "ARTIST",
        "row": 6,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "DOCTOR"
  },
  {
    "id": 15,
    "title": "Travel",
    "size": 7,
    "solution": [
      [
        "V",
        null,
        "T",
        "A",
        "X",
        "I",
        null
      ],
      [
        "I",
        null,
        "O",
        null,
        null,
        null,
        "H"
      ],
      [
        "S",
        null,
        "U",
        null,
        "R",
        null,
        "O"
      ],
      [
        "A",
        "I",
        "R",
        "P",
        "O",
        "R",
        "T"
      ],
      [
        null,
        null,
        null,
        null,
        "U",
        null,
        "E"
      ],
      [
        null,
        null,
        null,
        null,
        "T",
        null,
        "L"
      ],
      [
        "T",
        "I",
        "C",
        "K",
        "E",
        "T",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Permission to enter a country",
        "answer": "VISA",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Car you pay to ride in",
        "answer": "TAXI",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "A guided trip around sights",
        "answer": "TOUR",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Where you sleep on a trip",
        "answer": "HOTEL",
        "row": 1,
        "col": 6,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "The path you take",
        "answer": "ROUTE",
        "row": 2,
        "col": 4,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Where planes take off and land",
        "answer": "AIRPORT",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "You need it to board",
        "answer": "TICKET",
        "row": 6,
        "col": 0,
        "bonus": true
      }
    ],
    "bonusWord": "TICKET"
  },
  {
    "id": 16,
    "title": "Clothing",
    "size": 7,
    "solution": [
      [
        "D",
        "R",
        "E",
        "S",
        "S",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "O",
        null,
        "H",
        null
      ],
      [
        null,
        "P",
        null,
        "C",
        null,
        "A",
        null
      ],
      [
        "J",
        "A",
        "C",
        "K",
        "E",
        "T",
        null
      ],
      [
        null,
        "N",
        null,
        "S",
        null,
        null,
        null
      ],
      [
        null,
        "T",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "S",
        "C",
        "A",
        "R",
        "F",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "One-piece outfit",
        "answer": "DRESS",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "They go on before shoes",
        "answer": "SOCKS",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "You wear it on your head",
        "answer": "HAT",
        "row": 1,
        "col": 5,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "You wear them on your legs",
        "answer": "PANTS",
        "row": 2,
        "col": 1,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Light coat for your top half",
        "answer": "JACKET",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "You wrap it around your neck",
        "answer": "SCARF",
        "row": 6,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "JACKET"
  },
  {
    "id": 17,
    "title": "House & Home",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        "I",
        "N",
        "D",
        "O",
        "W"
      ],
      [
        null,
        null,
        null,
        null,
        "O",
        null,
        null
      ],
      [
        null,
        null,
        "T",
        null,
        "O",
        null,
        null
      ],
      [
        "S",
        "T",
        "A",
        "I",
        "R",
        "S",
        null
      ],
      [
        null,
        null,
        "B",
        null,
        null,
        "I",
        null
      ],
      [
        "W",
        "A",
        "L",
        "L",
        null,
        "N",
        null
      ],
      [
        null,
        null,
        "E",
        null,
        null,
        "K",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "You look outside through it",
        "answer": "WINDOW",
        "row": 0,
        "col": 1,
        "bonus": true
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You open it to enter",
        "answer": "DOOR",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "You eat at it",
        "answer": "TABLE",
        "row": 2,
        "col": 2,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "You climb them between floors",
        "answer": "STAIRS",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "You wash your hands in it",
        "answer": "SINK",
        "row": 3,
        "col": 5,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "It divides the rooms",
        "answer": "WALL",
        "row": 5,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "WINDOW"
  },
  {
    "id": 18,
    "title": "Nature",
    "size": 7,
    "solution": [
      [
        "M",
        null,
        "T",
        "R",
        "E",
        "E",
        null
      ],
      [
        "E",
        null,
        null,
        "I",
        null,
        null,
        null
      ],
      [
        "A",
        null,
        null,
        "V",
        null,
        "S",
        null
      ],
      [
        "D",
        "E",
        "S",
        "E",
        "R",
        "T",
        null
      ],
      [
        "O",
        null,
        null,
        "R",
        null,
        "O",
        null
      ],
      [
        "W",
        null,
        null,
        null,
        null,
        "N",
        null
      ],
      [
        null,
        "V",
        "A",
        "L",
        "L",
        "E",
        "Y"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Grassy field with flowers",
        "answer": "MEADOW",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "It has a trunk and leaves",
        "answer": "TREE",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Water flowing to the sea",
        "answer": "RIVER",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "A small rock",
        "answer": "STONE",
        "row": 2,
        "col": 5,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Dry, sandy region",
        "answer": "DESERT",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Low land between hills",
        "answer": "VALLEY",
        "row": 6,
        "col": 1,
        "bonus": false
      }
    ],
    "bonusWord": "DESERT"
  },
  {
    "id": 19,
    "title": "Food & Meals",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        "R",
        "I",
        "C",
        "E"
      ],
      [
        "H",
        null,
        null,
        null,
        null,
        "A",
        null
      ],
      [
        "O",
        null,
        "T",
        null,
        null,
        "K",
        null
      ],
      [
        "N",
        "O",
        "O",
        "D",
        "L",
        "E",
        null
      ],
      [
        "E",
        null,
        "A",
        null,
        null,
        null,
        null
      ],
      [
        "Y",
        null,
        "S",
        "A",
        "L",
        "A",
        "D"
      ],
      [
        null,
        null,
        "T",
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Small white grains",
        "answer": "RICE",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Sweet treat for a birthday",
        "answer": "CAKE",
        "row": 0,
        "col": 5,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Sweet food made by bees",
        "answer": "HONEY",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Browned bread",
        "answer": "TOAST",
        "row": 2,
        "col": 2,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Long strand in your soup",
        "answer": "NOODLE",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Bowl of fresh vegetables",
        "answer": "SALAD",
        "row": 5,
        "col": 2,
        "bonus": false
      }
    ],
    "bonusWord": "NOODLE"
  },
  {
    "id": 20,
    "title": "Technology",
    "size": 7,
    "solution": [
      [
        "C",
        null,
        "C",
        "O",
        "D",
        "E",
        null
      ],
      [
        "A",
        null,
        "H",
        null,
        null,
        null,
        null
      ],
      [
        "B",
        null,
        "I",
        null,
        "M",
        null,
        null
      ],
      [
        "L",
        "A",
        "P",
        "T",
        "O",
        "P",
        null
      ],
      [
        "E",
        null,
        null,
        null,
        "U",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "S",
        null,
        null
      ],
      [
        "R",
        "O",
        "U",
        "T",
        "E",
        "R",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Wire that connects devices",
        "answer": "CABLE",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Instructions for a program",
        "answer": "CODE",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tiny computer part",
        "answer": "CHIP",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "You click with it",
        "answer": "MOUSE",
        "row": 2,
        "col": 4,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Portable computer",
        "answer": "LAPTOP",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "It shares the Wi-Fi signal",
        "answer": "ROUTER",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "LAPTOP"
  },
  {
    "id": 21,
    "title": "Camping",
    "size": 7,
    "solution": [
      [
        null,
        null,
        "T",
        "O",
        "R",
        "C",
        "H"
      ],
      [
        null,
        "T",
        null,
        null,
        "O",
        null,
        null
      ],
      [
        null,
        "R",
        null,
        null,
        "P",
        null,
        "K"
      ],
      [
        "L",
        "A",
        "N",
        "T",
        "E",
        "R",
        "N"
      ],
      [
        null,
        "I",
        null,
        "E",
        null,
        null,
        "I"
      ],
      [
        null,
        "L",
        null,
        "N",
        null,
        null,
        "F"
      ],
      [
        null,
        null,
        "S",
        "T",
        "O",
        "V",
        "E"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Handheld flashlight",
        "answer": "TORCH",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You tie things with it",
        "answer": "ROPE",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "A path through the woods",
        "answer": "TRAIL",
        "row": 1,
        "col": 1,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Handy cutting tool",
        "answer": "KNIFE",
        "row": 2,
        "col": 6,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Portable light for the dark",
        "answer": "LANTERN",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "You sleep in it outdoors",
        "answer": "TENT",
        "row": 3,
        "col": 3,
        "bonus": false
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Small camp cooker",
        "answer": "STOVE",
        "row": 6,
        "col": 2,
        "bonus": false
      }
    ],
    "bonusWord": "LANTERN"
  },
  {
    "id": 22,
    "title": "The Beach",
    "size": 7,
    "solution": [
      [
        null,
        "C",
        null,
        null,
        null,
        "S",
        null
      ],
      [
        "B",
        "O",
        "A",
        "T",
        null,
        "H",
        null
      ],
      [
        null,
        "R",
        null,
        null,
        null,
        "E",
        null
      ],
      [
        "S",
        "A",
        "N",
        "D",
        "A",
        "L",
        null
      ],
      [
        null,
        "L",
        null,
        "U",
        null,
        "L",
        null
      ],
      [
        null,
        null,
        null,
        "N",
        null,
        null,
        null
      ],
      [
        "T",
        "O",
        "W",
        "E",
        "L",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Colorful sea growth",
        "answer": "CORAL",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You collect it in the sand",
        "answer": "SHELL",
        "row": 0,
        "col": 5,
        "bonus": true
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "It floats on the water",
        "answer": "BOAT",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Open summer shoe",
        "answer": "SANDAL",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "A hill of sand",
        "answer": "DUNE",
        "row": 3,
        "col": 3,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "You lie on it at the beach",
        "answer": "TOWEL",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "SHELL"
  },
  {
    "id": 23,
    "title": "Winter",
    "size": 7,
    "solution": [
      [
        null,
        "S",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "C",
        null,
        "S",
        "K",
        "I",
        null
      ],
      [
        null,
        "A",
        null,
        "L",
        null,
        "C",
        null
      ],
      [
        "F",
        "R",
        "E",
        "E",
        "Z",
        "E",
        null
      ],
      [
        null,
        "F",
        null,
        "E",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "S",
        "T",
        "O",
        "R",
        "M"
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "You wrap it around your neck",
        "answer": "SCARF",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Slide down a snowy slope",
        "answer": "SKI",
        "row": 1,
        "col": 3,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Rain mixed with snow",
        "answer": "SLEET",
        "row": 1,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Frozen water",
        "answer": "ICE",
        "row": 1,
        "col": 5,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Turn to ice",
        "answer": "FREEZE",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "A blizzard is a snow ___",
        "answer": "STORM",
        "row": 5,
        "col": 2,
        "bonus": false
      }
    ],
    "bonusWord": "FREEZE"
  },
  {
    "id": 24,
    "title": "In the Garden",
    "size": 7,
    "solution": [
      [
        "L",
        null,
        null,
        null,
        "H",
        null,
        null
      ],
      [
        "E",
        null,
        "B",
        "L",
        "O",
        "O",
        "M"
      ],
      [
        "A",
        null,
        null,
        null,
        "S",
        null,
        null
      ],
      [
        "F",
        "L",
        "O",
        "W",
        "E",
        "R",
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        "A",
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        "K",
        null
      ],
      [
        "S",
        "E",
        "E",
        "D",
        null,
        "E",
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Green part of a plant",
        "answer": "LEAF",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "You water plants with it",
        "answer": "HOSE",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "What a flower does in spring",
        "answer": "BLOOM",
        "row": 1,
        "col": 2,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "A rose or a tulip",
        "answer": "FLOWER",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Unwanted plant",
        "answer": "WEED",
        "row": 3,
        "col": 3,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "Tool for gathering leaves",
        "answer": "RAKE",
        "row": 3,
        "col": 5,
        "bonus": false
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "You plant it to grow a plant",
        "answer": "SEED",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "FLOWER"
  },
  {
    "id": 25,
    "title": "Insects",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        "A",
        "S",
        "P",
        null,
        null
      ],
      [
        "L",
        null,
        "P",
        null,
        null,
        "B",
        null
      ],
      [
        "O",
        null,
        "H",
        null,
        null,
        "E",
        null
      ],
      [
        "C",
        "R",
        "I",
        "C",
        "K",
        "E",
        "T"
      ],
      [
        "U",
        null,
        "D",
        null,
        null,
        "T",
        null
      ],
      [
        "S",
        null,
        null,
        null,
        null,
        "L",
        null
      ],
      [
        "T",
        null,
        null,
        "F",
        "L",
        "E",
        "A"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Stinging insect with a thin waist",
        "answer": "WASP",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tiny insect that harms plants",
        "answer": "APHID",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Swarming grasshopper",
        "answer": "LOCUST",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "It makes honey",
        "answer": "BEE",
        "row": 1,
        "col": 5,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Hard-shelled crawling bug",
        "answer": "BEETLE",
        "row": 1,
        "col": 5,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "It chirps at night",
        "answer": "CRICKET",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Tiny jumping pest on pets",
        "answer": "FLEA",
        "row": 6,
        "col": 3,
        "bonus": false
      }
    ],
    "bonusWord": "CRICKET"
  },
  {
    "id": 26,
    "title": "Tools",
    "size": 7,
    "solution": [
      [
        null,
        "W",
        "R",
        "E",
        "N",
        "C",
        "H"
      ],
      [
        "T",
        null,
        null,
        null,
        null,
        "H",
        null
      ],
      [
        "A",
        null,
        null,
        "L",
        null,
        "I",
        null
      ],
      [
        "P",
        "L",
        "I",
        "E",
        "R",
        "S",
        null
      ],
      [
        "E",
        null,
        null,
        "V",
        null,
        "E",
        null
      ],
      [
        null,
        null,
        null,
        "E",
        null,
        "L",
        null
      ],
      [
        "D",
        "R",
        "I",
        "L",
        "L",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "You tighten bolts with it",
        "answer": "WRENCH",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tool for carving wood",
        "answer": "CHISEL",
        "row": 0,
        "col": 5,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "A measuring ___",
        "answer": "TAPE",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "It checks if things are flat",
        "answer": "LEVEL",
        "row": 2,
        "col": 3,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "You grip things with them",
        "answer": "PLIERS",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "It makes holes",
        "answer": "DRILL",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "PLIERS"
  },
  {
    "id": 27,
    "title": "Emotions",
    "size": 7,
    "solution": [
      [
        "T",
        null,
        null,
        null,
        "L",
        null,
        null
      ],
      [
        "E",
        null,
        null,
        "H",
        "O",
        "P",
        "E"
      ],
      [
        "N",
        null,
        "H",
        null,
        "N",
        null,
        null
      ],
      [
        "S",
        "C",
        "A",
        "R",
        "E",
        "D",
        null
      ],
      [
        "E",
        null,
        "P",
        null,
        "L",
        null,
        null
      ],
      [
        null,
        null,
        "P",
        null,
        "Y",
        null,
        null
      ],
      [
        "J",
        "O",
        "Y",
        null,
        null,
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Nervous and on edge",
        "answer": "TENSE",
        "row": 0,
        "col": 0,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Feeling all alone",
        "answer": "LONELY",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Wishing for something good",
        "answer": "HOPE",
        "row": 1,
        "col": 3,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Feeling full of joy",
        "answer": "HAPPY",
        "row": 2,
        "col": 2,
        "bonus": true
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Feeling afraid",
        "answer": "SCARED",
        "row": 3,
        "col": 0,
        "bonus": false
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "A feeling of great happiness",
        "answer": "JOY",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "HAPPY"
  },
  {
    "id": 28,
    "title": "Drinks",
    "size": 7,
    "solution": [
      [
        null,
        null,
        null,
        null,
        "W",
        null,
        "T"
      ],
      [
        null,
        null,
        "S",
        "H",
        "A",
        "K",
        "E"
      ],
      [
        null,
        "M",
        null,
        null,
        "T",
        null,
        "A"
      ],
      [
        "C",
        "O",
        "F",
        "F",
        "E",
        "E",
        null
      ],
      [
        null,
        "C",
        null,
        null,
        "R",
        null,
        null
      ],
      [
        null,
        "H",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "L",
        "A",
        "T",
        "T",
        "E",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Clear, plain drink",
        "answer": "WATER",
        "row": 0,
        "col": 4,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Drink made by steeping leaves",
        "answer": "TEA",
        "row": 0,
        "col": 6,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Thick blended milk drink",
        "answer": "SHAKE",
        "row": 1,
        "col": 2,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Coffee with chocolate",
        "answer": "MOCHA",
        "row": 2,
        "col": 1,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Hot drink that wakes you up",
        "answer": "COFFEE",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Coffee with steamed milk",
        "answer": "LATTE",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "COFFEE"
  },
  {
    "id": 29,
    "title": "Countries",
    "size": 7,
    "solution": [
      [
        null,
        null,
        "I",
        "N",
        "D",
        "I",
        "A"
      ],
      [
        null,
        "S",
        null,
        "E",
        null,
        null,
        null
      ],
      [
        null,
        "P",
        null,
        "P",
        null,
        "J",
        null
      ],
      [
        "C",
        "A",
        "N",
        "A",
        "D",
        "A",
        null
      ],
      [
        null,
        "I",
        null,
        "L",
        null,
        "P",
        null
      ],
      [
        null,
        "N",
        null,
        null,
        null,
        "A",
        null
      ],
      [
        null,
        null,
        "C",
        "H",
        "I",
        "N",
        "A"
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Country of the Taj Mahal",
        "answer": "INDIA",
        "row": 0,
        "col": 2,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Country with Mount Everest",
        "answer": "NEPAL",
        "row": 0,
        "col": 3,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Country known for flamenco",
        "answer": "SPAIN",
        "row": 1,
        "col": 1,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Land of the rising sun",
        "answer": "JAPAN",
        "row": 2,
        "col": 5,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Country north of the USA",
        "answer": "CANADA",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Country with the Great Wall",
        "answer": "CHINA",
        "row": 6,
        "col": 2,
        "bonus": false
      }
    ],
    "bonusWord": "CANADA"
  },
  {
    "id": 30,
    "title": "Time & Calendar",
    "size": 7,
    "solution": [
      [
        null,
        "A",
        "L",
        "A",
        "R",
        "M",
        null
      ],
      [
        "D",
        null,
        null,
        null,
        null,
        "O",
        null
      ],
      [
        "U",
        null,
        null,
        "M",
        null,
        "N",
        null
      ],
      [
        "S",
        "E",
        "C",
        "O",
        "N",
        "D",
        null
      ],
      [
        "K",
        null,
        null,
        "N",
        null,
        "A",
        null
      ],
      [
        null,
        null,
        null,
        "T",
        null,
        "Y",
        null
      ],
      [
        "N",
        "I",
        "G",
        "H",
        "T",
        null,
        null
      ]
    ],
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "It wakes you up",
        "answer": "ALARM",
        "row": 0,
        "col": 1,
        "bonus": false
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "First day of the work week",
        "answer": "MONDAY",
        "row": 0,
        "col": 5,
        "bonus": false
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "When the sun sets",
        "answer": "DUSK",
        "row": 1,
        "col": 0,
        "bonus": false
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "About thirty days",
        "answer": "MONTH",
        "row": 2,
        "col": 3,
        "bonus": false
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "The smallest unit on a clock face",
        "answer": "SECOND",
        "row": 3,
        "col": 0,
        "bonus": true
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "The dark part of the day",
        "answer": "NIGHT",
        "row": 6,
        "col": 0,
        "bonus": false
      }
    ],
    "bonusWord": "SECOND"
  }
];
