const { createRunOncePlugin, IOSConfig, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Compiles Rencana's App Intents into the main iOS app target.
 *
 * App Intents metadata is only extracted from the app target, so the Swift
 * cannot live in the Smart Capture pod. It is appended to AppDelegate.swift
 * rather than added as a new file because this project already has two plugins
 * rewriting the Xcode project (expo-widgets and expo-sharing both add targets),
 * and a third pass through the `xcode` serializer silently drops entries from
 * their build phases — including ExpoModulesProvider.swift, which breaks
 * autolinking. AppDelegate.swift is already in the app target's Sources phase,
 * so appending needs no project mutation at all.
 *
 * `ios/` is generated by prebuild and gitignored, so this runs on every local
 * prebuild and on EAS.
 */

const SOURCE_RELATIVE = path.join(
  'modules',
  'smart-capture',
  'ios-app-target',
  'SmartCaptureIntents.swift',
);

const BEGIN_MARKER = '// MARK: - BEGIN Smart Capture App Intents (generated by plugins/withSmartCapture.js)';
const END_MARKER = '// MARK: - END Smart Capture App Intents';

/** Swift requires every import at file scope, so they are hoisted out of the block. */
function splitImports(source) {
  const imports = new Set();
  const body = source
    .split('\n')
    .filter((line) => {
      const match = /^import\s+(\w+)\s*$/.exec(line.trim());
      if (match) {
        imports.add(match[1]);
        return false;
      }
      return true;
    })
    .join('\n')
    .trim();
  return { imports: [...imports], body };
}

const withSmartCapture = (config) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const { projectRoot, platformProjectRoot } = cfg.modRequest;
      const source = path.join(projectRoot, SOURCE_RELATIVE);

      if (!fs.existsSync(source)) {
        throw new Error(
          `[withSmartCapture] Missing ${SOURCE_RELATIVE}. The Back Tap App Intent cannot be built without it.`,
        );
      }

      const projectName = IOSConfig.XcodeUtils.getProjectName(projectRoot);
      const appDelegatePath = path.join(platformProjectRoot, projectName, 'AppDelegate.swift');
      if (!fs.existsSync(appDelegatePath)) {
        throw new Error(`[withSmartCapture] Could not find ${appDelegatePath}.`);
      }

      const { imports, body } = splitImports(fs.readFileSync(source, 'utf8'));
      let appDelegate = fs.readFileSync(appDelegatePath, 'utf8');

      // Drop a previous injection so repeated prebuilds without --clean stay
      // idempotent and always pick up edits to the module source.
      const begin = appDelegate.indexOf(BEGIN_MARKER);
      if (begin !== -1) {
        const end = appDelegate.indexOf(END_MARKER);
        appDelegate = (
          appDelegate.slice(0, begin) +
          appDelegate.slice(end === -1 ? begin : end + END_MARKER.length)
        ).trimEnd();
      }

      for (const moduleName of imports) {
        if (!new RegExp(`^import\\s+${moduleName}\\s*$`, 'm').test(appDelegate)) {
          appDelegate = `import ${moduleName}\n${appDelegate}`;
        }
      }

      fs.writeFileSync(
        appDelegatePath,
        `${appDelegate.trimEnd()}\n\n${BEGIN_MARKER}\n${body}\n${END_MARKER}\n`,
      );

      return cfg;
    },
  ]);

module.exports = createRunOncePlugin(withSmartCapture, 'with-smart-capture', '1.0.0');
